documentation/mkdocs.yml

MkDocs 0.17 features theme customization options [1] which are picked up
supported with mkdocs-material 2.0.1 [2] and later. These are now the
minimum required versions to compile our gh-pages documentation.
[1] http://www.mkdocs.org/about/release-notes/#major-additions-to-version-0170
[2] https://github.com/squidfunk/mkdocs-material/releases/tag/2.0.0

Update mkdocs.yml to MkDocs 0.17.0 format

---

Jenkinsfile

- send "build failed" mail only when an exception has been received.
- provide a non empty mail message, since an empty mail body causes the build to fail.

Fix mail notification

---

test/groovy/NeoDeploymentTest.groovy
vars/neoDeploy.groovy

Without proper quotation characters with a special semantics
on shell level (e.g. "${}", "!", """ gets escaped on shell level
before handed over to the neo tool.
neoExecutable is surrounded by double quotes since we may have
shell ${variables} inside the groovy variable.
All other variables (user, host, account, password) are surrounded
by single quotes since we do not expect to be variables used here.
The neoExecutable is

fix quotation inside neo deploy

---

pom.xml

- Deletes unused dependencies
- Fixes error for Windows builds:
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000180003ae0, pid=6092, tid=0x0000000000001df0
JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
Problematic frame:
C 0x0000000180003ae0
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
An error report file with more information is saved as:
C:\Users\XXXXXXX\Desktop\repository\github.wdf.sap.corp\ContinuousDelivery\piper-library-os\hs_err_pid6092.log
If you would like to submit a bug report, please visit: …

pom clean up

---

src/com/sap/piper/Utils.groovy

The method is related to an outdated use case
It was intended for getting the coordinates of a payload repo when the
pipeline repo is specified in the pipeline job.
That has been changed so that the pipeline (or at least a stub pipeline)
is now always contained in the payload repo and the payload repo is
always specified in the pipeline job itself.

Remove Utils#retrieveGitCoordinates

---

test/groovy/PipelineExecuteTest.groovy

node() is not necessary in the LesFurets unit tests. This is especially
misleading for the pipelineExecute step, as the step itself opens a node
closure when loading a pipeline. If used like this in Jenkins
unnecessary executors will be used.

Remove node from test pipeline

---

documentation/docs/scripts/configurationLoader.md

In configurationLoader.md the reference to commonPipelineEnvironment.md
is wrong and will give you a 404, because commonPipelineEnvironment.md
lies in a separate folder called steps.
The change was already deployed to the gh-pages!

Correct reference to commonPipelineEnvironment.md

---

test/groovy/DockerExecuteTest.groovy
vars/dockerExecute.groovy

We check
1.) if docker-workflow plugin is installed
2.) if docker itself is installed on the system hosting Jenkins
If one of the conditions is not fullfilled we try to execute
locally.
We expect use cases for the piper-lib where we cannot make strong assumtions about the environment wrt to docker.

Make docker more resilent wrt to environment

---

.travis.yml

To build the documentation mkdocs, a python package, is necessary. The
material theme is used and also needs to be installed.
To find errors in the documentation it is built with mkdocs usind strict
mode: Thus any warnings result in errors and abort the travis build.
Also we activated caching.

Build mkdocs and abort travis build on error

---

test/groovy/util/JenkinsSetupRule.groovy

I guess nobody is interested in the callstack printed into the log
during the tests.

remove printing the callstack

---

test/groovy/NeoDeploymentTest.groovy
vars/neoDeploy.groovy

When running on a slave we have to use the Pipeline method fileExists,
using the File class' exist on the absolute path fails.
The neo deployment uses the relative path as well.
The fileExists method is mocked with LesFurets.

Use fileExists to check whether archivePath really exists

---

test/groovy/MTABuildTest.groovy

The test fails on Windows due to the absolute path

bugfix absolute path

---

vars/neoDeploy.groovy

We have a default value configured at the level of the shipped defaults.
grep neoCredentialsId resources/default_pipeline_environment.yml

Remove empty string as default for neo credentials id

---

test/groovy/ArtifactSetVersionTest.groovy
vars/artifactSetVersion.groovy

By using UTC, we avoid potential issues when development happens in
different time zones. Also, daylight saving time does not exist in UTC.

Use UTC time zone for artifact version time stamp

---

documentation/docs/steps/artifactSetVersion.md
resources/default_pipeline_environment.yml
src/com/sap/piper/GitUtils.groovy
test/groovy/ArtifactSetVersionTest.groovy
test/groovy/com/sap/piper/GitUtilsTest.groovy
vars/artifactSetVersion.groovy

You might not want to add a new commit for each version, when versions
are automatically created. This commit makes this feature optional, but
enabled by default to maintain API compatibility.

Make commit of new version optional in `artifactSetVersion` step

---

test/groovy/MTABuildTest.groovy
test/groovy/NeoDeployTest.groovy
vars/mtaBuild.groovy
vars/neoDeploy.groovy

We know about two issues:
1.) groovy based file systems checks seems to be executed on Jenkins
master even if there is a node which is dispatched to a slave.
2.) Environment variable contained in the value of a provided
variable are not expanded. Example: In case we describe neoHome like
"$JENKINS_HOME/tools/neo" we do not expand $JENKINS_HOME. Hence the
file exists check for file '$JENKINS_HOME/tools/neo' fails.

Disable tool validation inside neoDeploy and mtaBuild

---

.travis.yml

Docu build is performed without deployment into gh-pages branch for pull requests in order to ensure we have no failures inside the documentation.
Some days ago preparing the mkdocs setup (pip) failed since it was not possible to get all the dependencies for mkdocs (issues with unsecure https).
Now the situation changed. There is still a warning when preparing mkdocs, but the build does not fail. In case we encounter issues again we should try to upgrade the python version  to 2.7.9 or above. Accoding to a log message when having the failing mkdocs preparation the issue with the unsecure https is resolved with 2.7.9 and higher, but we was on python version 2.7.6.

Enable docu build for PR again.

---

documentation/docs/steps/mtaBuild.md
resources/template_mta.yml
src/com/sap/piper/MtaUtils.groovy
test/groovy/MTABuildTest.groovy
test/groovy/com/sap/piper/MtaUtilsTest.groovy
test/resources/MtaUtils/package.json
vars/mtaBuild.groovy

In case the mta.yml descriptor is not present in the project sources, it could be internally generated using the information available in the package.json file and one additional parameter, applicationName, defined additionally from the user.
* name from package.json will be used for ID in mta.yml
* version from package.json will be used for the version in mta.yml
* the specified 'applicationName' parameter will be used for module name in mta.yml
Example:
MTAR_FILE_PATH = mtaBuild mtaJarLocation: env.MTA_HOME, buildTarget: 'NEO', applicationName: 'webshop'

generate mta.yml from package.json and given applicationName

---

test/groovy/ArtifactSetVersionTest.groovy
vars/artifactSetVersion.groovy

In order to use the configuration the script needs to be forwarded to MavenArtifactVersioning and to mavenExecute

Fix referencing script in setVersion

---

src/com/sap/piper/ConfigurationMerger.groovy
test/groovy/com/sap/piper/ConfigurationMergerTest.groovy

In line
https://github.com/SAP/jenkins-library/compare/fix/merging?expand=1#diff-07e7b5ab7692947662654f171daa514fR19
defaults[key] might be null, thus merge(filteredConfig[key], null, defaults[key]) will fail

Fix merging if no default values exist

---

documentation/docs/steps/mtaBuild.md
resources/default_pipeline_environment.yml
src/com/sap/piper/VersionUtils.groovy
src/com/sap/piper/tools/JavaArchiveDescriptor.groovy
src/com/sap/piper/tools/ToolDescriptor.groovy
test/groovy/MTABuildTest.groovy
test/groovy/ToolValidateTest.groovy
test/groovy/com/sap/piper/tools/JavaArchiveDescriptorTest.groovy
vars/mtaBuild.groovy
vars/toolValidate.groovy

Adds the parameter and step configuration 'mtaJarName' to make the SAP
Multitarget Archive Builder jar file configurable.
Issue #73

add mtaJarName to make 'mta.jar' configurable

---

src/com/sap/piper/GitUtils.groovy
test/groovy/ArtifactSetVersionTest.groovy
test/groovy/com/sap/piper/GitUtilsTest.groovy

This approach works also in case we are in a subdirectory of the git repo,
e.g. in the closure of a dir statement.
The decission is delegate to git rather than using internal knowledge
about git file names. Well, the directory will be always named '.git',
but nevertheless ...
May endup in a false positive in case we did not clone a repo AND there
is another git repo somewhere upwards in the file system. Maybe some
other git repo is located upstairs containing e.g. the jenkins setup.
The advantage of working also for subdirectories outweights the disadvantage
for the false positive. It is not likely that we have to deal with another
git repo upstairs, since the pipeline script is expected to be located in
the payload git repo. A phantom repo upstairs looks like a pure academical …

Check if inside git repo via rev-parse --is-inside-work-tree

---

documentation/docs/steps/mavenExecute.md
resources/default_pipeline_environment.yml
test/groovy/ArtifactSetVersionTest.groovy
test/groovy/MavenExecuteTest.groovy
test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy
vars/mavenExecute.groovy

This commit adds a flag to Maven by default, which disables the messages
like "Downloading from central".
The logger is set to level "warn", so errors will still be visible, but
successful messages won't clutter logs anymore.
This option is also set by default in the GitLab CI template file for
maven.
See [1] for reference on the option.
1: https://stackoverflow.com/a/35653426/8843830

Disable download logs in Maven by default

---

test/groovy/util/LibraryLoadingTestExecutionListener.groovy

PrepareDefaultValuesTest registers the methods "libraryResource" and "readYaml" to provide test specific configuration values. This had impacts to other test classes.
It looks like that the restoration of allowedMethods after a test method run has been forgotten.

LibraryLoadingTestExecutionListener: restore tracked methods on afterTestMethod

---

src/com/sap/piper/ConfigurationHelper.groovy
test/groovy/com/sap/piper/ConfigurationHelperTest.groovy

For some transport related steps it would be cool to have a message providing more details about what is going wrong.

withMandatoryParameter supports a error message from the caller

---

src/com/sap/piper/DefaultValueCache.groovy
test/groovy/PrepareDefaultValuesTest.groovy
vars/prepareDefaultValues.groovy
vars/setupCommonPipelineEnvironment.groovy

_This is more a proposal than a ready-to-merge pull request. Feedback, questions, other approaches, etc. welcome ..._
**functional gap:** At the moment we have no configuration layer in place for describing a system landscape on customer side.
**details:** At the moment we have these configuration layers:
* the library defaults described in ```resources/default_pipeline_environment.yml```. The content in this file provides defaults set by the library itself. This file should not be modified at customer side. 
* project specific configuration layer, based on file ```.pipeline/config.yml```. 
But there is no configuration layer for describing common properties for e.g. a customer landscape (... values which are the same for all projects of a customer).
We are currently preparing the …

Provide configuration layer for custom configuration

---

src/com/sap/piper/cm/ChangeManagement.groovy
test/groovy/CheckChangeInDevelopmentTest.groovy
test/groovy/com/sap/piper/cm/ChangeManagementTest.groovy
vars/checkChangeInDevelopment.groovy

Forwarding of the configuration map into utils classes increases maintainance efforts later in case configuration keys are changed.
An approach handling retrieval of configuration only inside the steps in much clearer compared with forwarding the config map and picking properties later on down the code.

No forwarding of config map in to ChangeManagement class.

---

test/groovy/util/JenkinsLoggingRule.groovy

With the current approach of checking log entries we are not able to
check log entries in case of a failure. But is is important to assert
log messages in case of a failure. Having reasonable log messages
simplified troubleshooting.
Hence we add JenkinsLoggingRule.expect(substring) and check after the
base of that rule has been called.
This interfears with other rules also working with an expect approach,
like e.g. ExpectedException. Which violation is presented depends on
the order or the rules around the test case.

Support check for log messages in case of exceptions in code under test

---

test/groovy/util/JenkinsLoggingRule.groovy

@CCFenner  mentioned the misplaced quotation mark alread in PR #199 , but by error I forgot to fix it.

[fix] misplaced quotation mark in assertion message

---

test/groovy/CheckChangeInDevelopmentTest.groovy
test/groovy/TransportRequestCreateTest.groovy
test/groovy/TransportRequestReleaseTest.groovy
test/groovy/TransportRequestUploadFileTest.groovy
vars/checkChangeInDevelopment.groovy
vars/transportRequestCreate.groovy
vars/transportRequestRelease.groovy
vars/transportRequestUploadFile.groovy

- In case a parameter is missing we do not thrown and AbortException
anmore, but an IllegalArgumentExcpetion, since that exception is
thrown by the configuration helper. The difference is: AbortExceptions
are contained in the log without stacktrace, other exceptions are
printed with stack trace.
- Exception messages are changed to the standard error message triggered
inside the configuration helper. In case the changeDocumentId is
retrieved also from the commit history we keep an exception message
pointing to that.
- Having references to the parameters is droped. Instead the parameters
are directly used from the configuration map.
- in case of long signatures line breaks are inserted in order to
simplify reading the code.

Validate required parameters via config helper

---

src/com/sap/piper/ConfigurationHelper.groovy

... instead of accessing the config map directy.
With that we ensure that getMandatoryProperty behaves the same like
getConfigProperty. Currently we differ e.g. with trim().

[refactor] re-use getConfigPropery inside getMandatoryProperty

---

src/com/sap/piper/VersionUtils.groovy
src/com/sap/piper/tools/ToolDescriptor.groovy
test/groovy/ToolValidateTest.groovy
test/groovy/com/sap/piper/VersionUtilsTest.groovy
test/groovy/com/sap/piper/tools/ToolDescriptorTest.groovy
vars/neoDeploy.groovy
vars/toolValidate.groovy

We agreed that the version of the neo image we are going to use (latest) will be compatible per definition. If not, the customer can configure a certain version.
#26

Remove the NEO version check

---

test/groovy/TransportRequestCreateTest.groovy
test/groovy/TransportRequestReleaseTest.groovy
test/groovy/TransportRequestUploadFileTest.groovy
test/groovy/com/sap/piper/cm/ChangeManagementTest.groovy

Up to now the upload file to transport step tested the step itself and also the ChangeManagment utils class. With that change we ensure a clear focus to one class under test. There are the tests in the default package testing the step itself. Beside that there is a dedicated test class for the ChangeManagment utils class.

decouple tests

---

test/groovy/CheckChangeInDevelopmentTest.groovy
test/groovy/TransportRequestCreateTest.groovy
test/groovy/TransportRequestReleaseTest.groovy
test/groovy/TransportRequestUploadFileTest.groovy
test/groovy/util/JenkinsCredentialsRule.groovy

Instead of configuring the credentials setup
o withCredentials
o usename
in each of our tests (for the moment change-management related)
we collect the common coding in a JUnitRule.

Introduce CredentialsRule

---

test/groovy/TransportRequestReleaseTest.groovy
vars/transportRequestRelease.groovy

otherwise we will never try to read the change document id from commit history.

[fix] Remove early check for mandatory param 'changeDocumentId'

---

resources/default_pipeline_environment.yml
test/groovy/NeoDeployTest.groovy
vars/neoDeploy.groovy

The implementation of neo as a ToolDescriptor is not necessary. The version check was already dropped, so only the creation of the executable path remained. Since the neo executable is expected on the path it can be dropped too.

Remove tool descriptor from neo deploy and config the neo docker image

---

test/groovy/MavenExecuteTest.groovy
vars/mavenExecute.groovy

The old naive check fails if an argument starts with '-B'. Now we use a
regular expression, which should correctly match if batch mode was
already supplied, and add it if not.

Improve check for batch mode in mavenExecute

---

test/groovy/NeoDeployTest.groovy
vars/neoDeploy.groovy

This reverts commit c3c7d8b14280a7ee1304bc09617159e057f2f814.
The change mentioned above is incompatible since we do not take a neoDeploy home from the configuration into account as it was before.

Revert "remove the tool descriptor from neo deploy"

---

src/com/sap/piper/ConfigurationHelper.groovy
test/groovy/com/sap/piper/ConfigurationHelperTest.groovy

With this change we can avoid coding like [this](https://github.com/SAP/jenkins-library/pull/183/files#diff-3ce088eec8992f06ecf9eddb854fe1d8R42)
and call it like this:
```
.mixin(parameters, PARAMETER_KEYS)
// check mandatory parameters
.withMandatoryProperty('changeId', { c -> return c.get('isVoter') })
.withMandatoryProperty('githubTokenCredentialsId', { c -> return c.get('isVoter') })
.withMandatoryProperty('githubOrg', { c -> return c.get('isVoter') })
.withMandatoryProperty('githubRepo', { c -> return c.get('isVoter') })
.withMandatoryProperty('projectVersion', { c -> return !c.get('isVoter') })
.use()
```
**changes**

ConfigurationHelper: add condition to withMandatoryProperty

---

test/groovy/TransportRequestUploadFileTest.groovy
vars/transportRequestUploadFile.groovy

This allows the steps to interact without using return values (which is not possible in
declarative pipelines). On the other hand we have depencencies between the steps based
on the status of the commonPipelineEnvironment.

Take mtarFilePath in commonPipelineEnviroment into account

---

documentation/docs/steps/neoDeploy.md
test/groovy/NeoDeployTest.groovy
vars/neoDeploy.groovy

neo deploy is not capable of fetching the deployable out of the common pipeline environment (parameter mta file path).
-

neoDeploy with archvive from CPE

---

test/groovy/ArtifactSetVersionTest.groovy
vars/artifactSetVersion.groovy

* Only one sh statement instead of three.
* No need to change the origin url and with that no footprint on the build servers git repo.
Integration test not performed so far, hence status is "in progress"

[refactoring] streamline git calls

---

src/com/sap/piper/versioning/MavenArtifactVersioning.groovy
test/groovy/ArtifactSetVersionTest.groovy
test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy

The pom.xml.versionBackup file is not needed since the
old file with the old version is available in the history.

avoid creating pom.xml.versionBackup 

---

vars/artifactSetVersion.groovy

rather than checking for existing .git folder. An existing .git folder is a necessarry, but not a sufficient
condition here.
Adapting the test is not necessary. The gitUtil itself is not mocked, but the underlying sh calls are
already mocked accordingly.
-

[refactoring] artifactSetVersion: use gitUtils#insideWorkTree

---

src/com/sap/piper/cm/ChangeManagement.groovy
test/groovy/com/sap/piper/cm/ChangeManagementTest.groovy

the call of the cmclient command 'upload-file-to-transport' with a file path containing spaces fails. Since getCMCommandLine does not quote the option values the shell ignores anything after the first space of the file path found.
[workspace] Running shell script Exception in thread "main" java.lang.IllegalArgumentException: Cannot read upload file '/var/jenkins_home/jobs/copy'. at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
hudson.AbortException: Cannot upload file '/var/jenkins_home/jobs/copy of solution teched 2018/workspace/com.sap.teched2018.cna370.fiori.mtar' for change document '8000000225' with transport request 'SCDK900002'. Return code from cmclient: 1. ***

cmclient call needs to quote the file path

---

documentation/docs/configuration.md

The coding box was too long since the closing markup for the code box
had a leading blank, hence the end of the code box was not properly detected.

[docu] fix markup

---

test/groovy/MtaBuildTest.groovy

should have been removed earlier with the other pull request removing writing the test files.
This is pure leftover.

Prune useless code from MTABuild test.

---

test/groovy/ArtifactSetVersionTest.groovy

if we don't mock the GitUtils here changes inside GitUtils affecting the git commands
issued at the command line requires changes here. In fact we have to react on
implementation details of the GitUtils here. It is better to be independent from that
implementation details here since this leads to more focused and smaller commits.
The quint-essence is: Up to now we described what should happen on the ```GitUtils``` layer via mocking some shell calls. Now we describe what should happen on the ```GitUtils``` layer by directly mocking this.

mock GitUtils

---

vars/commonPipelineEnvironment.groovy

We get getters and setters generated automatically.
IMO we should be able to explain each line of code. For me it is hard do explain why we have getters and setters, since groovy is able to automagically create getters and setters. Does anybody know a good reason for writing down the getters and setters explictly?
See:
* [here](https://github.com/SAP/jenkins-library/pull/298#issuecomment-421981041)
* and [here](https://en.wikipedia.org/wiki/Occam%27s_razor)

Remove explict getters and setters from common pipeline environment

---

test/groovy/util/BasePiperTestContext.groovy

In fact nobody reads it, but on some IDEs it is shown when tests are executed.
In case this was some kind of 'manual' asserts: Should we replace it by real asserts?

Remove output to stdout from tests

---

.github/CONTRIBUTING.md

There is no official advice that our pipeline steps must use ```void``` as a return type as discussed yesterday with @OliverNocon @CCFenner @rodibrin @thorstenwillenbacher .
Especially feedback from the colleagues not involved in that face-to-face discussion is appreciated: @daniel-kurzynski (Daniel, please share with more colleagues if there is a need for further discussions).

Pipeline steps are expected not to return a return value

---

src/com/sap/piper/ConfigurationHelper.groovy
test/groovy/com/sap/piper/ConfigurationHelperTest.groovy

it is the duty of the configuration helper to build a map
providing the configuration. Having facilites to use the
ConfigurationHelper as some kind of configuration registry
makes life more complicated.
Is there any use-case for having the ConfigurationHelper
as configuration registry?
If not we should make the getConfigProperty methods
private.
And: yes, I know about the bug that private fields and
method are not really private in groovy ...

Limit usage of ConfigurationHelper to the builder pattern

---

src/com/sap/piper/ConfigurationHelper.groovy
test/groovy/com/sap/piper/ConfigurationHelperTest.groovy

With the current approach we fail at the first mandatory parameter
which is not present. Any other missing mandatory parameter is not
reported.
In case of multiple missing parameters somebody fixes the reported
parameter and encounters the next missing parameter at the next build.
And so on, until all parameters are fixed.
With the proposal here we catch all missing parameters and report them
all at once. This speeds up the time it needs to fix configuration
issues.
By default the old behaviour is not changed. In order to trigger the
new behavour a call to method collectValidationFailures() is
required.
We can also discuss if it would make sense to change the default
behaviour so that we fail always reporting all missing parameters.

Report all missing mandatory parameters instead of only the first on

---

test/groovy/ArtifactSetVersionTest.groovy
vars/artifactSetVersion.groovy

by the way: in the tests we assert the git commands, but the order is not asserted despite the order is significant. But it is this way before and after that change ...

[refactoring] Reduce number of sh calls

---

documentation/docs/steps/healthExecuteCheck.md
documentation/mkdocs.yml
resources/default_pipeline_environment.yml
test/groovy/HealthExecuteCheckTest.groovy
vars/healthExecuteCheck.groovy

This step allows to perform a basic health check on an installed application.
It verifies that your app has a simple health endpoint available and that there is no error when calling it.

add step healthExecuteCheck

---

documentation/docs/steps/cloudFoundryDeploy.md
src/com/sap/piper/CfManifestUtils.groovy
test/groovy/CloudFoundryDeployTest.groovy
test/groovy/com/sap/piper/CfManifestUtilsTest.groovy
vars/cloudFoundryDeploy.groovy

**changes:**
Handle the case when cloud foundry manifest follows the new format (list of buildpacks) and transform to a single buildpack, since the blue-green plugin can't handle the new API.

Implement workaround for incompatible change in cloud foundry API

---

.codeclimate.yml

**changes:**
- exclude `*.png` & `*.ico` files from scan
- exclude `cfg/id_rsa.enc` file from scan

exclude images and key file from Code Climate editorConfig scan

---

.travis.yml

**changes:**
- disable maven log infos like:
```
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/org/eluder/coveralls/coveralls-maven-plugin/4.3.0/coveralls-maven-plugin-4.3.0.jar
```

disable download logs in maven

---

.codeclimate.yml

**changes:**
- deactivate Markdown rule [MD013](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length) - *Line length*
Line length limit is not applicable for generated docs (automatic line breaking).

deactivate MD013 - line length

---

documentation/docs/steps/transportRequestCreate.md
src/com/sap/piper/cm/StepHelpers.groovy
test/groovy/CommonStepsTest.groovy
test/groovy/TransportRequestCreateTest.groovy
test/groovy/TransportRequestReleaseTest.groovy
test/groovy/TransportRequestUploadFileTest.groovy
test/groovy/com/sap/piper/cm/StepHelpersTest.groovy
vars/checkChangeInDevelopment.groovy
vars/commonPipelineEnvironment.groovy
vars/transportRequestCreate.groovy
vars/transportRequestRelease.groovy
vars/transportRequestUploadFile.groovy

Pipeline steps must not return any value from a call (return type ```void```). TransportRequestId is now handled via common pipeline environment.
```transportRequestCreate``` puts the transport request id into the common pipeline environment. Subsequent steps (```transportRequestUploadFile```, ```transportRequestRelease```) reads the transport request id from CPE if there is no value provided via parameter to these steps. If no parameters is provided to the step and if there is nothing inside CPE, the git commit history is traversed in order to lookup a transport request id.

transport request id also via cpe

---

.codeclimate.yml

Is it IMO completly normal to use Boolean.getBoolean(./.).
What is stated in the rule description
>  It is often mistakenly used to attempt to read user input or parse
is not a cool reason for having that rule. With such an approach we
can knock out a lot of APIs which can be misunderstood. It is the
duty of the developer to understand the API s?he is using.
The alternate way would be
'Boolean.parseBoolean(System.getProperty('xxx'))'
which is not that convenient like Boolean.getBoolean('xxx').
**changes:**
-

Disable check for Boolean.getBoolean()

---

documentation/docs/steps/testsPublishResults.md
resources/default_pipeline_environment.yml
test/groovy/TestsPublishResultsTest.groovy

**changes:**
- update jUnit pattern to work also for projects which do not use surefire plugin.

testsPublishResults: Make jUnit pattern more universal

---

documentation/docs/steps/cloudFoundryDeploy.md
resources/default_pipeline_environment.yml
test/groovy/CloudFoundryDeployTest.groovy
vars/cloudFoundryDeploy.groovy

* Added an option to keep the old instance in case of a blue-green deployment.
* check `cf logout` when testing deploy methods.
related issue: #323

Provide option to Stop and not delete old instance on BlueGreenDeploy

---

vars/cloudFoundryDeploy.groovy

**changes:**
This change fixes an error which only occurs in a Kubernetes landscape.
When only initial stashes are passed, the deployment will fail since it misses the artifact to be deployed.
Solution: pass empty stash map thus Docker execution on Kubernetes will respect all content in the current workspace.

cloudFoundryDeploy - fix stashing behavior

---

test/groovy/CommonStepsTest.groovy

We searched for the slash, but on win like operating system we have of course a backslash.

[fix] Make regex in test Operating System independent.

---

test/groovy/util/JenkinsShellCallRule.groovy

* toString is helpful for troubleshooting during developing tests
* equals/hashCode are required in case somebody would like to register
some responses again (e.g. register something valid almost all the time, and
register something more specific for a certain test).

Implement hashCode/equals/toString for JenkinsShellCallRule

---

vars/cloudFoundryDeploy.groovy

Resolves #425
**changes:**
- Fail CF deployments when one command does not return a successful code to make the error more obvious

Fail CF Deployment Shell Script Early

---

documentation/docs/steps/dockerExecuteOnKubernetes.md
test/groovy/DockerExecuteOnKubernetesTest.groovy
vars/dockerExecuteOnKubernetes.groovy

Depending on the Docker image used the default shell will not work in certain cases.
**changes:**
This extends the executeDockerOnKubernetes step to be able to use a custom shell according to https://github.com/jenkinsci/kubernetes-plugin#specifying-a-different-shell-command-other-than-binsh

executeDockerOnKubernetes - specify custom shell

---

documentation/mkdocs.yml

- add link to `newmanExecute` docs

docs: add reference to newman page

---

test/groovy/NewmanExecuteTest.groovy
vars/newmanExecute.groovy

**changes:**
- uses user-specific .npm-global directory `~/.npm-global`
- extend `$PATH` to `~/.npm-global/bin`
fixes #445 
see https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#global-npm-dependencies

newmanExecuteTests: use user-specific .npm-global directory

---

test/groovy/CloudFoundryDeployTest.groovy
vars/cloudFoundryDeploy.groovy

Internal name was used: writeInflux -> influxWriteData

cloudFoundryDeploy: fix naming of Influx step 

---

documentation/docs/steps/cloudFoundryDeploy.md
test/groovy/CloudFoundryDeployTest.groovy
vars/cloudFoundryDeploy.groovy

mta deploy plugin has flag:
` --no-confirm` which is described as _"Do not require confirmation for deleting the previously deployed MTA apps"_
This flag is essentials for performing fully automated blue-green deployments.

cloudFoundryDeploy - patch mta blue-green deployment

---

test/groovy/DockerExecuteTest.groovy
vars/dockerExecute.groovy

command `which` requires a dedicated OS package to be installed.
In case a Jenkins Master or Jenkins Slave Image does not contain `which`, although `docker` command is available the step took a wrong turn.
This removes the check using `which` since checking `docker ps` is sufficient.

dockerExecute - fix issue when image does not contain which

---

vars/dockerExecute.groovy

since it is not intendend to expose the method docu as api doc.

dockerExecute: make javadoc comment to 'normal' comment

---

resources/default_pipeline_environment.yml
vars/dockerExecuteOnKubernetes.groovy

Fix stashing behavior to include all files in workspace.
This was for example an issue for PR-voting in Docker pipeline since `Dockerfile` has been excluded from stashing

Fix regression introduced with #474

---

documentation/bin/createDocu.groovy

in case there is a pseudo annotation '@see' found in a step docu the docu is retrived from
the parameter with the same name in the other step. Format is:
'@see <OTHER_STEP_NAME>'
This simplifies documentation for parameters with same name and same
semantics used in more than one step.

implement @see strategy

---

vars/cloudFoundryDeploy.groovy

Widens the lookup space for an mtar file to the whole workspace. Necessary because mta build tool creates mtar in workspace root.
Still includes the target folder and reuses the existing solution for multiple mtars giving a hint to specify a concrete mtaPath.

Lookup mtar in the whole workspace

---

documentation/docs/steps/newmanExecute.md

fix: table not generated by mkdocs due to wrong syntax

---

test/groovy/UiVeri5ExecuteTestsTest.groovy

The test class is in the default package and not in a package 'steps'.

[fix] remove inapproriate package statement

---

test/groovy/util/LibraryLoadingTestExecutionListener.groovy

We should try to avoid promting statements to the log during tests. This is basically
some kind of manual/visual checking of conditions. This does not work since in most cases
nobody scans test logs manually/visually. I think this is often a smell for missing assertions.

Remove println statements from default registered sh closure

---

test/groovy/MailSendNotificationTest.groovy

Nobody will have a look at println statements emitted by tests. Proper way is to assert.
* log is empty, not sure if it makes sense to assert that the log is empty.
* result is already asserted, so everything is fine there ...

Remove println statements from tests

---

vars/checkChangeInDevelopment.groovy

According to the documentation the parameter ```changeManagement``` should be configurable with general scope.

fix general config for parameter changeManagement

---

src/com/sap/piper/tools/neo/NeoCommandHelper.groovy
test/groovy/FioriOnCloudPlatformPipelineTest.groovy
test/groovy/NeoDeployTest.groovy
test/groovy/com/sap/piper/tools/neo/NeoCommandHelperTest.groovy
vars/neoDeploy.groovy

No configuration options anymore for `neo.sh`. It is expected that neo is configured properly on the system or in the docker container (folder containing `neo.sh` is in path or symbolic link to neo.sh from `/usr/local/bin`, environment variables set accordingly (if any)).

neo toolset not configurable

---

src/com/sap/piper/tools/neo/NeoCommandHelper.groovy
test/groovy/NeoDeployTest.groovy
vars/neoDeploy.groovy

In case of a mis-configuration we get a hint like "host is missing".
Actually it should be "neo/host is missing" since the parameter "host" is nested inside "neo".
Having simply "host" confuses the person troubleshooting this issue.
With this change the input validation is performed right at the beginning of the step.
The NeoCommandLine helper does not check a second time now.

Perform parameter validation early, do not truncate parameters

---

resources/default_pipeline_environment.yml
test/groovy/DockerExecuteOnKubernetesTest.groovy
vars/dockerExecuteOnKubernetes.groovy

*  Make the Kubernetes ns configurable
If one Jenkins Master is used by multiple Teams, it is desirable to
schedule K8S workloads in separate workspaces.
*  Add securityContext to define uid and fsGroup
In the context of the Jenkins k8s plugin it is uids and fsGroups play an
important role, because the containers share a common file system.
Therefore it is beneficial to configure this data centrally.
To achieve this, we change the way pods are defined. Instead of using the DSL provided by the Kubernetes plugin, we specify pods directly as Kubernetes Objects.
This has the advantage of unlocking Kubernetes features which are not
exposed via the Kubernetes plugin, including all Kubernetes security
features.

Make K8S integration more configurable

---

test/groovy/NeoDeployTest.groovy
vars/neoDeploy.groovy

With #561 sanity checks at beginning of neoDeploy covers also neo host and account.
But for deploy mode `warProperties` these values are expected in the corresponding properties file. Hence we must not check that with the sanity checks.

Fix sanity checks for warPropertiesFile deploy mode.

---

test/groovy/FioriOnCloudPlatformPipelineTest.groovy
vars/fioriOnCloudPlatformPipeline.groovy

Reading the documentation, it is sufficient to use fioriOnCloudPlatformPipeline to build and deploy SAPUI5 application. However, in the prepare step only the parameters were set. The user has to explicitly checkout the sources of the project.

enhance prepare stage with cleanup and checkout

---

README.md

Start to remove https://github.com/SAP/jenkins-pipelines from documentation for deprecation.

[docu] remove old reference pipelines

---

test/groovy/NeoDeployTest.groovy

- Renames configProperties to warProperties since the name is misleading.
-  Adds JenkinsFileExistsRule in order to follow rules format.
- Removes deprecated check related to the old config framework.

Format neo deploy test

---

vars/dockerExecute.groovy
vars/dockerExecuteOnKubernetes.groovy
vars/pipelineExecute.groovy
vars/pipelineRestartSteps.groovy

Certain steps should always fail, even though resilience option `failOnError=false` is used.
* Docker execution typically happens in another step. We should not hide errors here but rather handle their resilience in the step which uses `dockerExecute` and `dockerExecuteOnKubernetes`.
* Wrapper steps like `pipelineExecute`, `pipelineRestartSteps` should not hide errors. If an error occured this has to be considered as **intentional** and not hidden accidentially in case resilience option is switched on.

Avoid unwanted behavior when using resilience options

---

documentation/bin/createDocu.groovy

In case there is a @see tag provided for a parameter in the description,
the possible values are only fetched from the corresponding source in
case there is no explict value provided for the possible values.
In case the source does not contain a possible value tag nothing is
transfered.

fetch possible values from @see

---

test/groovy/CommonStepsTest.groovy
test/groovy/templates/PiperPipelineTest.groovy
vars/buildSetResult.groovy
vars/piperPipeline.groovy

**changes:**
- add convenient step to adjust the build result
- set `currentBuild.result` accordingly to the executed post stage

piperPipeline: handle build result correctly

---

test/groovy/MtaBuildTest.groovy
vars/mtaBuild.groovy

Allow setting custom settings file for maven in mta build, which is for example required if a custom maven repo needs to be used.

Honor maven user-settings file for mta build

---

test/groovy/templates/PiperInitRunStageConfigurationTest.groovy
vars/piperInitRunStageConfiguration.groovy

extends init condition with condition `configKeys`
This condition allows to specify a list of configuration keys which if any key is set will activate the respective step & stage

Pipelines - extend init conditions

---

resources/default_pipeline_environment.yml
test/groovy/WhitesourceExecuteScanTest.groovy

golang scan requires sources to be present. They are already part of the `checkmarx` stash which can be used here.

whitesourceExecuteScan - fix stashing behavior for golang

---

documentation/docs/steps/slackSendNotification.md
test/groovy/templates/PiperInitRunStageConfigurationTest.groovy
vars/piperInitRunStageConfiguration.groovy

support a nested structure for config keys for initialization conditions, like
```
Acceptance:
stepConditions:
cloudFoundryDeploy:
configKeys:
- 'cfSpace'
- 'cloudFoundry/space'
```

pipeline initialization - support nested keys

---

test/groovy/MtaBuildTest.groovy
vars/mtaBuild.groovy

To allow users to use other registries than npmjs.com this change makes the npm registry used in a mtaBuild configurable.

Enable configuration of npm registry for mtaBuild

---

documentation/docs/steps/neoDeploy.md

due to wrong indentation in the md file the excpetions are not rendered as expected. The reasons
why an exception occures is on the same level like the exception, but should have only level more.
Fixes #692.

Fix exception list for step neoDeploy

---

src/com/sap/piper/ConfigurationHelper.groovy
src/com/sap/piper/MapUtils.groovy
test/groovy/com/sap/piper/MapUtilsTest.groovy

The config map prepared by `ConfigHelper` is a mix from several configuration levels. The lowest config level (`DefaultValueCache`) is shared between several `ConfigHelper`/step invocations. In case a Map or Collection which is inherited from the `DefaultValueCache` level gets modified, this is also visible for all subsequent steps. This causes trouble and situations which are hard to debug (See e.g. https://github.com/SAP/jenkins-pipelines/issues/16).
With this change here each invocation of ConfigHelper.use() provides a deep defensive copy. With that we can ensure that there is no configuration update from one step to another.
There is another related pull request making the DefaultValueCache immutable (#642). This PR is not superseded by thisone. This two PRs complements each other. …

Provide a deep config copy from ConfigHelper.use()

---

.travis.yml

Since some weeks we create a docu metadata.json file which contains the same information we use for rendering the md files - and finally the published documention.
That docuMetadata.yml is intended to be used as input for wizzard generators.
In order to simplify the consumption of that file we have the requirement to include this file in the gh-pages branch  - that branch holds also the generated docu.

Provide docu metadata in gh-pages branch

---

documentation/docs/scenarios/CAP_Scenario.md

Missing colon in yaml example.

Fix typo in yaml

---

test/groovy/CommonPipelineEnvironmentTest.groovy
test/groovy/WhitesourceExecuteScanTest.groovy
vars/whitesourceExecuteScan.groovy

Having the executed WhiteSource project names in `commonPipelineEnvironment` will help downstream steps to re-use these names for example to conduct further checks against these projects.

whiteSourceExecuteScan - allow passing projects via cpe

---

test/groovy/DockerExecuteOnKubernetesTest.groovy

depending on the execution order tests may fail.
This solves this issue

fix flaky tests for dockerExecuteOnKubernetes

---

test/groovy/DockerExecuteOnKubernetesTest.groovy
vars/dockerExecuteOnKubernetes.groovy

stashing .git directory had negative side-effects.
Solution would be to stash `.git` folder and unstash in `dockerExecuteOnKubernetes` only if required for a dedicated scenario.

dockerExecuteOnKubernetes - revert #739

---

test/groovy/MtaBuildTest.groovy
vars/mtaBuild.groovy

The PATH is now correctly substituted.

Fix PATH substitution

---

vars/piperStageWrapper.groovy

If an error occurs in a `piperStageWrapper`, the message `Current build result in stage xyz is SUCCESS.` is logged.
```
17:11:52  ----------------------------------------------------------
17:11:52  --- An error occurred in the library step: runBuild
17:11:52  ----------------------------------------------------------
...
17:11:52  ----------------------------------------------------------
17:11:52  --- End library step of: runBuild ---
[Pipeline] }
[Pipeline] // parallel
[Pipeline] echo
17:11:54  Current build result in stage xyz is SUCCESS.
...
```
The used Jenkins variable `currentBuild.currentResult` is not yet updated and therefore this misleading status is logged.

piperStageWrapper: remove misleading log message

---

vars/handlePipelineStepErrors.groovy

* avoid the use of SimpleTemplateEngine in areas that underly CPS transformation since it uses a non serializable java.io.StringWriter
- [not relevant] Documentation

Use GStringTemplateEngine instead of SimpleTemplateEngine

---

documentation/docs/steps/pipelineStashFiles.md
resources/default_pipeline_environment.yml

While D source code files not used in checkmarx, the stash ```checkmarx``` is used for various purposes (e.g. in step detectExecuteScan). Therefore added D source code files to stash ```checkmarx```.
Maybe an additional stash ```additionalSourceFiles``` makes sense in general?

pipelineStashFiles: Add *.d, *.di

---

documentation/mkdocs.yml
resources/com.sap.piper/pipeline/stageDefaults.yml
resources/com.sap.piper/pipeline/stageOrdinals.yml
test/groovy/BatsExecuteTestsTest.groovy
test/groovy/templates/PiperPipelineStageAdditionalUnitTestsTest.groovy
test/groovy/templates/PiperPipelineStageInitTest.groovy
vars/batsExecuteTests.groovy
vars/buildExecute.groovy
vars/piperPipeline.groovy
vars/piperPipelineStageAdditionalUnitTests.groovy
vars/piperPipelineStageBuild.groovy
vars/piperPipelineStageInit.groovy
vars/piperPipelineStageIntegration.groovy
vars/piperStageWrapper.groovy

* fix stage name in documentation
* fix doc generation for integration stage
* verbose output
* add default stage ordinals
* `buildExecute`, properly handle empty `containerBuildOptions`
* `buildExecute` fix wrong script reference
* make usage of `batsExecuteTests` possible

Docker Pipeline - fixes and small adoptions

---

documentation/mkdocs.yml

Adding the step to mkdocs index was forgotten in #782

Add tmsUpload to mkdocs index page

---

pom.xml

There is a possibility with maven to inject the version number into the build (see https://maven.apache.org/maven-ci-friendly.html).
This will allow us to publish regular releases without permanent PRs for version updates.
- ~[ ] Tests~ not relevant
- ~[ ] Documentation~ not relevant

Make library versioning more flexible

---

src/com/sap/piper/JsonUtils.groovy
test/groovy/GithubPublishReleaseTest.groovy
vars/githubPublishRelease.groovy

So far some special characters have not been properly encoded when creating a release.
This is addressed by using a new JsonUtils method now.

githubPublishRelease - ensure proper JSON encoding

---

test/groovy/HandlePipelineStepErrorsTest.groovy
vars/handlePipelineStepErrors.groovy

With https://jenkins.io/blog/2019/07/05/jenkins-pipeline-stage-result-visualization-improvements/ it has been made possible to allow for a better visualization in case certain pipeline stages are 'UNSTABLE'
This is about using the new feature if available with a fall-back to old behavior.

use new unstable step to better visualize pipeline errors

---

test/groovy/SetupCommonPipelineEnvironmentTest.groovy
vars/setupCommonPipelineEnvironment.groovy

Allows the default configuration file to be `config.yaml` instead of `config.yml`. When I have made this mistake in the past it has taken me a long time to understand what I did wrong, why the config was not loaded properly.

setupCommonPipelineEnvironment: support yaml config file ending

---

test/groovy/DockerExecuteTest.groovy
vars/dockerExecute.groovy

* At the moment the configured env vars passed to `dockerExecute` are not used when executing inside an already created pod
* This change creates a list from `config.dockerEnvVars` which will then be used as env vars for the execution inside a docker container, inside an already created pod of Kubernetes

Pass configured env vars to docker execution in existing container

---

test/groovy/templates/PiperPipelineStageInitTest.groovy
vars/piperPipelineStageInit.groovy

Before: complete scmInfo was handed over via method signature.
After: Only the relevant part (GIT_URL from scmInfo) is handed over.
All the other properties from scmInfo are not used in the method body.
With this appraoch it is more obvious what is used inside the method.

more precise param handover (gitUrl) in piperPipelineStageInit

---

vars/dockerExecuteOnKubernetes.groovy

When using this function with only a single container instead of a `containerMap` (e.g. from the `dockerExecute` function), the key of the resulting `containerMap` is of type `org.codehaus.groovy.runtime.GStringImpl`, not `java.lang.String`, against which it will be compared later in Line 290, when determining the `imagePullPolicy`, resulting in it being always `IfNotPresent`. 
Same with the `containerCommands` Map.
A simple `.toString()` compiles the GString to a normal Java String and therefore fixes the comparison.

Fix imagePullPolicy always being IfNotPresent when executing single container

---

documentation/docs/steps/piperPipelineStagePost.md

There are at the moment no stage docu pages. I guess this has been added too early
by mistake. Maybe we should remove this for now since it triggers a warning during docu generation.

Remove template docu page for piperPipelinStagePost

---

test/groovy/MailSendNotificationTest.groovy
vars/mailSendNotification.groovy

Added `--first-parent` option to the `git log` command to ensure that only the first parent of a merge commit is being considered for author and committer determination. This should help with getting our culprits fan-out under control.

mailSendNotification: Avoid full merge trace being added to culprits

---

vars/whitesourceExecuteScan.groovy

whitesourceExecuteScan: Fix path for archiving UA logs

---

pkg/config/defaults.go

Looks strange to have the close that early.
With the current test setup (... using a no-op closer) closing that
early will not have any impact. Not sure in case we have something
which gets really closed.

defer close

---

test/groovy/TmsUploadTest.groovy
vars/tmsUpload.groovy

Right now we fail with some error message from curl.
The error messages is:
```
Warning: setting file /var/jenkins_home/workspace/TMS-Upload/doesNotExist  
Warning: failed!
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162    0     0    0   162      0   1338 --:--:-- --:--:-- --:--:--  1338
curl: (26) read function returned funny value
```
which does not clearly point to the issue.

Fail early if file which should be uploaded does not exist.

---

test/groovy/CloudFoundryDeployTest.groovy
vars/cloudFoundryDeploy.groovy

Small change beyond refactoring: for mtaDeploy the user is now quoted.
As promissed in [PR 865](https://github.com/SAP/jenkins-library/pull/865#discussion_r324145341)  common coding between mtaDeploy and cfNativeDeploy is now condenced.

[refactoring] condence common coding for cf deploy

---

pom.xml
resources/default_pipeline_environment.yml
test/groovy/TestsPublishResultsTest.groovy

- update default file name pattern for cobertura coverage files in xml format. the new pattern should work for both Java (e.g. `target/cobertura/cobertura-coverage.xml`) as well as for UI5 (e.g. `target/cobertura/Chrome 76/cobertura-coverage.xml`)
- update the test case for the default settings of `testsPublishResults`: match the file pattern against sample file paths rather than just comparing the pattern itself

Make cobertura defaults compatible with UI5

---

cmd/getConfig.go
pkg/config/config.go

In case there was no project config file (`.pipeline/config.yml`)  we failed with a panic. In the current groovy code we are able to work also without project config. Should be the same for go also.
1.) this is handy for poc'ing
2.) It is a valid scenario to have no project config, eg. in case everything can be defined on landscape layer.

Fix: getting config should also work in case there is no project config

---

cmd/getConfig.go
cmd/githubPublishRelease_generated.go
cmd/karmaExecuteTests_generated.go
cmd/piper.go
cmd/piper_test.go
cmd/version_generated.go
go.mod
pkg/generator/step-metadata.go
pkg/generator/testdata/TestProcessMetaFiles/step_code_generated.golden

Allow for package external access to general configuration.
Use-case: re-use individual steps

Export general configuration

---

pkg/generator/helper/helper.go

When using step generator outside of the current package the `PrepareConfig` call was not done using the prefix.

Fix bug in step generator

---

Dockerfile
pkg/log/log.go

**changes:**
- The *library* field in the `logrus.Entry` is assigned with the url of the current (built time) repository.
This way forks and dependent libraries provide the correct value in the logger.

assign library field in logger with respect of containing repository

---

documentation/docs/steps/cloudFoundryCreateService.md
resources/default_pipeline_environment.yml
test/groovy/CloudFoundryCreateServiceTest.groovy
vars/cloudFoundryCreateService.groovy

Bug fix for plugin call, wrong parameter was used. Only default manifest-service.yml filename was working before.
Provide default value for stash-content to support execution in pipeline templates.
using "deployDescriptor" which contains all yml files. 
Added forgotten documentation md file for step.

Fix bug and added documentation for cloudFoundryCreateService step

---

vars/sonarExecuteScan.groovy

**changes:**
- in case a `.git` file is already present, no unstash of `git` stash is done to avoid read/write issues
(`java.nio.file.AccessDeniedException: /data/jenkins/workspace/project/.git/objects/pack/pack-c9858d29b71082e85.idx`)
- in case the `git` unstash fails, the pipeline will not stop as SCM analysis is optional and only necessary for PR decoration

fix: sonarExecuteScan: safeguard unstash of git metadata

---

src/com/sap/piper/MapUtils.groovy
test/groovy/com/sap/piper/MapUtilsTest.groovy

Adds a comment and a test to make the behaviour of `MapUtils#merge()` more obvious.

Clarify precedence in MapUtils#merge()

---

.travis.yml

remove outdated parameter for call to `piper githubPublishRelease`

Update parameters to githubPublishRelease

---

cmd/getConfig.go
cmd/getConfig_test.go

Up to now: provided explicity via command line argument and also contained in the
step metadata (which are as a file also provided as command line argument).
Now it is retrieved from the metadata file.
closes #952

Remove redundancy: no duplicate stepName

---

resources/default_pipeline_environment.yml
vars/mtaBuild.groovy

Due to #970 pipeline are failing with `[ERROR][mtaBuild] BuildTool 'npm' not supported!` or `[WARNING][dockerExecute] Cannot connect to docker daemon (command 'docker ps' did not return with '0'). Configured docker image 'null' will not be used.`. Configuration parameters are influencing the docker image selection in the `mtaBuild` step.
**changes:**
- rename `buildTool` parameter to `mtaBuildTool` to avoid parameter clashes

fix: mtaBuild: avoid parameter clash

---

resources/default_pipeline_environment.yml
test/groovy/SonarExecuteScanTest.groovy
vars/sonarExecuteScan.groovy

The SonarJS plugin [requires](https://docs.sonarqube.org/latest/analysis/languages/javascript/) NodeJS 8+ to be installed.
The PR changes the use image to `node:8-stretch` and handle TLS certificates differently to work around the absence of the Java `keytool` in the image.

fix(sonar): run sonar scan in NodeJS container

---

src/com/sap/piper/Utils.groovy
vars/slackSendNotification.groovy

**changes**: 
- correct parameter names for `stash` and `slackSend` steps to fix 'unknown parameter' warnings
```
WARNING: Unknown parameter(s) found for class type 'jenkins.plugins.slack.workflow.SlackSendStep': collectTelemetryData
```
```
WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.support.steps.stash.StashStep': exclude
```
fixes #1079

fix: correct step parameters (unknown parameters found)

---

pkg/piperenv/environment.go

I guess the white spaces are not significant.
We had e.g. a trailing `\n` in one of the CPE related files.

Trim spaces from config value while reading CPE

---

test/groovy/PiperStageWrapperTest.groovy
test/resources/stages/test_old_extension.groovy
vars/artifactSetVersion.groovy
vars/piperStageWrapper.groovy

* Fix a syntax error in vars/artifactSetVersion.groovy
* Wrap calling of extensions scripts "interceptors" in a method which detects the API used by the extension script.

Introduce support for different"interceptor API" in extensions

---

test/groovy/JenkinsMaterializeLogTest.groovy
vars/jenkinsMaterializeLog.groovy

The constructor for hudson.FilePath does not take a file, but rather a
string containing the path to the file, cf https://javadoc.jenkins.io/hudson/FilePath.html#FilePath-hudson.remoting.VirtualChannel-java.lang.String-

Fix Could not find matching constructor for: hudson.FilePath

---

resources/debug_report.txt
src/com/sap/piper/DebugReport.groovy
test/groovy/HandlePipelineStepErrorsTest.groovy
test/groovy/PiperStageWrapperTest.groovy
test/groovy/com/sap/piper/DebugReportTest.groovy
test/resources/stages/test_global_overwriting.groovy
vars/handlePipelineStepErrors.groovy
vars/piperStageWrapper.groovy

The DebugReport is a global instance where steps can store information relevant for internal diagnoses of failed pipelines. In the SDK Pipeline, this is used to generate a debug report within the postActionArchiveDebugLog step. The reason for adding this to Piper is to feed information about extended or overwritten stages in piperStageWrapper into the DebugReport, as was done before in the SDK Pipeline's equivalent runAsStage step.

Add DebugReport facility

---

src/com/sap/piper/DebugReport.groovy
src/com/sap/piper/EnvironmentUtils.groovy
test/groovy/com/sap/piper/EnvironmentUtilsTest.groovy

This should have been added along with DebugReport. For context:
EnvironmentUtils used to be a class alongside DebugReport and thus
there was no 'import' directive. Working with Jenkins DSL stuff
has numbed my ability to pay attention to the IDE indicating errors.

Added EnvironmentUtils needed by DebugReport (#1126)

---

.github/workflows/verify-go.yml
DEVELOPMENT.md
cmd/checkmarxExecuteScan.go
cmd/checkmarxExecuteScan_generated.go
cmd/detectExecuteScan.go
cmd/detectExecuteScan_generated.go
cmd/githubCreatePullRequest.go
cmd/githubCreatePullRequest_generated.go
cmd/githubPublishRelease.go
cmd/githubPublishRelease_generated.go
cmd/karmaExecuteTests.go
cmd/karmaExecuteTests_generated.go
cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_generated.go
cmd/version.go
cmd/version_generated.go
cmd/version_test.go
cmd/xsDeploy.go
cmd/xsDeploy_generated.go
go.mod
go.sum
pkg/generator/helper/helper.go
pkg/generator/helper/helper_test.go
pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden

Update step generation:
* allow setting custom telemetry data
* use Cobra's `Run` function instead of `RunE` since steps do not return errors but rather exit with exit code 1 in case of errors (through `log.Entry().Fatalf(...)` and adapt steps accordingly
* streamline handling of stepConfig using proper names  to align with initial creation of step framework and past `groovy` handling

Streamline step generation

---

test/groovy/PiperStageWrapperTest.groovy
test/resources/stages/test_crashing_extension.groovy
vars/piperStageWrapper.groovy

The code of extensions was not executed within the try-catch-block of `handlePipelineStepErrors`. The main benefit of this change is better logging and re-using the 'unstable' feature also for extended/overwritten steps.

Executing extensions in handlePipelineStepErrors

---

resources/default_pipeline_environment.yml
vars/hadolintExecute.groovy

**changes:**
- stash **all** `Dockerfile`s
- Allow modification of parameter `reportName` on step and parameter level to avoid collisions on report generation in case the step is execute several times.
- ~[ ] Tests~

feat(hadolint): enable correct handling of multiple scan results

---

resources/debug_report.txt
resources/default_pipeline_environment.yml
src/com/sap/piper/DebugReport.groovy
test/groovy/DebugReportArchiveTest.groovy
test/groovy/com/sap/piper/DebugReportTest.groovy
vars/debugReportArchive.groovy

Offer archiving the debug_report.txt as a step. You would use this in the post stage. I have tested running a pipeline which uses this step and also handles conversion of the old location of the configuration key in the SDK pipeline.

Implement archiving the debug report as step

---

test/groovy/util/JenkinsWriteFileRule.groovy
vars/debugReportArchive.groovy

I've changed the return type of DebugReport.generateReport() from
String to Map in order to get the generated file name as part of the
return value instead of getting it from a field of DebugReport. The
UnitTest checks whether writeFile() creates the debug_report file
successfully and whether it has the expected contents. The effect
of passing the Map instead of map.contents to writeFile() should
have been an unnecessary wrapping via Map.toString() as in the test,
but in the execution context of Jenkins, this throws an
IllegalArgumentException: Could not instantiate {... and then the
results of map.toString(). This could also be a problem with how
JenkinsWriteFileRule simulates the writeFile step.

writeFile() cannot be passed a Map

---

test/groovy/MailSendNotificationTest.groovy
vars/mailSendNotification.groovy

Hi,
we’re using an auto merge bot (github app) to merge our pull requests automatically. Unfortunately, it looks like we cannot easily configure an email address for our bot and piper is not able to send emails in case the bot’s internal github email address is part of the committer list:
[mailSendNotification] last 18 commits revealed following responsibles user1@domain.com user2@domain.com 56094+cos-probot-auto-merge[bot]@users.noreply.github.domain.co
[Pipeline] emailext
Failed to create e-mail address for 56094+cos-probot-auto-merge[bot]@users.noreply.github.domain.com
An attempt to send an e-mail to empty list of recipients, ignored.
To circumvent the problem for us and potential other github app consumers I’m creating this PR which avoids that Piper sends mails to users if the email …

Ignore email addresses containing string "noreply"

---

resources/metadata/githubrelease.yaml
test/groovy/GithubPublishReleaseTest.groovy
vars/githubPublishRelease.groovy

The PR removes an unnecessary reference to a `resource`.
This is not required since the reference in the `parameters` section is sufficient.
In addition it is better to provide credentials via environment variable.
With the changes this step can now serve also as an example how to do things like:
* passing credentials
* using `commonPipelineEnvironment` as input resource

Streamline implementation githubPublishRelease

---

pkg/http/downloader.go

Is there any reason for using a POST request for downloading some content. To my understanding POST is used for transmitting parameters where GET is used for simply retrieving something.

switch downloader from POST to GET

---

src/com/sap/piper/Utils.groovy

Manual testing of using the mvn evaluate plugin has revealed the following behavior for properties that do not exist:
```
▶ mvn --file pom.xml -Dexpression=project.url -DforceStdout -q org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate
https://sap.github.io/jenkins-library/%
```
If I remove the `url` property, mvn will still have a 0 exit code and a non-empty output to stdout:
```
▶ mvn --file pom.xml -Dexpression=project.url -DforceStdout -q org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate
null object or invalid expression%
```
This change makes sure that Utils.evaluateFromMavenPom() returns an empty string when there was an error in the expression or the property cannot be resolved, instead of returning the error message itself as if it were the result.
It would be great …

Utils.evaluateFromMavenPom(): Handle errors

---

cmd/abapEnvironmentPullGitRepo_test.go
cmd/cloudFoundryDeleteService_test.go
cmd/detectExecuteScan.go
cmd/detectExecuteScan_test.go
cmd/interfaces.go
cmd/karmaExecuteTests.go
cmd/karmaExecuteTests_test.go
cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_test.go
cmd/mtaBuild.go
cmd/mtaBuild_test.go
cmd/piper_test.go
cmd/xsDeploy_test.go
integration/integration_api_test.go
integration/integration_cli_test.go
pkg/command/command.go
pkg/config/stepmeta_test.go
pkg/mock/runner.go

As we will add more common functionality to `pkg/` (in my case mavenExecute, see #1204 ) we have to move the mock runners to pkg.
With that we can avoid cyclic imports, which are forbidden in go.

Move mock capabilities to pkg/mock/runner and adapt all tests

---

integration/integration_test.go

This change allows a development workflow where you don't need to set the `PIPER_INTEGRATION_EXECUTABLE` variable if your executable is available in the CWD. This should make it non-required to set the variable for most cases of local development.

Use piper exe in CWD for integration tests if available

---

.github/workflows/verify-go.yml
Dockerfile
pkg/mock/runner.go

This change ensures that shared testing capabilities e.g. in `pkg/mock/runner` won't end up in the production code using go build tags (see [here](https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags) for more information.).
To verify that this PR works you can add  `// +build !release` to e.g. `cmd/interfaces.go` and then build the binary with `go build -tags release`. The result is that the code can't be compiled.

Add tag release when building go binary

---

pkg/maven/maven.go
pkg/maven/maven_test.go

* adds a helper method to get the exclude parameters for test modules in case they exist
* needed for spotBugs, pmd, and many other maven calls which should only operate on production modules

Add GetTestModulesExcludes to pkg/maven

---

consumer-test/TestRunnerThread.groovy
src/com/sap/piper/PiperGoUtils.groovy

This change makes sure we're using the piper version under test for the consumer tests.

Build piper binary in Consumer Tests

---

pkg/nexus/nexus.go
pkg/nexus/nexus_test.go

The nexus package implements uploading artifacts to a Nexus repository manager version 2 or 3 via HTTP. It also generates the MD5 and SHA1 hash files for the uploaded artifacts in the Nexus repository.
Extracted from https://github.com/SAP/jenkins-library/pull/1201

Implementation of Nexus upload as Go package

---

pkg/http/http.go

This might provide useful context to the user.
For example when you try to upload a SNAPSHOT jar to a maven-release
repo in nexus, this will print an error like
`returned with response 400 Repository version policy: RELEASE does not allow version: 1.0-SNAPSHOT`
instead of
`returned with HTTP Code 400`

Improve message in error case in http client

---

vars/karmaExecuteTests.groovy
vars/uiVeri5ExecuteTests.groovy

This PR follows up on #1171 and exposes the newly introduced parameter `seleniumHubCredentialsId` to higher-level functions such as `karmaExecuteTests` and `uiVeri5ExecuteTests`.

Expose seleniumHubCredentialsId to higher-level Jenkins steps

---

cmd/mtaBuild.go

**changes:**
- don't add `os.Environ()` to command environment (as it is already added [here](https://github.com/SAP/jenkins-library/blob/master/pkg/command/command.go#L107-L109))
related to #1223

fix(mta): add os.Environ() only once to command

---

pkg/maven/maven.go
pkg/maven/maven_test.go

Replicates the functionality from the Groovy [`Utils.evaluateFromMavenPom()`](https://github.com/SAP/jenkins-library/blob/master/src/com/sap/piper/Utils.groovy#L157) class in Go.

Add Evaluate() method to maven package

---

pkg/maven/maven.go
pkg/maven/maven_test.go

Returns error instead of exiting via logging framework (should not do this in pkg code).
Fixes wrongly downloading the global maven settings file from the project settings file's option.
Extends unit-tests to expose such errors.

Fix copy-paste-bug for downloading settings

---

test/groovy/PiperStageWrapperTest.groovy
vars/piperStageWrapper.groovy

closes #1286 which was introduced with #1146

Fix issue with pipeline resilience

---

cmd/abapEnvironmentPullGitRepo_generated.go
cmd/checkmarxExecuteScan_generated.go
cmd/cloudFoundryDeleteService_generated.go
cmd/detectExecuteScan_generated.go
cmd/getConfig.go
cmd/githubCreatePullRequest_generated.go
cmd/githubPublishRelease_generated.go
cmd/karmaExecuteTests_generated.go
cmd/kubernetesDeploy_generated.go
cmd/mavenBuild_generated.go
cmd/mavenExecuteStaticCodeChecks_generated.go
cmd/mavenExecute_generated.go
cmd/mtaBuild_generated.go
cmd/piper.go
cmd/protecodeExecuteScan_generated.go
cmd/version_generated.go
cmd/xsDeploy_generated.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/stepmeta.go
pkg/generator/helper/helper.go
pkg/generator/helper/helper_test.go
pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
resources/metadata/mavenBuild.yaml
resources/metadata/mavenStaticCodeChecks.yaml

Introduction of configuration aliases for steps.
This will ease following scenarios for example:
* config migration due to step name changes
* re-use of more general config, e.g. `mavenExecute` in `mavenBuild`
Configuration in step metadata is done as follows:
```
metadata:
name: mavenBuild
aliases:
- name: mavenExecute
deprecated: false
- name: deprecatedMavenExecute
deprecated: true
```
This configuration will ensure that relevant step configuration parameters of `mavenExecute` will be used for `mavenBuild` unless they are already defined for `mavenBuild`.
It is possible to define multiple aliases, like `deprecatedMavenExecute` in this example.
They are considered in order. 
That means step configuration parameters of `deprecatedMavenExecute` are only considered in case the …

Golang step metadata: Config aliases for steps

---

resources/com.sap.piper/templates/mvn_download_cache_proxy_settings.xml
src/com/sap/piper/DownloadCacheUtils.groovy
test/groovy/DownloadCacheUtilsTest.groovy

Especially for the use case with cx-server in a docker environment where a nexus container acts as a download cache dockerOptions and GlobalSettings are needed to configure mavenExecute to use the download cache.
This utility class implements the handling of dockerOptions and creates a maven global config on the fly.
The idea is to use this helper class every time we call a go step which executes maven.

Add DownloadCacheUtils for handling download cache docker container

---

cmd/sonarExecuteScan.go

The command line argument building for calling keytool was wrong.
* Parameters which are separated by a space on the command line are passed as separate argv entries to the tool by the shell. Translating this to `execRunner.RunExecutable()` means they need to be separate entries in the options array.
* Surrounding paths by quotes in the shell has the effect that the path can have special characters. They can also have spaces, which means the shell generates one argv entry for the path. For building the options array for `execRunner.RunExecutable()`, this is wrong, since we are already one step farther, we build the argv-array directly. Adding quotes means it will end up in the executed tool *with* the quotes.

Fix CLI exec call building for keytool

---

pkg/http/http_test.go

Fix flaky test expectations of pkg/http timeout test.
The exact error message has changed in go 1.14.

Future proof the http-timeout test for go 1.14

---

test/groovy/util/BasePiperTest.groovy

Before every test used the same application context, including the same nullScript.

Fix test by resetting application context after each test

---

cmd/sonarExecuteScan.go
cmd/sonarExecuteScan_test.go

**changes:**
- use `SONAR_TOKEN` instead of `SONAR_AUTH_TOKEN` to provide API token
The Jenkins Sonar plugin provides `SONAR_AUTH_TOKEN` which is at least not considered by the Sonar CLI scanner.
The `SONAR_TOKEN` usage is also not explicitly documented though, only as part of [GitLab integration](https://docs.sonarqube.org/latest/analysis/gitlab-cicd/).

fix(sonar): use SONAR_TOKEN in Sonar go

---

cmd/artifactPrepareVersion.go
cmd/artifactPrepareVersion_generated.go
cmd/artifactPrepareVersion_test.go
resources/metadata/versioning.yaml

add versioning option `cloud_noTag`.
This allows teams to use automatic versioning without creating a tag on the SCM which contains the change.
This option needs to be handled with care since teams can create a build artifact with no real representation in the SCM.
Thus the `cloud_noTag` option is weak when it comes to providing a traceable build result
superseeds #1366

artifactPrepareVersion: new versioning option

---

test/groovy/com/sap/piper/integration/TransportManagementServiceTest.groovy

This PR provides an extension for TMS-related junit tests, where it is explicitly asserted that there is no token present in the logs.

TMS: explicitly check in tests that there is no token in the logs

---

.github/workflows/integration-tests.yaml

With this pull request collaborators can trigger consumer as well as go integration tests with commenting `/it` on the pull request.
Consumer tests need to be updated before, but this will be done in a different pull request.

Trigger integration test with command

---

.github/workflows/integration-tests.yaml

It turned out that we are considered as Members (Author is a member of the organization that owns the repository.)
https://developer.github.com/v4/enum/commentauthorassociation/
With this PR everyone in the SAP organization would be allowed to trigger pull requests. 
Is that fine with everyone?

Allow MEMBERs to trigger integration tests

---

pkg/config/config.go
pkg/config/config_test.go

Improves the error message when a config couldn't be parsed.

improve error message when parsing config

---

cmd/nexusUpload.go
cmd/nexusUpload_generated.go
cmd/nexusUpload_test.go
integration/integration_nexus_upload_test.go
integration/testdata/TestNexusIntegration/npm/package.json
pkg/nexus/nexus.go
pkg/nexus/nexus_test.go
resources/metadata/nexusUpload.yaml

Upload npm to nexus if a package.json exists in the project root.
Minor breaking change: The parameter "repository" was renamed to "mavenRepository" so it is consistent with the newly introduced "npmRepository".

Extend nexusUpload to also handle npm

---

documentation/docs/pipelines/cloud-sdk/build-tools.md

This change adds documentation for the new behavior and capabilities of
the lint stage of the Cloud SDK Pipeline.

Add documentation for the lint stage of Cloud SDK Pipeline

---

.github/workflows/update-go-dependencies.yaml
.pipeline/config.yml

New github action to trigger automatic go dependency updates on schedule.
Will create a new PR with updates on monday after the weekly release was triggered, so we can merge it to master and get a freshly updated master branch for the new development cycle.

Automate go dependency updates

---

cmd/getConfig.go

respect `.pipeline/config.yml` and `.pipeline/config.yaml` as in [`prepareConfig`](https://github.com/SAP/jenkins-library/blob/master/cmd/piper.go#L115)

fix: read config.yaml in getConfig command

---

resources/default_pipeline_environment.yml

Especially for go steps we are using `curl` to download the go binary which is not included in the default jenkins agent docker image. See also https://github.com/SAP/jenkins-library/issues/1409
This PR configures our ppiper kubernetes agent docker image as default which contains curl.
Alternative approach: Use wget instead of curl everywhere.

Configure default jenkins agent for kubernetes

---

.github/workflows/update-go-dependencies.yaml

This should fix the issue that the created PRs don't trigger tests.

Use specific token for automated go dependency update PR

---

.github/workflows/documentation.yaml
.github/workflows/verify-groovy.yml

**changes:**
- use cache action to cache `~/.m2` directory during Groovy test execution

chore: cache .m2 directory during groovy tests

---

pkg/piperenv/environment.go
pkg/piperutils/stepResults.go
pkg/piperutils/stepResults_test.go

**changes:**
- add general *read* permissions on created files
- handle empty (`nil`) result sets
related to #1390
[compare without whitespaces](https://github.com/SAP/jenkins-library/pull/1425/files?diff=split&w=1)

fix: improve stepResults handling

---

cmd/artifactPrepareVersion_generated.go
cmd/checkmarxExecuteScan_generated.go
cmd/mtaBuild_generated.go
cmd/protecodeExecuteScan_generated.go
cmd/xsDeploy_generated.go
pkg/generator/helper/resources.go
pkg/generator/helper/resources_test.go
pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden

Do not exit with `os.Exit(1)` but use `log.Entry().Fatal()` instead

Step generator: correct error handling

---

cmd/sonarExecuteScan.go

~~In some cases~~ When `legacyPRHandling` is used `sonar-scanner-cli` does not to write a `.scannerwork/report-task.txt` file, which lead to a *file not found* issue.
**changes:**
- prevents the step from failing if `.scannerwork/report-task.txt` is missing / could not be read

fix(sonar): do not fail on missing task report file

---

.github/workflows/upload-go-master.yml

Telemetry reporting is failing (ignored) due to an incorrect source url.
**changes:**
- set the source url for telemetry reporting as `https://github.com/SAP/jenkins-library.git`

fix(telemetry): correct source URL for web reporting

---

vars/artifactPrepareVersion.groovy

setting SSH environment variable breaks step on JaaS.
In addition it made the step hardly dependent on Jenkins.
In case there is really something missing we need a proper solution here.

Emergency fix: revert part of #1455

---

resources/metadata/versioning.yaml

container definition in #1455 broke existing behavior:
- maven execution by default without Docker to improve performance in a Kubernetes cluster
- `git repository required - none available` due to stashing in Kubernetes which does not include git context so far due to performance reasons
We need a proper solution in case we want to execute the maven versioning inside a Docker container:
- proper stashing in Kubernetes
- conditional Docker image (only for Maven case)
- maven execution in container only in case maven is not found locally since no build logic involved for versioning (only version retrieval and update)

Revert breaking change with #1455

---

cmd/mavenExecute.go
pkg/piperutils/slices.go
pkg/piperutils/slices_test.go

In the current implementation we end up with a command containing `-pl !integration-tests !unit-tests` which is not valid syntax for maven. We need the second `-pl` which is the reason that we must not de-duplicate.

Dont dedup mvn flags

---

vars/nexusUpload.groovy

Fix name of environment variable as nexusUpload parameter is called user instead of username:
https://github.com/SAP/jenkins-library/blob/master/cmd/nexusUpload_generated.go#L103

Fix nexus upload to pass correct environment variable

---

vars/sonarExecuteScan.groovy

fixes #1449
**changes:**
- remove `.sonar-scanner` and `.certificates` folder after scan
[review without whitespace changes](https://github.com/SAP/jenkins-library/pull/1481/files?diff=split&w=1)

fix(sonar): remove .sonar-scanner and .certificates folder after scan

---

cmd/cloudFoundryCreateServiceKey.go
cmd/cloudFoundryCreateServiceKey_generated.go
cmd/cloudFoundryCreateServiceKey_test.go
documentation/docs/steps/cloudFoundryCreateServiceKey.md
resources/metadata/cloudFoundryCreateServiceKey.yaml

This change will no longer support in-line passing of JSON config as parameter for `cfCreateServiceKeyConfig`. Only passing the path to a JSON config file will be supported at the moment. This is mostly covered in tests and the documentation has been adapted accordingly. Passing the JSON config as in-line parameter will be supported in a later feature release with test coverage.

Removing JSON config for Service Key Creation as in-line parameter

---

vars/protecodeExecuteScan.groovy

With #1426 the username parameter was changed, but the parameter provided by `withCredentials` was missed.

fix(protecode): correct provided user parameter

---

cmd/abapEnvironmentPullGitRepo.go
cmd/artifactPrepareVersion.go
cmd/cloudFoundryCreateServiceKey.go
cmd/cloudFoundryDeleteService.go
cmd/detectExecuteScan.go
cmd/gctsCreateRepository.go
cmd/karmaExecuteTests.go
cmd/kubernetesDeploy.go
cmd/malwareExecuteScan.go
cmd/mavenBuild.go
cmd/mavenExecuteStaticCodeChecks.go
cmd/mtaBuild.go
cmd/nexusUpload.go
cmd/npmExecuteScripts.go
cmd/protecodeExecuteScan.go
cmd/sonarExecuteScan.go
documentation/docs/pipelines/cloud-sdk/introduction.md
pkg/generator/helper/helper.go
pkg/log/log.go
pkg/log/log_test.go
pkg/log/writer.go
pkg/log/writer_test.go
pkg/maven/maven.go

Provides work-around for https://github.com/SAP/jenkins-library/issues/1474
* Implement an io.Writer to be used instead of Entry().Writer() for re-routing a tool's output to the logging framework.
* Replace any occurrence of log.Entry().Writer() with log.Writer().
This avoids the problem of writing chunks larger than 64K that contain no linebreaks. Note that this is not a general solution, as it only solves re-directing tool output to the logging framework. Logrus doesn't provide any facility to override the scanning function. Also it doesn't prevent someone from using log.Entry().Writer(). I am open to other ideas.

Logrus buffer issue

---

cmd/artifactPrepareVersion.go
cmd/artifactPrepareVersion_generated.go
cmd/artifactPrepareVersion_test.go
pkg/versioning/docker.go
pkg/versioning/versioning.go
pkg/versioning/versioning_test.go
resources/metadata/versioning.yaml

it is now possible to use
* a Unix timestamp number (instead of `YYYYMMDDHHMMss`)
* a short commit hash
for the automatically created version.
In addition a dedicated versioning scheme for Docker `docker` has been added instead of "misusing" `maven`

artifactPrepareVersion: additional options

---

cmd/artifactPrepareVersion.go
cmd/artifactPrepareVersion_test.go

replaces #1544 
fixes #1537
> // All automatically stage files that have been modified and deleted, but
// new files you have not told Git about are not affected.
All bool

fix(versioning): commit only modified files

---

cmd/abapEnvironmentRunATCCheck_test.go

Execute the test in a temp folder in order to keep project clean.

Fix: Execute ABAP run ATC check test in temp folder

---

cmd/mtaBuild.go
cmd/mtaBuild_test.go

The mtarName config param is documented such that it shall include the extension. The Groovy implementation also expected the name to include the extension. See here: https://github.com/SAP/jenkins-library/blob/v1.34.0/vars/mtaBuild.groovy#L147

Fix mtarName config param handling

---

documentation/mkdocs.yml

Add missing registration of fortify step documentation page.
The page itself was added together with the fortify step.

Add fortify docs

---

pkg/log/log.go

Cosmetic change to make the "warning" log level fit into the fixed width log format.

Use short warn log level

---

.github/workflows/integration-tests-pr.yaml
.github/workflows/integration-tests.yaml
integration/run-tests.sh

#1472 Changes
Default is 10m, see https://golang.org/cmd/go/#hdr-Testing_flags
This fails often for me in practice, like so: https://github.com/SAP/jenkins-library/runs/716803728?check_suite_focus=true

Provide a timeout of 20m for the go Integration Tests

---

src/com/sap/piper/JenkinsUtils.groovy

archiveArtifacts is documented to work from the current directory. But for some reason, it doesn't support glob patterns that start with `./`. It even logs an error message to the effect of "`./path/*.ext` does not match anything, did you mean `path/*.ext`?".

Strip "./" from paths to artifacts

---

.github/workflows/upload-go-master.yml

This produces a much smaller binary for faster downloads.
See https://golang.org/cmd/link/ for docs on -s and -w flag.
A quick test on my mac produced this differences in file size. I think it is sensible to build the release binary without debug info, but I'm not sure if I overlook some negative consequence of doing this.
```
-rwxr-xr-x   1 x x  41M 2020-05-31 12:36 piper-normal*
-rwxr-xr-x   1 x x  34M 2020-05-31 12:37 piper-prod*
```

Build go binary without debug symbols

---

cmd/fortifyExecuteScan.go
cmd/fortifyExecuteScan_generated.go
cmd/fortifyExecuteScan_test.go
resources/metadata/fortify.yaml

Es described in the Fortify documentation:
https://www.microfocus.com/documentation/fortify-static-code-analyzer-and-tools/1910/SCA_Guide_19.1.0.pdf
`- exclude: Removes files from the list of files to translate. Separate multiple file
paths with semicolons(Windows) or a colons(non-Windowssystems).`
* Also includes a cleanup of the meta-data YAML with regards to indentation and string quoting. 
* Removal of the mvnCustomArgs param which duplicates m2Path and related options.
* Removal of buildDescriptorExcludeList which was not implemented anyway.
* The already "deprecated" Python includes and excludes arguments have been merged with the Maven versions.
* Parameters which represent lists are now also typed as "[]string".
* Includes a fix where the python includes were not tokenized, …

Needed CLI separator for Fortify tools depends on platform

---

cmd/malwareExecuteScan.go
cmd/malwareExecuteScan_generated.go
cmd/malwareExecuteScan_test.go
resources/metadata/malwareExecuteScan.yaml

the default (10s) is not sufficient for scanning bigger files.

Timeout for malwarescan

---

src/com/sap/piper/variablesubstitution/YamlUtils.groovy
test/groovy/CfManifestSubstituteVariablesTest.groovy
test/groovy/com/sap/piper/variablesubstitution/YamlUtilsTest.groovy
test/resources/variableSubstitution/datatypes_manifest-variables.yml
test/resources/variableSubstitution/datatypes_manifest.yml

Fixes: yaml substitution does not work for booleans with value false. See #1579.

Fix: yaml util handling for boolean with value false

---

vars/buildExecute.groovy
vars/commonPipelineEnvironment.groovy

This is required by Cloud SDK Pipeline. Instead of configuring it the pipeline will infer the build tool and store it in the commonPipelineEnvironment.

Store build tool in commonPipelineEnvironment

---

pkg/http/http.go
pkg/http/http_test.go

Increase the default transport timeout to 3 minutes. The thinking is this: If a Pipeline will fail due to a network stall, it isn't so bad to have it stall for longer than necessary. On the other hand, to have a pipeline fail quickly because of a 10s network stall, while everything would have been fine just with a longer timeout, is very frustrating and may overall consume much more time than is saved by failing more quickly in the first situation.

Increase default transport timeout to 3 mins

---

cmd/nexusUpload.go
cmd/nexusUpload_test.go
pkg/maven/maven.go
pkg/maven/maven_test.go
pkg/versioning/maven.go
pkg/versioning/maven_test.go
pkg/versioning/versioning.go
pkg/versioning/versioning_test.go

Global maven options (m2Path, projectSettingsFile, globalSettingsFile), which most steps using maven already share via aliasing from the general config, need to be passed also to Evaluate().
This does actually fix problems in the artifactPrepareVersion step, depending on the project setup.

Refactor maven.Evaluate() to take options

---

vars/dockerExecuteOnKubernetes.groovy

I was reading the doc and decided it was a bit too much to have to select a link and paste in another tab, so I wanted to fix it.

doc(kubernetes): Make plugin link clickable

---

pkg/config/config.go
pkg/config/config_test.go

Bug: In go the stage config in customDefaults are ignored. In groovy the are taken into account.
This PR fixes this behaviour.

Consider stage config from custom defaults

---

documentation/docs/extensibility.md

Adapt mavenExecute example call to new api

---

pkg/piperutils/fileUtils_test.go

On my local environment I get 
```
ok  	github.com/SAP/jenkins-library/pkg/piperenv	2.858s
[{"name":"","target":"testFile1.json","mandatory":true,"scope":""},{"name":"","target":"testFile2.json","mandatory":false,"scope":""}]
[{"name":"Weblink","target":"https://1234568.com/test","mandatory":false,"scope":""}]
--- FAIL: TestCopy (0.00s)
--- FAIL: TestCopy/copying_file_succeeds (0.00s)
fileUtils_test.go:41: 
Error Trace:	fileUtils_test.go:41
Error:      	Received unexpected error:
Source file 'testFile' does not exist
Test:       	TestCopy/copying_file_succeeds
Messages:   	Didn't expert error but got one
fileUtils_test.go:42: 
Error Trace:	fileUtils_test.go:42
Error:      	Not equal: 
expected: 3
actual  : 0
Test:       	TestCopy/copying_file_succeeds
Messages:   	Expected true but got …
```

No parallel test exec for file tests

---

pkg/cloudfoundry/ManifestUtils.go
pkg/cloudfoundry/ManifestUtils_test.go

makes it more easy to test other code with the interface
since we can inject a mock.
As a small side story improved function name, basically unrelated. `GetName` on the Manifest is now `GetFileName` in order to avoid misunderstandings with getting an application name.

Introduce interface for manifest

---

vars/npmExecuteScripts.groovy

Add sysadmin capabilities to npmExecuteScripts is it is only then possible to start chrome with sandbox mode.

Add sysadmin capabilities to npmExecuteScripts

---

src/com/sap/piper/DefaultValueCache.groovy

This change fixes the error handling in addDefaultsFromFiles(), i.e.,
using the correct path when calling the readFile step to return the
content of the unsuccessfully parsed yaml file.

Fix error Handling in DefaultValueCache

---

cmd/kubernetesDeploy.go
pkg/command/command.go
pkg/command/command_test.go

* add known error category mapping for step `kubernetesDeploy`
* enhance error parsing to support patterns
* fixes #1732

kubernetesDeploy: categorize known errors & fix #1732

---

pkg/command/command.go
pkg/command/command_test.go
pkg/mock/runner.go
vars/cloudFoundryDeploy.groovy

enhancing the command/shell execution with capability to retrieve the exit code.
This will be helpful to derive error categories in case
an executable provides context-specific error codes.

Allow retrieving exit code from command execution

---

pkg/cloudfoundry/Authentication.go
pkg/cloudfoundry/CloudFoundry_test.go

`cf` command line tool provides additional options for `api` subcommand (`--skip-ssl-validation`)  and `login` subcommand (`--skip-ssl-validation`, `--origin`). We need to be able to pass these additional options.
Nota bene: `--skip-ssl-validation` should not be used for productive scenarios. Nevertheless it is useful for rapid prototyping and troubleshooting.

cf login additional opts

---

test/groovy/NeoDeployTest.groovy
vars/neoDeploy.groovy

Previously, all logs were stored in the same folder and in case of an
error all logs in that folder would be returned to the user. Thus, it
is possible that unrelated logs, i.e., from different deployments (e.g. 
parallel deployments) are returned to the user.

Separate log folders for neo deployments

---

resources/default_pipeline_environment.yml
test/groovy/MulticloudDeployTest.groovy
test/groovy/NeoDeployTest.groovy
vars/multicloudDeploy.groovy
vars/neoDeploy.groovy

Before the neoDeploy step already had a default / fallback value for source for mta but not for maven /war. 
With this change the neoDeploy step also tries for maven to automatically detect the deployable artifact.

Default source for maven deployments to neo

---

cmd/npmExecuteLint.go

The Warnf in line 66 produces wrapping errors when using golang version 1.14. 
With the use of the verb %v instead of %w the error is fixed.

npmExecuteLint.go - Replace %w with %v for Warnf 

---

pkg/config/config.go
pkg/config/config_test.go

Before if there is an alias p0/oldParam but p0 was configured as non map type, e.g. p0: true the configure resolution failed with a panic.
`panic: interface conversion: interface {} is bool, not map[string]interface {}`

Make aliasing more resilient

---

cmd/abapEnvironmentRunATCCheck.go
pkg/cloudfoundry/Authentication.go
pkg/cloudfoundry/CloudFoundry_test.go
pkg/cloudfoundry/Services.go

We have to be able to provide the cloudfoundry instance from outside to the cloudfoundry package in order to eg. perform a login. Reason: There are some environment variables which controls the behaviour of the cf cli (e.g. `CF_TRACE`, `CF_HOME`).
When we work upon a shared instance for all our tasks we have these issues:
1.) when the instance is global we have to ensure we perform a cleanup each time we are done with a task (e.g. resetting environment variables, streams (`stdout`, `stderr`)
2.) we cannot use that global instance in a parallel way. Currently we don't use that instance in a parallel mode, but in principle   concurrency is well supported in go and we should be prepared for this.

No "global" exec runner instance inside cloudfoundry pkg

---

src/com/sap/piper/integration/CloudFoundry.groovy

The `newmanExecute` relies on this part of the code to identify applications (for the `cfAppsWithSecrets` parameter).
However, the `cloudFoundryDeploy` step names them differently then expected:
- Deployed by `cloudFoundryDeploy`: `<appname>-green` and `<appname>-blue`
- Searched by this snippet: `<appname>_green` and `<appname>_blue`
So this change adds the actually deployed names in a backwards compatible way (in case someone relies on the `_green` suffix).

Improve newman blue-green app identification

---

cmd/kanikoExecute_test.go
cmd/mtaBuild_test.go
cmd/xsDeploy_test.go
pkg/maven/settings_test.go
pkg/mock/fileUtils.go
pkg/mock/fileUtils_test.go
pkg/piperutils/FileUtils.go

for
- `cmd/kanikoExecute_test.go`
- `cmd/xsDeploy_test.go`
-  `cmd/mtaBuild_test.go`
- `pkg/maven/settings_test.go`
we should switch to THE file mock. But I would like to suggest to do this in an dedicated PR.

Introduce chmod in file utils

---

DEVELOPMENT.md
cmd/piper.go
integration/contracts_test.go
main.go
pkg/generator/helper/helper.go
pkg/generator/helper/helper_test.go
pkg/generator/step-metadata.go

allows now to use native golang means for code generation:
use `go generate` in folder `cmd/` in order to generate the step framework based on the step.yaml files

Step generation: allow usage of go generate

---

vars/commonPipelineEnvironment.groovy
vars/piperStageWrapper.groovy

For the cloud sdk pipeline we need more flexibility to define the locks. 
E.g. env.JOB_NAME does not work as it also contains the branch name. However, we have stages which should be locked across branches, e.g. when running end to end tests from multiple non productive branches.
Also having an ordinal does not always work, e.g. when a stage is run in parallel.

Make stage locking more flexible

---

integration/docker_integration_test_executor.go
integration/integration_mta_build_test.go
integration/piper-command-wrapper.sh

This change addresses some issues of the testcontainer based testing approach (much repeated code, API not on the right abstraction level). It introduces new methods that make use of the docker cli, and rewrites the mta tests using this method.

Rewrite mta IT using docker cli

---

integration/docker_integration_test_executor.go

- Extracted some methods to structure the code better
- Explicitly run the binary with a trivial command first to avoid simple failure reasons (like having a non-linux binary)

Refactoring, sanity check for unit-under-test binary

---

.github/workflows/integration-tests.yaml

Allow triggering IT via `workflow_dispatch` which adds a UI element that allows to chose a branch on which the IT should be run.
This has advantages over both ways we already have:
- no need to push an `it/foo` branch
- no emails/notifications for people typing `/it` comments (and also I still can't use this method for some unknown reason)
cf https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow\#manually-running-a-workflow
I tried this out in this repo https://github.com/fwilhe/test-ghact-expression-syntax, so I'm somewhat confident that it works as expected. Choosing the branch name/commit id should exactly do what is expected, given you chose the right branch to run the test on in the dropdown.

Allow trigger IT via GitHub UI

---

cmd/piper.go
cmd/piper_test.go

Reverts SAP/jenkins-library#1837
... until more validation is performed. At the moment, it looks like parameters which end up as 'nil' throw unexpected type errors.
related to #1838

Revert "Bugfix: Convert int/float parameters"

---

cmd/sonarExecuteScan.go
cmd/sonarExecuteScan_generated.go
cmd/sonarExecuteScan_test.go
resources/metadata/sonar.yaml

This PR corrects the type of `customTlsCertificateLinks` to be a List of URLs.
fixes #1838

fix(sonar): correct type for custom TLS certificates

---

test/groovy/MavenExecuteIntegrationTest.groovy
vars/mavenExecuteIntegration.groovy

The collection of test results is not supposed to happen within the step/wrapper.

mavenExecuteIntegration: Remove test collection

---

pkg/cloudfoundry/Authentication.go
pkg/cloudfoundry/CloudFoundry_test.go

we don't have any cf api calls anymore in the context of cf login.

CfAPIOpts: remove leftovers

---

cmd/checkmarxExecuteScan_generated.go
resources/metadata/checkmarx.yaml

Adds an alias "groupId" to the parameter "teamId", and an alias "checkMarxProjectName" to "projectName".
Allows the Cloud SDK Pipeline to switch to the step without a breaking change.

checkmarxExecuteScan: Add two (deprecated) aliases

---

cmd/fortifyExecuteScan.go

The maven options could be important to be able to extract the project coordinates. See also https://github.com/SAP/jenkins-library/blob/master/cmd/artifactPrepareVersion.go#L73 We have an open issue where fortifyExecuteScan fails due to maven being unable to download dependencies.

fortifyExecuteScan: Pass on maven options to versioning

---

cmd/protecodeExecuteScan_generated.go
resources/metadata/protecode.yaml

This PR removes the `addSideBarLink` as it is not used anywhere. Also the publication of reports should be handled by StepResults completely in the future (#1891).

refactor(protecode): remove unused parameter

---

integration/integration_mta_build_test.go

Use `devxci/mbtci:latest` image instead of openjdk image for mta IT which did not work with the old testing approach.

Simplify IT

---

documentation/docs/steps/writeTemporaryCredentials.md
documentation/mkdocs.yml
test/groovy/WriteTemporaryCredentialsTest.groovy
vars/writeTemporaryCredentials.groovy

This change adds the groovy step writeTemporaryCredentials, in order to
avoid resolving configuration parameters within the piperPipelineStageIntegration
in the future.
For the integration tests functionality provided by the SAP Cloud SDK
Pipeline it needs be possible to configure a credential id pointing to
Jenkins credentials, which are then temporarily written to a file to be
available during the execution of the integration tests.
With the previous implementation solely in the TemporaryCredentialsUtils
class, it would be required to resolve the credentialId from the
configuratuion within the piperPipelineStageIntegration, once we fully
migrate the Cloud SDK integration tests stage.

Add groovy wrapper for TemporaryCredentialsUtils

---

resources/metadata/protecode.yaml
vars/protecodeExecuteScan.groovy

We have different approaches of authenticating against a Docker registry. 
- `kubernetesDeploy` uses username/password via the `dockerCredentialsId` parameter
- `kenikoExecute` uses a `config.json` file via the `dockerConfigJsonCredentialsId ` parameter
- `protecodeExecuteScan` uses a `config.json` file via the `dockerCredentialsId` parameter
This PR aligns the parameter name for a `config.json` file in the protecode step with the [`kaniko`](https://github.com/SAP/jenkins-library/blob/master/resources/metadata/kaniko.yaml#L8) step.
mind #1914

refactor(protecode): align Docker config.json parameter name

---

cmd/protecodeExecuteScan.go
cmd/protecodeExecuteScan_generated.go
cmd/protecodeExecuteScan_test.go
documentation/docs/steps/protecodeExecuteScan.md
resources/metadata/protecode.yaml
vars/protecodeExecuteScan.groovy

This PR adds a new parameter `dockerConfigJSON` to reflect the usage of `dockerConfigJsonCredentialsId` in the docs.
mind #1915

refactor(protecode): add explicit parameter for Docker config.json file

---

test/groovy/PiperStageWrapperTest.groovy
vars/piperPipelineStageAcceptance.groovy
vars/piperPipelineStageBuild.groovy
vars/piperPipelineStageIntegration.groovy
vars/piperPipelineStageRelease.groovy
vars/piperStageWrapper.groovy

Make sure to avoid problems with conflicting sources of truth about the current stage name by setting env.STAGE_NAME to the name from the parameters in piperStageWrapper.
Reverts #1796, which did not have any effect without #1920. With this PR, it is no longer needed.

Align stage name

---

cmd/getConfig.go
cmd/piper.go
cmd/piper_test.go

stageName from parametersJSON was ignored up until now and there was a TODO in the code. The precedence from the TODO is not clear to me. It said "first env.STAGE_NAME, second: parametersJSON, third: flag". So maybe I implemented it wrongly, but it would be easy to change. Right now, STAGE_NAME is always in the ENV when piper is called from Jenkins, but to mimic the behavior of being able to pass `stageName` in the parameters and override the ENV value, this is what happens in go as well now.
The reason why `stageName` needs to be evaluated before other step parameters is that it affects config evaluation. So I've added a function which is called first in `PrepareConfig()`.

piper: Use stageName from parametersJSON, log value and source

---

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
resources/default_pipeline_environment.yml
src/com/sap/piper/TemporaryCredentialsUtils.groovy
test/groovy/WriteTemporaryCredentialsTest.groovy
test/groovy/com/sap/piper/TemporaryCredentialsUtilsTest.groovy
vars/piperPipelineStageIntegration.groovy
vars/writeTemporaryCredentials.groovy

This change add the support for running integration tests using the
recently introduced step mavenExecuteIntegration in
piperPipelineStageIntegration. In addition, capabilities to provide
temporary credentials to these tests is added using the
writeTemporaryCredentials step.

Add mavenExecuteIntegration and writeTemporaryCredentials to piperPipelineStageIntegration

---

cmd/cloudFoundryCreateService_generated.go
resources/metadata/cloudFoundryCreateService.yaml

Projects used to be able to configure cloudFoundry in the general section of .pipeline/config.yml. This is a follow up to https://github.com/SAP/jenkins-library/pull/1649, which introduced a breaking change.

cloudFoundryCreateService: Fix parameter scopes

---

pkg/versioning/versioning.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9830a6]
goroutine 1 [running]:
github.com/SAP/jenkins-library/pkg/versioning.searchDescriptor(0xc00067c060, 0x2, 0x2, 0x0, 0x0, 0xc0006549c0, 0xc0006413a0, 0x982ce0)
/home/runner/work/jenkins-library/jenkins-library/pkg/versioning/versioning.go:156 +0x76
github.com/SAP/jenkins-library/pkg/versioning.(*GoMod).GetVersion(0xc0006549c0, 0x6, 0x18089f1, 0x6, 0xc000664a80)
/home/runner/work/jenkins-library/jenkins-library/pkg/versioning/gomodfile.go:52 +0x18a
...
```

versioning: fix panic when using go.mod

---

cmd/cloudFoundryDeploy.go
cmd/cloudFoundryDeploy_generated.go
cmd/cloudFoundryDeploy_test.go
resources/metadata/cloudFoundryDeploy.yaml
test/groovy/CloudFoundryDeployTest.groovy
vars/cloudFoundryDeploy.groovy
vars/commonPipelineEnvironment.groovy

* Adds an off-by-default feature-toggle to the Groovy implementation of `cloudFoundryDeploy` to use the new go implementation.
* Fixes the go metadata's parameter scopes and adds the inputs for the Jenkins credentials IDs.
* Adds writing "buildTool" resource to common pipeline environment.
* Makes deployTool parameter optional, adds buildTool parameter, derived from CPE,  and filling deployTool from buildTool if necessary.

Add optional wrapper for cloudFoundryDeploy go-implementation

---

pkg/abaputils/abaputils.go
pkg/abaputils/abaputils_test.go

This change aims to avoid a runtime error, which was caused by an unsuccessful unmarshal.

Correction in abaputils

---

cmd/protecodeExecuteScan.go
cmd/protecodeExecuteScan_test.go
pkg/protecode/analysis.go
pkg/protecode/analysis_test.go
pkg/protecode/api.go
pkg/protecode/protecode.go
pkg/protecode/protecode_test.go
pkg/protecode/report.go
pkg/protecode/report_test.go

This changes makes the Protecode step fail when severe vulnerabilities (CVSS > 7.0) are found and the property `failOnSevereVulnerabilities` is set to true.
**further changes:**
- respect deprecated parameter `excludedCVEs`
- extract reporting function to `protecode` package
- define meaningful api status constants
- remove unconsidered return value of main step function
- fix redundant type issues
fixes #1970

fix(protecode): respect failOnSevereVulnerabilities parameter

---

cmd/protecodeExecuteScan.go
cmd/protecodeExecuteScan_test.go

This PR fixes an issue with the naming of the artifact to scan. Before it was named `<artifactName>:<artifactVersion><majorVersionDigit>.tar`, it is now correctly named `<artifactName>_<majorVersionDigit>.tar`. 
fixes #1972

fix(protecode): correct project naming

---

resources/default_pipeline_environment.yml
test/groovy/TestsPublishResultsTest.groovy
vars/testsPublishResults.groovy

This change extends the testsPublishResults step to support publishing
of HTML reports using the HTML publisher plugin. This change is a
preparation for the migration of frontend unit tests as already existing
in the SAP Cloud SDK Pipeline to the
piperPipelineStageAdditionalUnitTests.

Extend testsPublishResults step to support publishing of HTML reports

---

documentation/docs/pipelines/cloud-sdk/build-tools.md
resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
test/groovy/templates/PiperPipelineStageAdditionalUnitTestsTest.groovy
vars/piperPipelineStageAdditionalUnitTests.groovy

This change adds the support for running frontend unit tests using the
`npmExecuteScripts` step in the `piperPipelineStageAdditionalUnitTests`.

Add npmExecuteScripts to piperPipelineStageAdditionalUnitTests

---

cmd/completions.go
cmd/piper.go

Small change to allow better interactive cli usage of piper. This makes use of cobra's feature as described here https://github.com/spf13/cobra/blob/master/shell_completions.md
Usage example after typing `piper maven<tab><tab>`:

Add command for command line completion scripts

---

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
test/groovy/templates/PiperPipelineStageBuildTest.groovy
vars/piperPipelineStageBuild.groovy

This change adds the support for executing maven static code checks and
linting using the mavenExecuteStaticCodeChecks and npmExecuteLint steps
as part of the piperPipelineStageBuild.

Add npmExecuteLint and mavenExecuteStaticCodeChecks to build stage

---

vars/sonarExecuteScan.groovy

If env.BRANCH_NAME is null, the env variable will be `PIPER_branchName=null`, i.e. pass "null" as the branch name.
The idea behind the original change was, if `sonarExecuteScan` is being run in a non-productive branch, it needs the branchName parameter. I am not sure if we should also check if the "branch plugin" is installed before setting this property, or if it actually means that the setup is wrong and the pipeline should rightfully fail. (The error message is then "To use the property "sonar.branch.name", the branch plugin is required but not installed.")
Or to word it differently: Is it a valid use-case to *not* pass `branchName` if the pipeline runs a non-productive branches?

Hotfix: Check env.BRANCH_NAME before using

---

vars/sonarExecuteScan.groovy

It became clear that it is too inflexible if the step infers when to pass the `branchName` parameter. There are project which change the sonar project name in each branch, other projects make a sonar scan only in one of their branches, but that is not the productive branch.
-> Revert the recent change and rely on the users of the step to avoid scanning into the same sonar project from multiple branches.

Fix for SonarQube: Remove check for non-productive branch

---

cmd/githubCheckBranchProtection.go
cmd/githubCheckBranchProtection_generated.go
cmd/githubCheckBranchProtection_test.go
cmd/githubCreatePullRequest_generated.go
cmd/githubSetCommitStatus.go
cmd/githubSetCommitStatus_generated.go
cmd/githubSetCommitStatus_test.go
documentation/docs/steps/githubCreatePullRequest.md
documentation/mkdocs.yml
resources/metadata/githubbranchprotection.yaml
resources/metadata/githubcreatepr.yaml
resources/metadata/githubstatus.yaml

Convenience updates to GitHub steps:
* use information from `commonPipelineEnvironment`
* update default
Add additional information to check status
Add missing documentation
Fix `nil de-reference` error when no checks are maintained

GitHub steps: convenience updates

---

cmd/abapEnvironmentCloneGitRepo_generated.go
resources/metadata/abapEnvironmentCloneGitRepo.yaml
test/groovy/CommonPipelineEnvironmentTest.groovy
vars/commonPipelineEnvironment.groovy

It was originally planned to pass repositoryNames through this pipeline. repositoryNames is superseded by the more extensive addonDescriptor.
The resourceRef abap/repositories also relates to an earlier design and was never fully implemented. This is not required anymore.

Changes to commonPipelineEnvironment for ABAP

---

cmd/artifactPrepareVersion.go

fixes categorization of errors like
```
artifactPrepareVersion failed - failed to push changes for version '0.0.1-20200920213337': knownhosts: /var/jenkins_home/.ssh/known_hosts:9: illegal base64 data at input byte 8
```

artifactPrepareVersion: fix error categorization

---

vars/neoDeploy.groovy

the space does not contribute to the uniqueness of the lock
identifier. Hence the space should be removed.

Remove useless space from lockIdentifier

---

pkg/documentation/generator/main.go

> Go provides two pretty amazing templating libraries - text/template and html/template. How you use these templates is identical, but behind the scenes the html/template package will do some encoding to help prevent code injection. 
Looks like I mixed this up with #2033.
https://github.com/SAP/jenkins-library/blob/4d9d2e78d81f9c1a0317c6a2cecfa127e0e4b927/pkg/generator/helper/docuHelper.go#L10
fixes #2073

docs: use correct template library

---

test/groovy/templates/PiperPipelineStageSecurityTest.groovy
vars/piperPipelineStageSecurity.groovy

This change adds the detectExecuteScan step to the
piperPipelineStageSecurity.

Extend piperPipelineStageSecurity to run detectExecuteScan step

---

src/com/sap/piper/Utils.groovy

without 'int' in a 'for (i = 0; ...)' loop 'i' is
a global variable and the value gets inside some parallel
execution randomly incremented from the parallel threads.
Defining it with the keyword 'int' makes it a method local
variable which does not change its value 'randomly'.

fix: make unstash work for parallel executions

---

pkg/documentation/generator.go
pkg/documentation/generator/description.go
pkg/documentation/generator/description_test.go

This PR provides the ability to run the docs generator with `--customLibraryStepFile` parameter to provide a list of custom steps. In the docs sample section for these steps a custom library name and binary name will be used.
Also add the `library('...')` tag that needs to be used to call the step.
The `customLibraryStepFile` parameter required a file in the following format:
```yaml
- name: anyName
binaryName: myBinary
libraryName: my-custom-library-name
steps:
- myCustomStep
- ...
```

docs: make used library and binary name in samples exchangeable

---

resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml

This change fixes the stash settings for the security stage in Cloud
SDK Pipeline. Previously, the SOURCES stash was not unstashed, thus
potentially existing extensions could not be found.

Fix Cloud SDK Pipeline stash settings for security stage

---

test/groovy/templates/PiperPipelineStageInitTest.groovy
vars/piperPipelineStageInit.groovy

Allow calling the `piperPipelineStageInit` with the parameters `configFile` and `customDefaultsFromFiles` in addition to the already forwarded `customDefaults`.
Still only `customDefaults` can be parameter to `piperPipeline`, I've not modified the GP pipeline itself. The Init stage is however called from the Cloud SDK Pipeline, and the change is useful there.

Forward config-related params to setupCommonPipelineEnvironment

---

test/groovy/SetupCommonPipelineEnvironmentTest.groovy
test/groovy/templates/PiperPipelineStageInitTest.groovy
vars/piperPipelineStageInit.groovy
vars/setupCommonPipelineEnvironment.groovy

Everything cpe related should be done in setupCommonPipelineEnvironment.
Thus a new parameter was introduced to accept the scmInfo object
returned by a checkout.

Move setting git info in cpe from stage init to setupCPE step

---

cmd/detectExecuteScan.go

Adds an error category for policy violation issues.
```log
10:03:04  info  detectExecuteScan - 2020-10-06 08:03:04 INFO  [main] --- Overall Status: FAILURE_POLICY_VIOLATION - Detect found policy violations.
10:03:04  info  detectExecuteScan - 2020-10-06 08:03:04 INFO  [main] --- 
10:03:04  info  detectExecuteScan - 2020-10-06 08:03:04 INFO  [main] --- ===============================
10:03:04  info  detectExecuteScan - 2020-10-06 08:03:04 INFO  [main] --- 
10:03:04  info  detectExecuteScan - 2020-10-06 08:03:04 INFO  [main] --- Detect duration: 00h 01m 56s 765ms
10:03:04  error detectExecuteScan - 2020-10-06 08:03:04 ERROR [main] --- Exiting with code 3 - FAILURE_POLICY_VIOLATION
```

chore(detect): add error category for policy violations

---

cmd/sonarExecuteScan.go

Adds error category for `You must define the following mandatory properties for 'Unknown': sonar.projectKey, sonar.sources`.

chore(sonar): add error category

---

pkg/abaputils/abaputils.go

The ABAP steps run occasionally into EOF HTTP errors.
It seems that this issue corresponds to https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi
This PR is the proposed solution

Fix EOF http issue

---

cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_test.go

Pass correct module path to npm.InstallAllDependencies(). We are already in the module's directory.

WhiteSource: Pass correct module path to npm.InstallAllDependencies()

---

resources/default_pipeline_environment.yml
test/groovy/MulticloudDeployTest.groovy
vars/multicloudDeploy.groovy

This reverts commit 32fd89c6640da852b20206df19aa35bee2f7452e.
Commit mentioned above has been merged in order to circumvent
the issue which has been resolved by commit 0a17ed56. Since this
issue is now resolved and since there is no other known use case
for running deployments explicitly in parallel we decided to remove
that flag again.

Revert "allow multicloud deployment to run in current workspace (#2031)"

---

src/com/sap/piper/analytics/InfluxData.groovy

The `net.sf.json.JSONSerializer` reads only `map` and `list` from JSON. 
With this change the Influx handler reads the content again wrapped into an object if an error occurred during reading.
required by #2132

fix(influx): read simple values from json

---

cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_generated.go
cmd/whitesourceExecuteScan_test.go
resources/metadata/whitesource.yaml

This change fixes an issue with the default maven excludes where the step would fail when performance tests are present in the project, but are not a module in the root pom. In addition, it provides a small fix of an assertion on a file path to also work on Windows.

WhiteSource: Remove performance-tests from default maven excludes

---

pkg/documentation/generator/description.go
pkg/documentation/generator/description_test.go
pkg/documentation/generator/helper.go
pkg/documentation/generator/parameters.go

Correct header for `Description` and align handling of `md` healing syntax.

fix(docs): correct md syntax for headlines

---

pkg/documentation/generator/main.go
pkg/documentation/generator/main_test.go
pkg/documentation/generator/parameters.go

This PR makes the docs generator flag parameters that come with a default as optional. This also corrects the default values depending on their type to be not `nil`.

fix(docs): flag mandatory parameters with default value as non-mandatory

---

resources/metadata/cloudFoundryDeploy.yaml

This PR corrects the type of the default for `manifestVariablesFiles` to be `[]string` instead of `string`.

fix(cfDeploy): correct type of default value

---

documentation/docs/scenarios/abapEnvironmentAddons.md
documentation/mkdocs.yml

We would like to provide a scenario documentation for the use case of building Add-ons for the ABAP Environment Pipeline.
The go live of this scenario will be soon. However, we still want to provide an initial documentation now in order to link it in the official help.sap.com documentation.

Add initial docu for scenario: "Build and Publish ABAP Add-ons"

---

documentation/docs/pipelines/cloud-sdk/configuration.md
resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml
resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml
resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml
resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml
resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml
resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml

This change updates the stash settings, stage defaults and the containers map to
allow a single call of `piperPipelineStageIntegration` in SAP Cloud SDK Pipeline.

Cloud SDK: Update stash settings, stage defaults and containers map for a single call of integration stage

---

cmd/detectExecuteScan.go
cmd/detectExecuteScan_test.go
cmd/mtaBuild_test.go
pkg/maven/maven.go
pkg/maven/settings.go

Fixes #2237
* Check error from DownloadFile().
* Add deletion of "detect.sh".
* Fix tests. Shows why to avoid `assert.NotNil(t, err)`, since the test was actually getting a different error than what it tested for.
* Avoid using exported `piperutils.FileUtils` interface, at least in code I had to touch. I would have needed to extend this interface for `FileRemove()`, but this would necessitate changes in all unrelated clients of this interface, with no-op functions. That is the reason why interfaces should be declared at the client, not the provider of a struct. See also [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#interfaces).

detectExecuteScan: Clean up detect.sh

---

resources/metadata/mtaBuild.yaml

The old image still configures the not used anymore registry npm.sap.com. Update to get rid of that.

Bump mta builder default image to 1.0.16.1

---

test/groovy/NpmExecuteEndToEndTestsTest.groovy
vars/npmExecuteEndToEndTests.groovy

Remove hard-coded `install: false` in `npmExecuteScripts` call to allow the pipeline to configure the step according to how it is right for that pipeline.
- [N/A ] Documentation

Allow npm install in e2e tests

---

resources/metadata/npmExecuteScripts.yaml

The current stash settings don't include required files for running cucumber tests, thus this PR uses the larger skoped `source` stash.

Unstash "source" for npmExecuteScripts

---

pkg/log/log.go
pkg/log/log_test.go

Although secrets are masked when they appear in the log output there are certain scenarios where they can appear inside a url where they are properly encoded so that they are human readable but not recognised as the registered secret.
Now when a secret is registered we also check wether it looks different when it's url encoded (i.e if it contains special characters) if so we will also mask the url encoded values in the log

mask secret also when they are url encoded

---

test/groovy/FioriOnCloudPlatformPipelineTest.groovy
test/groovy/SetupCommonPipelineEnvironmentTest.groovy
vars/piperPipelineStageInit.groovy
vars/setupCommonPipelineEnvironment.groovy

When handing over an instance of SCMInfo we got a
CPS serialization issue. Hence we don't hand over
that instance any more
o git commit id is resolved with exising git tooling
o git branch is handed over as parameter to setupCPE

Avoid CPS serialization issue in setupCPE

---

pkg/config/vault.go

In 99% you don't care about the vault log messages. However since they are quite useful for debugging a pipeline they should be visible when debugging is enabled
closes #2255

Vault: Switch to debug logging for some vault log messages

---

test/groovy/SetupCommonPipelineEnvironmentTest.groovy
vars/setupCommonPipelineEnvironment.groovy

Without this change the closure in the switch case will throw an CpsCallableInvocation exception.
Example output with a `gitPath == 3`:
>CpsCallableInvocation{methodName=call, call=com.cloudbees.groovy.cps.impl.CpsClosureDef@47c84984, receiver=org.jenkinsci.plugins.workflow.cps.CpsClosure2@c34320d, arguments=[3]}

Fix setupCPE bug

---

resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml

Will prompt Cloud SDK Pipeline users to rename their config key.

Add "checkGatling" to deprecated steps

---

resources/metadata/abapEnvironmentAssemblePackages.yaml
resources/metadata/abapEnvironmentCheckoutBranch.yaml
resources/metadata/abapEnvironmentCloneGitRepo.yaml
resources/metadata/abapEnvironmentCreateSystem.yaml
resources/metadata/abapEnvironmentPullGitRepo.yaml
resources/metadata/abapEnvironmentRunATCCheck.yaml
resources/metadata/cloudFoundryCreateService.yaml
resources/metadata/cloudFoundryCreateServiceKey.yaml
resources/metadata/cloudFoundryCreateSpace.yaml
resources/metadata/cloudFoundryDeleteService.yaml
resources/metadata/cloudFoundryDeleteSpace.yaml
resources/metadata/cloudFoundryDeploy.yaml
resources/metadata/mavenBuild.yaml
resources/metadata/mavenExecute.yaml
resources/metadata/mavenExecuteIntegration.yaml
resources/metadata/mavenStaticCodeChecks.yaml
resources/metadata/mtaBuild.yaml
resources/metadata/nexusUpload.yaml
resources/metadata/npmExecuteLint.yaml
resources/metadata/npmExecuteScripts.yaml
resources/metadata/versioning.yaml
resources/metadata/xsDeploy.yaml

Without this change the default setting from dockerExecute and dockerExecuteOnKubernetes are overruled.
With this change the user has to explicitly configure the step if they want this behaviour.

Remove image pull policy from steps defaults

---

resources/com.sap.piper/pipeline/cloudSdkToGppConfigSettings.yml
src/com/sap/piper/LegacyConfigurationCheckUtils.groovy
test/groovy/com/sap/piper/LegacyConfigurationCheckUtilsTest.groovy

* Instead of letting the pipeline fail for the first config validation error, accumulate all errors and output them to the log, then fail.
* Beginnings of a resource for validating a config.yml migrated to the GPP. Can be configured in the general section:
```yaml
general:
legacyConfigSettings: 'com.sap.piper/pipeline/cloudSdkToGppConfigSettings.yml'
```

Accumulate config validation errors

---

cmd/detectExecuteScan_test.go
cmd/mavenExecuteIntegration_test.go

Enables parallelization of tests by removing reused mocks and adding parallel command.
Proposal for https://github.com/SAP/jenkins-library/issues/2136.

Enable parallel execution with reused mocks

---

cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_generated.go
cmd/kubernetesDeploy_test.go
resources/metadata/kubernetesdeploy.yaml

At the moment failed deployments will be deleted immediately which limits the debugging options. It should be possible to keep a failed deployment to be able to debug the error
Add `keepFailedDeployments` parameter to enable debugging when using helm 
**Important Note**
This PR enables the --atomic parameter for helm2 deployments. At the moment it is just enabled for helm3 deployments

(kubernetesDeploy) allow to keep a failed deployment 

---

resources/com.sap.piper/pipeline/stageDefaults.yml

Add stage run configuration to autodetect the presence of "ci-frontend-unit-test" script(s) and enable the step "npmExecuteScripts" in the stage "Additional Unit Tests" automatically.

Conditions for npmExecuteScripts in Additional Unit Tests

---

cmd/mtaBuild.go

`DownloadFile` is already defined in [`maven.Utils`](https://github.com/SAP/jenkins-library/blob/bc38af7c919c1fc8df70f71de26f481292944b03/pkg/maven/maven.go#L46). This is marked as error during local build: 
```log
/***/jenkins-library/cmd/mtaBuild.go:88: duplicate method DownloadFile
note: module requires Go 1.15
FAIL	github.com/SAP/jenkins-library/cmd [build failed]
FAIL
```

remove duplicate function from interface

---

resources/com.sap.piper/pipeline/stashSettings.yml
vars/piperPipelineStageIntegration.groovy

The integration tests always require sources and build results to be unstashed, so we unstash them as part of the stage.

Unstash sources in integration tests

---

.pipeline/config.yml

Shall we ignore issues with the [stale label](https://github.com/SAP/jenkins-library/issues?q=is%3Aopen+is%3Aissue+label%3Astale) in release notes?

chore(release): ignore stale issues

---

cmd/abapEnvironmentRunATCCheck.go

This PR catches the error mentioned in #2337. Unit tests will be handled in a separate Pull Request
Since there is no try and catch in Golang this seems like the best option to me

Catch runtime error in ATC step

---

resources/default_pipeline_environment.yml

#Changes
To install artifacts later it is required to also have the original jar (created in case of spring repackaging) available in other stages.

Stash also original jar

---

resources/com.sap.piper/pipeline/stashSettings.yml

When specifying `mavenDeploymentModule` for the step `neoDeploy`, it needs the pom.xml file(s).

Fix stage stashes for potential use of neoDeploy

---

cmd/abapEnvironmentCloneGitRepo.go
pkg/abaputils/manageGitRepositoryUtils.go

The polling of the Clone status has to be done using the "Pull" entity.
There was an issue with the creation of the correct URL: Namespaces were not handled correctly.
It was formerly expected that the name of the software component was given as "/DMO/SWC" within the URI returned from the ABAP system. However, the ABAP system actually returns: "%2FDMO%2FSWC". 
The new logic works independently from  the software component.

Fix: Change URL creation for abapEnvironmentCloneGitRepo

---

vars/cloudFoundryDeploy.groovy

fix(cfDeploy): fix stash for go step

---

documentation/docs/scenarios/abapEnvironmentAddons.md

_Was ist ein „software product“? Im addon.yml definiere ich addonProduct, addOnVersion, und repositories. Ich fände es gut, wenn wir diese Begriffe konsistent verwenden. Und nach Möglichkeit Synonyme vermeiden._
Rename software product to add-on product

Replace naming of software product with add-on product

---

.github/workflows/verify-go.yml

With the current approach we get a failure when the generated
content triggers a change. But we cannot see what was changed.
With this commit we can see the diff. In case there is not diff
we will not see anything, so there is in that case no real change
in the behaviour. But in case there is a change we will see that
change.
Without that we have to reproduce locally, which means additional
efforts.

Tell us what was changed.

---

go.mod
go.sum
pkg/fortify/fortify.go
pkg/fortify/fortify_test.go

With latest Fortify SSC update a parameter was removed from two API calls, therefore we need to adapt our usage.

Remove obsolete parameter

---

resources/default_pipeline_environment.yml
test/groovy/CloudFoundryDeployTest.groovy

With https://github.com/SAP/devops-docker-cf-cli/pull/32 we introduce cf version 7.2
To avoid unforeseen incompatible changes we fix the ppiper/cf-cli version to v5 in the defaults.
- [x ] Tests

Temporary fix ppiper/cf-cli version

---

cmd/fortifyExecuteScan_generated.go
cmd/githubCreatePullRequest_generated.go
cmd/githubPublishRelease_generated.go
cmd/githubSetCommitStatus_generated.go
cmd/sonarExecuteScan_generated.go
resources/metadata/fortify.yaml
resources/metadata/githubcreatepr.yaml
resources/metadata/githubrelease.yaml
resources/metadata/githubstatus.yaml
resources/metadata/sonar.yaml

Add `access_token` alias for all github secrets

add access_token alias to all gh secrets

---

pkg/config/stepmeta.go
pkg/config/stepmeta_test.go

non-string parameters were so far handled incorrectly when reading from `commonPipelineEnvironment`

fix(config): properly read non-string parameters from environment

---

vars/malwareExecuteScan.groovy

Removing this code will not print the following echo message twice in the logs:
` --- End library step of: malwareExecuteScan ---`

Remove handle pipeline step errors from groovy glue code

---

go.mod
go.sum
pkg/http/http.go
pkg/http/http_test.go

Allow usage of [`httpmock`](https://github.com/jarcoal/httpmock#usage) by optionally using the `DefaultTransport` object in the http client.
required by #2218

test: allow usage of httpmock in tests

---

cmd/cloudFoundryDeploy.go
cmd/cloudFoundryDeploy_test.go

printing the cf cli version into the log. Knowing which version of the cf cli is used and having that information in the log at the point in time when deployment happens speeds up troubleshooting.

print version of cf cli

---

test/groovy/templates/PiperPipelineStageInitTest.groovy
vars/piperPipelineStageInit.groovy

This change makes it optional for the user to checkout the sources in the piperPipelineStageInit step. For the Cloud CI Service we want to checkout the sources before this step.
skipCheckout flag (defaults to false)
scmInfo parameter to pass to setupCommonPipelineEnvironment

Skip checkout flag

---

pkg/whitesource/scanReports.go
pkg/whitesource/scanReports_test.go
pkg/whitesource/sytemMock.go

report file names of projects which had a structure in the name
like `@test/myProject ` were incorrectly handled
This now prevents that reports are targeted to a sub directory.
Structure is now part of the filename.

fix(whitesourceExecuteScan) correctly handle structured projects

---

test/groovy/CommonPipelineEnvironmentTest.groovy
vars/commonPipelineEnvironment.groovy

fixes error `Error: net.sf.json.JSONException: Invalid JSON String` in following situations
```
commonPipelineEnvironment.setValue('bool', true)
commonPipelineEnvironment.setValue('int', 1)
commonPipelineEnvironment.setValue('float', 1.7)
commonPipelineEnvironment.setValue('string', 'this is my string')
commonPipelineEnvironment.writeToDisk(this)
commonPipelineEnvironment.readFromDisk(this)
```
replaces #2627

fix(cpe) readToDisk failes with content from writeToDisk

---

.github/workflows/integration-tests-pr.yaml
.github/workflows/integration-tests.yaml

This exposes the `PIPER_INTEGRATION_SONAR_TOKEN` secret needed for #2218 to the integration tests.

tests: expose sonar test secret to workflows

---

pkg/sonar/taskService.go

The tasks endpoint for a certain version (<7.x?) does not support the `warnigns` field, thus removing it for now.

fix(sonar): remove warnings handling

---

cmd/sonarExecuteScan.go

If no token is set use token provided by sonar-scanner-jenkins plugin in `SONAR_AUTH_TOKEN`.

fix(sonar): use token provided by sonar-scanner-jenkins plugin

---

cmd/sonarExecuteScan.go

measurements are no longer retrieved if 
- no credentials are provided
- no task report is available

fix(sonar): disable measurements if no credentials are provided

---

pkg/transportrequest/gitutils.go
pkg/transportrequest/gitutils_test.go

for compatibility the transport request/changedocument label needs to be adusted.

transport request: consider old label default

---

cmd/cloudFoundryDeploy.go
cmd/cloudFoundryDeploy_test.go
cmd/mtaBuild_test.go
pkg/mock/fileUtils.go
pkg/piperutils/FileUtils.go
pkg/sonar/sonar_test.go

Go Unit Tests fail due to windows/linux file separator mismatch

---

pkg/config/stepmeta.go
pkg/config/stepmeta_test.go

When a step only hat a vaultSecretFile Reference the vault credentials where not injected since the ContextParamFilter didn't return the correct filter.

[Vault] Fix ContextParamFilters for vaultSecretFile

---

cmd/whitesourceExecuteScan_generated.go
pkg/whitesource/scanUA.go
pkg/whitesource/scanUA_test.go
resources/metadata/whitesource.yaml

multi-module projects were handled incorrectly.
For example in the Maven case only the root module was considered for security scanning and not all sub-modules.
This also lead to in incomplete list of scanned projects handed over to subsequent steps.

fix(whitesourceExecuteScan) get full list of projects

---

cmd/sonarExecuteScan.go
pkg/sonar/report.go
pkg/sonar/report_test.go
vars/sonarExecuteScan.groovy

With this change the `sonarExecuteScan` step creates a report `sonarscan.json` which contains:
- sonar server url
- project key
- task id
- number of issues by severity

feat(sonar): create report for issue count 

---

cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_generated.go
cmd/whitesourceExecuteScan_test.go
resources/metadata/whitesource.yaml

don't use native build-tool specific plugins any longer.
They have been deprecated by WhiteSource mid 2019 already.

whitesource: use only Unified Agent for scanning

---

test/groovy/DockerExecuteOnKubernetesTest.groovy
vars/dockerExecuteOnKubernetes.groovy

This will add a parameter `containerMountPath` which can be used to mount a volume available at this path in each container defined in the `containerMap`. We use it together with `additionalPodProperties` to combine it with an initContainer.

dockerExecuteOnKubernetes: Add capability for volume mounts

---

pkg/abap/build/connector.go

As apps.support.sap.com will work with basic auth only for dedicated User Agents in the future we set one

set User-Agent Header

---

test/groovy/CheckmarxExecuteScanTest.groovy
test/groovy/MavenExecuteIntegrationTest.groovy
test/groovy/NexusUploadTest.groovy
test/groovy/PiperExecuteBinTest.groovy
vars/writePipelineEnv.groovy

* CPE was not written when map was empty. (groovy treats empty maps as falsy 😞 )

[CPE] write commonPipelineEnvironment even when it's empty

---

pkg/piperenv/CPEMap.go
pkg/piperenv/CPEMap_test.go
vars/sonarExecuteScan.groovy

During the execution of the sonarExecuteStep there is no pipeline environment present, since the `writePipelineEnv` call was never executed inside the container.
The new go implementation of reading the common pipeline environment had changed the behaviour of what happens when the `.pipeline/commonPipelineEnvironment` directory is not present to throwing an error. This is now changed back to simply ignoring it.

[CPE] Missing pipeline environment in sonar docker container

---

cmd/kanikoExecute_generated.go
resources/metadata/kaniko.yaml

* pin kaniko container version to v1.3.0-debug (https://github.com/GoogleContainerTools/kaniko/issues/1586)

fix(kaniko): pin kaniko version to v1.3.0-debug (latest working version)

---

cmd/githubCreateIssue.go

In case the Github connection leads to an error it can happen that a nil pointer dereference exception can occur.
This is to fix this.

fix(githubCreateIssue): prevent panic for Github error

---

cmd/whitesourceExecuteScan.go

Filter alerts that are persisted in the version wide aggregated vulnerabilities report to only contain actual vulnerability reports.

[WhitesourceExecuteScan] Show Vulnerabilities in Aggregated Report Only

---

cmd/init_unix.go

Unix systems use [umasks](https://en.wikipedia.org/wiki/Umask) to control permissions on newly created files or directories.
As a default  umask `022` is often picked.  Which means that the permission `777` will result in `755` after the umask was applied or
`766` will result in `744`. Or in words the `write` permission will be removed for `groups` and `others`.
Piper tries to write files and create directories with very broad permissions at several places ([writing outputs](https://github.com/SAP/jenkins-library/blob/8883a5148c0801d854d93a0f9b12ec1c7858151b/pkg/piperenv/environment.go#L59-L65)) in the past the permissions specified in the code were never the permissions that ended up on the filesystem on unix systems since the umask was applied first.
Most of the time this was not a …

fix: piper never writes with correct file permissions since umask is never considered

---

pkg/whitesource/scanReports.go
pkg/whitesource/scanReports_test.go

This PR adds logging output to the report download mechanism of the WhiteSource step.
The extended logging mechanism supports us in resolving issues with downloaded files from WS.

(feat) adds error logging output for downloading reports from WhiteSource

---

cmd/mavenExecuteIntegration.go
cmd/mavenExecuteIntegration_generated.go
cmd/mavenExecuteIntegration_test.go
resources/metadata/mavenExecuteIntegration.yaml

adds the ability to define a maven lifecycle goal different from default `test`.
Required for Mojo's `integration-tests` and `report-aggregate`which only come later.
Ref: https://github.wdf.sap.corp/ContinuousDelivery/piper-library/issues/3600

mavenExecuteIntegration: add maven lifecycle goal as parameter

---

cmd/writePipelineEnv.go
pkg/piperenv/CPEMap.go
pkg/piperenv/CPEMap_test.go

Whenever go decodes a json field which is of type number and the target type is unknown (`interface{}`) go will automatically choose `float64`. When doing that the numbers are also cleaned (`5.000` becomes `5`).
This behaviour could potentially lead to some errors when groovy code writes float types and go code converts them to int types. 
This behaviour of go can be disabled by calling `UseNumbers` on the `json.Decoder`. By doing this a string representation of the number is kept so that it can be properly encoded again without messing up numbers
Change `assert` package to `require` in tests to abort the test when something is not working

fix(commonPipelineEnvironment): keep json numbers untouched

---

cmd/integrationArtifactDeploy_generated.go
cmd/integrationArtifactDownload_generated.go
cmd/integrationArtifactGetMplStatus_generated.go
cmd/integrationArtifactGetServiceEndpoint_generated.go
cmd/integrationArtifactUpdateConfiguration_generated.go
cmd/integrationArtifactUpload_generated.go
documentation/docs/steps/integrationArtifactDeploy.md
documentation/docs/steps/integrationArtifactDownload.md
documentation/docs/steps/integrationArtifactGetMplStatus.md
documentation/docs/steps/integrationArtifactGetServiceEndpoint.md
documentation/docs/steps/integrationArtifactUpdateConfiguration.md
documentation/docs/steps/integrationArtifactUpload.md
resources/metadata/integrationArtifactDeploy.yaml
resources/metadata/integrationArtifactDownload.yaml
resources/metadata/integrationArtifactGetMplStatus.yaml
resources/metadata/integrationArtifactGetServiceEndpoint.yaml
resources/metadata/integrationArtifactUpdateConfiguration.yaml
resources/metadata/integrationArtifactUpload.yaml
vars/integrationArtifactDeploy.groovy
vars/integrationArtifactDownload.groovy
vars/integrationArtifactGetMplStatus.groovy
vars/integrationArtifactGetServiceEndpoint.groovy
vars/integrationArtifactUpdateConfiguration.groovy
vars/integrationArtifactUpload.groovy

Change `cpiAPIServiceKeyCredentialId` to `cpiApiServiceKeyCredentialsId` in all CPI Steps so that the variable name can be consistent.

CPI- Refactor Credential ID

---

cmd/integrationArtifactDeploy_generated.go
cmd/integrationArtifactDownload_generated.go
cmd/integrationArtifactGetMplStatus_generated.go
cmd/integrationArtifactGetServiceEndpoint_generated.go
cmd/integrationArtifactUpdateConfiguration_generated.go
cmd/integrationArtifactUpload_generated.go
resources/metadata/integrationArtifactDeploy.yaml
resources/metadata/integrationArtifactDownload.yaml
resources/metadata/integrationArtifactGetMplStatus.yaml
resources/metadata/integrationArtifactGetServiceEndpoint.yaml
resources/metadata/integrationArtifactUpdateConfiguration.yaml
resources/metadata/integrationArtifactUpload.yaml

in the params section of the yaml files of each cpi step, change resourceRef name needed to match the name in the secrets at the top of the file (`cpiApiServiceKeyCredentialsId`) , and change param to match the name of the parent param (`apiServiceKey`)

CPI- Change resourceRef of apiServiceKey

---

cmd/integrationArtifactDeploy_generated.go
cmd/integrationArtifactDownload_generated.go
cmd/integrationArtifactGetMplStatus_generated.go
cmd/integrationArtifactGetServiceEndpoint_generated.go
cmd/integrationArtifactUpdateConfiguration_generated.go
cmd/integrationArtifactUpload_generated.go
resources/metadata/integrationArtifactDeploy.yaml
resources/metadata/integrationArtifactDownload.yaml
resources/metadata/integrationArtifactGetMplStatus.yaml
resources/metadata/integrationArtifactGetServiceEndpoint.yaml
resources/metadata/integrationArtifactUpdateConfiguration.yaml
resources/metadata/integrationArtifactUpload.yaml

Puts the parameters `integrationFlowId` and `integrationFlowVersion` into the general scope to simplify configuration.

CPI - Put share cpi parameters in general scope

---

cmd/integrationArtifactDeploy_generated.go
cmd/integrationArtifactDeploy_test.go
cmd/integrationArtifactGetMplStatus_generated.go
cmd/integrationArtifactGetMplStatus_test.go
cmd/integrationArtifactGetServiceEndpoint_generated.go
cmd/integrationArtifactGetServiceEndpoint_test.go
cmd/integrationArtifactUpdateConfiguration_generated.go
documentation/docs/steps/integrationArtifactDeploy.md
documentation/docs/steps/integrationArtifactGetServiceEndpoint.md
documentation/docs/steps/integrationArtifactTriggerIntegrationTest.md
documentation/docs/steps/integrationArtifactUpdateConfiguration.md
resources/metadata/integrationArtifactDeploy.yaml
resources/metadata/integrationArtifactGetMplStatus.yaml
resources/metadata/integrationArtifactGetServiceEndpoint.yaml
resources/metadata/integrationArtifactUpdateConfiguration.yaml

As platform isn't used anywhere in the cpi steps, we should remove it.
It was originally found in 4 of the 6 existing steps: Deploy, GetMPLStatus, GetServiceEndpoint, and UpdateConfig.

CPI- Remove platform parameter

---

test/groovy/ChecksPublishResultsTest.groovy
vars/checksPublishResults.groovy

This change attempts to fix #2881
`findbugs` plugin and some other related plugins has been [removed](https://issues.jenkins.io/browse/INFRA-2487) from the updated center.  After purging a Jenkins instance these plugins cannot be installed anymore in an automated way. Nevertheless these plugins are still referenced by our shared lib.
It is still possible to manually install these plugins from the [archive](https://archives.jenkins-ci.org/plugins/), but installing plugins manually is clearly not a sustainable approach.
The approach here is to avoid calling the reporting tools (`findBugs`, `eslint`, ...) in case the corresponding tool in not activated. 
Up to now we had a two step approach. In a first step the reporting tool was called anyway (e.g. `findBugs()`, `esLint()`, ...). Later in …

checksPublishResults: prepare reports only if the reporting is active

---

cmd/whitesourceExecuteScan_generated.go
resources/metadata/whitesource.yaml

This pull request fixes an issue when executing whiteSource steps after xmake. This way whitesource step will read the image and registry from `commonPipelineEnvironment`. Using the same params as protecode scan

Fix whitesource issue

---

cmd/integrationArtifactGetMplStatus.go
cmd/integrationArtifactGetMplStatus_generated.go
cmd/integrationArtifactGetMplStatus_test.go
pkg/cpi/mockingUtils.go
resources/metadata/integrationArtifactGetMplStatus.yaml

Adding GetIntegrationArtifactMPLError function to return error if message processing fails. error will be captured in CommonPipelineEnvironment varibale i.e. iFlowMplError

GetIntegrationArtifactMPLError function

---

cmd/integrationArtifactUpload_generated.go
resources/metadata/integrationArtifactUpload.yaml

The `packageId` parameter is only mandatory when creating on upload. In case of an update to an existing artifact it is not necessary.

Make packageId optional

---

pkg/orchestrator/azureDevOps.go
pkg/orchestrator/azureDevOps_test.go

This pull request introduces changes which aim to improve determining the PR key from the environment if the provider is an Azure DevOps pipeline.
The existing implementation used the `SYSTEM_PULLREQUEST_PULLREQUESTID` environment variable as the PR key in the pull request configuration. Yet there are cases where this environment variable doesn't contain the pull request number but an internal ID. In these scenarios the environment variable `SYSTEM_PULLREQUEST_PULLREQUESTNUMBER` will be set and contain the number of the pull request ( see `System.PullRequest.PullRequestNumber` in [Azure Pipeline variable reference](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)).
Some tools for which the piper library provides predefined steps (e.g. …

Improve determining PR key in Azure DevOps provider

---

cmd/containerExecuteStructureTests_generated.go
cmd/kanikoExecute_generated.go
pkg/config/stepmeta.go
pkg/config/stepmeta_test.go
resources/metadata/containerExecuteStructureTests.yaml
resources/metadata/kaniko.yaml

it is possible to overwrite the entrypoint for docker execution:
https://docs.docker.com/engine/reference/run/#entrypoint-default-command-to-execute-at-runtime
This is ideally done by passing `entrypoint=''` and not pass two options to the call.
This also helps with escaping issues of the empty value on other systems.

fix(dockerOptions) properly pass empty values

---

pkg/config/stepmeta.go
pkg/config/stepmeta_test.go

This follows up on #3024
Setting emptyValue to s.th. like `--entrypoint=''` will break in case the argument is properly escaped.
Docker will return with
`container process caused: exec: "''": executable file not found in $PATH`

fix(dockerOptions) allow proper usage of empty values

---

cmd/checkmarxExecuteScan.go
cmd/checkmarxExecuteScan_generated.go
cmd/checkmarxExecuteScan_test.go
resources/metadata/checkmarx.yaml

Added new configuration property filled from commonPipelineEnvironment to enforce non-incremental scans on optimized and scheduled runs.

Enforce non-incremental scans when optimized and scheduled

---

pkg/npm/npm.go
pkg/npm/npm_test.go

- https://www.npmjs.com/package/@cyclonedx/bom does not contain schema parameter hence removing that during npm build when Bom creation is required 
fixes #3031

[fix] remove schema parameter from cycloneDX for npm build

---

documentation/docs/infrastructure/vault.md
pkg/config/vault.go
pkg/config/vault_test.go

allow custom prefix for environment variables created for test credentials

feat(Vault): custom prefix for test credentials

---

pkg/docker/docker.go

make sure that error when parsing registryURL does not get unnoticed

chore(docker): do not swallow error

---

pkg/whitesource/scanUA.go
pkg/whitesource/scanUA_test.go
pkg/whitesource/utilsMock.go

We encountered the error 404 that the file wss-unified-agent.jar could not been downloaded. After manual check the file is present under the known url. For better resilience we want to have *one* retry in case we see this error.

Adds retry for whitesource download in case of 404 not found

---

cmd/protecodeExecuteScan_generated.go
documentation/docs/steps/protecodeExecuteScan.md
resources/metadata/protecode.yaml

1) Existing documentation referenced an external article that does not exist.
2) protecodeExecuteScan expects that the docker config file is named 'config.json'. (For example kanikoExecute does not! expect that.)
The dockerConfigJSON parameter is used by protecodeExecuteScan to retrieve the directory only (for environment variable DOCKER_CONFIG).

Improve documentation for protecodeExecuteScan

---

src/com/sap/piper/Utils.groovy

Groovy sleep functionality  takes seconds and not milliseconds leading to a wait time of 50 minutes. Reduced it to 3 seconds.

Fixes time bug in unstash resilience 

---

cmd/whitesourceExecuteScan.go
pkg/toolrecord/toolrecord_main.go

toolrecord: fix generated URLs for the whitesource web UI
- [ x] Tests pass
- [ x] Documentation not required

toolrecord: fix web ui URLs for whitesource

---

cmd/kanikoExecute_generated.go
resources/metadata/kaniko.yaml

In order to send in the path to the written dockerConfigJSON using the Build Stage and kanikoExecute step, we need to add the STAGES and STEPS back in to the scope.

Add configuration for dockerConfigJSON

---

test/groovy/BuildExecuteTest.groovy
vars/buildExecute.groovy

In the documentation of buildExecute, it says that dockerImageName and dockerImageTag [are only mandatory when doing Docker builds](https://www.project-piper.io/steps/buildExecute/#:~:text=dockerImageName%20-%20For%20Docker%20builds%20only%20(mandatory)%3A%20name,tag%20of%20the%20image%20to%20be%20built.), but that wasn't the case in the code. We were seeing that they were mandatory for kanikoExecute and creating a parameter with them called "containerImageNameAndTag" and passing that to kanikoExecute, even though[ containerImageNameAndTag is a deprecated alias in kanikoExecute](https://www.project-piper.io/steps/kanikoExecute/#:~:text=containerImageNameAndTag%20(deprecated)). It's better to have kanikoExecute use the parameters defined in its own step than creating it from parameters …

Match documentation of buildExecute

---

test/groovy/TransportRequestUploadFileTest.groovy
vars/transportRequestUploadFile.groovy

This PR directs the RFC upload request of the TransportRequestUploadFile step to transportRequestUploadRFC.

TransportRequestUploadFile migration to Go - RFC

---

cmd/transportRequestUploadCTS_generated.go
resources/metadata/transportRequestUploadCTS.yaml
test/groovy/TransportRequestUploadFileTest.groovy
vars/transportRequestUploadFile.groovy

This PR directs the CTS upload request of the TransportRequestUploadFile step to transportRequestUploadCTS.

TransportRequestUploadFile migration to Go - CTS

---

cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_test.go

A docker registry created with Piper ended up not being recognized as of type **kubernetes.io/dockerconfigjson** because of double quotes placed and escaped in the program code. Command runs fine in a terminal without double quotes. This should allow secrets created by Piper to correctly access private Docker Repositories
Difference can easily be seen in the following screenshot:

fix(kubernetesDeploy): created secret type incorrectly set because of double quotes

---

cmd/kubernetesDeploy_generated.go
resources/metadata/kubernetesdeploy.yaml

In the step **kubernetesDeploy**, some secrets including kubeconfig and dockerConfigJSON are fetched from Vault.
In the case of kubeconfig, which works as intended, the logs indicate the following:
```
10:07:34  debug kubernetesDeploy - Trying to resolve vault parameter 'kubeConfig' at 'piper/PIPELINE-GROUP-***/PIPELINE-****/kube-config'
10:07:34  debug kubernetesDeploy - Trying to resolve vault parameter 'kubeConfig' at 'piper/PIPELINE-GROUP-***/GROUP-SECRETS/kube-config'
10:07:34  debug kubernetesDeploy - Resolved param 'kubeConfig' with vault path 'piper/PIPELINE-GROUP-***/GROUP-SECRETS/kube-config'
```
We see that Piper attempts to resolve a secret called kube-config from the default Vault paths. In the case of dockerConfigJSON, the following happens:
```
10:07:34  debug …
```

Missing default Vault path for parameter dockerConfigJSON in step kubernetesDeploy

---

cmd/cnbBuild.go

Current os.Environ content should be always appended to the lifecycle calls, to ensure that dockerEnvVars are properly passed to the buildpacks.

append os.Environ to the lifecycle calls

---

src/com/sap/piper/cm/StepHelpers.groovy
vars/transportRequestUploadFile.groovy

Solves #3131 
and hidden `cmClientOpts `issue: passing wrong type.

No such property: commonPipelineEnvironment for class: com.sap.piper.cm.StepHelpers

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
integration/integration_cnb_test.go
pkg/cnbutils/env.go
pkg/cnbutils/env_test.go
resources/metadata/cnbBuild.yaml
test/groovy/CnbBuildTest.groovy

New `buildEnvVars` argument for `cnbBuild` step which allows users to set environment variables which should be passed to buildpacks during a build phase.
#3020

cnbBuild: buildEnvVars argument for setting custom build env vars

---

cmd/mtaBuild.go

mtar file upload to remote repository like nexus or artifactory used multi-form data in the header which got included in http body and also in the final mtar artifact
curl avoids this issue using --upload-file parameter, but the mtar build container does not contain curl so had to modify the http to upload without multi-form data

fix (mtaBuild) Mtar file includes multi-form data metadata in the final artifact

---

pkg/cnbutils/buildpack.go
pkg/cnbutils/order.go
pkg/cnbutils/order_test.go

All custom buildpacks will be put under a single order entry when generating `order.toml` file.

fix(cnbBuild): put all custom buildpacks under single order entry

---

cmd/detectExecuteScan_generated.go
resources/metadata/detect.yaml

Looks like validation introduced with PR #3125 has issues with
validation of possible values for multi-value parameters.
This is a workaround to remove the list of possible values for some parameters
and prevent the issue from happening

fix(detectEcecuteScan) remove possible values for multi-value fields

---

pkg/generator/helper/helper.go
resources/metadata/kubernetesdeploy.yaml

Use `quote` template function during templates generation, in order to properly escape characters (e.g. `\n`, `"`).

fix(generator): use quote template function instead of direct quotes

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
go.mod
integration/integration_cnb_test.go
integration/testdata/TestCnbIntegration/config.yml
integration/testdata/TestCnbIntegration/zip/config.yml
pkg/cnbutils/bindings/bindings.go
pkg/cnbutils/bindings/bindings_test.go
resources/metadata/cnbBuild.yaml

Added support for configuring ["bindings" provided by paketo buildpacks](https://paketo.io/docs/howto/configuration/#bindings). They can be used e.g. for custom maven `settings.xml`, but this depends on the buildpack used.

feat(cnbBuild): support for paketo bindings

---

pkg/piperenv/CPEMap.go
pkg/piperenv/CPEMap_test.go

- CPE values with user id and password for private staging repos must be cleared post promotion of the artifact from the staging repo
- cpe variables with value 'toBeEmptied' will be removed during the readPipelineEnvironment.go step execution and empty values will be written to the file and the cpeMap

feat (cpe) ability to write an empty string to an existing cpe string value

---

cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_generated.go
cmd/kubernetesDeploy_test.go
resources/metadata/kubernetesdeploy.yaml

Add an optional parameter to run `replace --force` instead of `apply` when running the kubernetesDeploy step with the kubectl flavor.

kubernetesDeploy - Add option to replace instead of apply

---

resources/default_pipeline_environment.yml

removed pipelineConfigAndTests from the stashing after build (introduced in #3248)
In some cases end users include the `pipelineStashFilesAfterBuild` into their custom pipelines after the steps, where no `.pipeline` folder unstashed.

removed pipelineConfigAndTests from the stashing after build

---

pkg/orchestrator/jenkins.go
pkg/orchestrator/jenkins_test.go

> The multibranch pipeline jobs do posess the environment variable env.BRANCH_NAME which describes the branch. Use multibranch pipeline job type, not the plain pipeline job type. 
https://stackoverflow.com/a/43962998/1500953

fix: correct env var name for git branch for Jenkins orchestrator implementation

---

cmd/sonarExecuteScan.go
cmd/sonarExecuteScan_generated.go
resources/metadata/sonarExecuteScan.yaml

Somehow, either InfluxDB itself or the logic that writes values to it automatically casts .0 floats to integers. So, if you had 33.9% coverage, write a test and then have 35.0% coverage, one will write a float and the other an integer in Influx and that always fails with Type Mismatch.
This pull request removes the coverage metrics of SonarQube/SonarCloud from InfluxDB and only writes them to the sonarscan.json.

hotfix: Don't write SonarQube coverage metrics to InfluxDB

---

cmd/hadolintExecute_generated.go
resources/metadata/hadolintExecute.yaml

Use the [HaDoLint alpine image](https://hub.docker.com/r/hadolint/hadolint/tags) to cope with Vault certificate issue.

fix(hadolint): change docker image

---

documentation/docs/infrastructure/vault.md
pkg/config/config.go
pkg/config/vault.go
pkg/config/vault_test.go

- currently any additional vault credentials are fetched from vault based on test parameters `vaultTestCredentialPath` and `vaultTestCredentialKeys`
- with this change we additionally allow vault credentials be fetched with the new parameters `vaultCredentialPath` and `vaultCredentialKeys`
-  `vaultTestCredentialPath` and `vaultTestCredentialKeys` are also allowed for back compatibility but are marked deprecated in the documentation since the `vaultCredentialPath` and `vaultCredentialKeys` are general purpose and not only for additional test scopes.
- the new environment variable are by default appended with `PIPER_VAULTCREDENTIAL_` which can be overwritten with parameter  `vaultCredentialEnvPrefix`
- if overwritten we publish two environment variable with prefixe …

feat(vault): general purpose credentials from vault

---

cmd/cnbBuild.go
pkg/cnbutils/bindings/bindings.go
pkg/cnbutils/bindings/bindings_test.go
resources/metadata/cnbBuild.yaml

cnbBuild's `bindings` map now also supports `fromUrl` option, to fetch a binding content from a URL

feat(cnbBuild): support for fetching binding content from url

---

documentation/docs/guidedtour.md

Removes brackets that break two URLs.

fix(docs): wrongly formatted URLs in guidedtour.md

---

vars/whitesourceExecuteScan.groovy

Currrently `whiteSourceExecuteScan` has an declared `dockerConfigJsonCredentialsId` input, as well as it has corresponding `resourceRef` of type secret for the `dockerConfigJSON` property, however the credentials map passed to the `piperExecuteBin` doesn't contain it.

fix(whitesourceExecuteScan): added missing credential declaration for the docker config

---

cmd/cnbBuild.go
cmd/cnbBuild_test.go
pkg/cnbutils/auth.go
pkg/cnbutils/auth_test.go
pkg/cnbutils/bindings/bindings_test.go
pkg/cnbutils/buildpack_test.go
pkg/cnbutils/env_test.go
pkg/cnbutils/mock.go
pkg/cnbutils/order_test.go
pkg/cnbutils/project/descriptor_test.go
pkg/cnbutils/project/metadata/metadata_test.go
pkg/piperutils/FileUtils.go

In order to better isolate buildpacks processes from sensitive credentials, docker config.json file will be removed after parsing.

feat(cnbBuild): remove docker config after parsing

---

documentation/docs/infrastructure/vault.md
pkg/config/vault.go
pkg/npm/config.go
pkg/npm/config_test.go
pkg/npm/publish.go

Curently the `npmExecuteScripts` overwrites the registry parameter in `.npmrc` file if this file is present .  Rather than modifying a user provided .npmrc file we create a new npmrc file and use this during `npm publish`  
Since npmrc files need to contain the authentication for scoped dependencies from private registries , the vault general purpose credential feature is enhanced to expose a base64 encoded environment variable of the vault secret in addition to the vault secret env variable

feat (npmExecuteScripts) create seperate npmrc file for publish to private repo

---

cmd/cnbBuild.go
cmd/cnbBuild_test.go
pkg/mock/fileUtils.go
pkg/mock/fileUtils_test.go
pkg/piperutils/FileUtils.go
resources/default_pipeline_environment.yml

`cnbBuild` will create a symlink for the maven's `target` folder, pointing out to the jenkins workspace `target`, in order to preserve a maven test result for being able to publish it afterwards

feat(cnbBuild): preserve maven test results in the workspace

---

pkg/documentation/generator/parameters.go

vault paths in the documentation only considered the vault secret and vault secret files are marked without the vault indicators in the documentation. 
including condition for vault secret files as well.

fix (documentation) adding vault secret file to documentation generator   

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
cmd/init_unix.go
pkg/cnbutils/project/descriptor.go
pkg/cnbutils/project/descriptor_test.go
pkg/cnbutils/target_image.go
pkg/cnbutils/target_image_test.go
resources/metadata/cnbBuild.yaml

`cnbBuild` step will try to identify a containerImageName using the following precedence:
1. `containerImageName` parameter.
2. `project.id` field of a `project.toml` file.
3. `git/repository` parameter of the `commonPipelineEnvironment`.
If none of the above was found - an error will be raised.

feat(cnbBuild) containerImageName will be defaulted if possible

---

cmd/gctsDeploy.go

1. Added abap system client paramter to the endpoint for the configuration
2. Disabled retry mechanism during 500 response for create repository and deploy repository

Fix(gctsDeploy) : add client in config url, disable retry for create and pull 

---

cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_test.go

Lets collect the `deployTool` used in the `kubernetesDeploy` step as telemetry, in order to know when to deprecate helm 2 support.

chore(kubernetesDeploy): add telemetry for deployTool

---

cmd/mtaBuild.go

mtaBuild mtars are pushed into a maven like repo when `publish `is set to `true `, so the artifact name from the mta yaml can contain `.` which we replace with `-` to keep it in synch with the maven gav co-ordinate naming convention
EDIT: mtar can consist of dotted string, so in the final change we do not replace the dots , but keep it as it is

fix (mtaBuild) keep mtar artifact name in synch with maven gav

---

cmd/golangBuild.go
cmd/golangBuild_generated.go
cmd/golangBuild_test.go
go.mod
go.sum
pkg/certutils/certutils.go
pkg/goget/goget.go
pkg/goget/goget_test.go
resources/metadata/golangBuild.yaml

Partially solves [#3468](https://github.com/SAP/jenkins-library/issues/3468) and adds support for usage of private go modules.
* the user just has to provide the contents of the `GOPRIVATE` env variable via the newly introduced `PrivateModules` parameter
* `golangBuild` looks then into the package descriptor (go.mod file) and tries to resolve a list of all repositories for which authentication is required
* it makes sure the `GOPRIVATE` env var is set in the build context
* finally it tells `git` to authenticate all requests to these repositories
* `go.mod` file is expected to be in the root directory of the repository
* pipeline git credentials can be reused (private modules are hosted on the same git server, no other vcs are supported)
* does only work with token authentication at the …

feat(golangBuild): support private modules

---

documentation/docs/scenarios/abapEnvironmentAddons.md

Add limitation that table data is exported with generic keys for delivery

Add limitation that table keys are exported generically

---

cmd/kanikoExecute_generated.go
resources/metadata/kanikoExecute.yaml

Fixes #3448
```
10:42:26  warn  kanikoExecute - Couldn't create temporary secret file for 'dockerConfigJSON' - stat /tmp: no such file or directory
10:42:26  warn  kanikoExecute - Couldn't create temporary secret file for 'gcpJsonKeyFilePath' - stat /tmp: no such file or directory
```

fix(kanikoExecute): tmp dir

---

cmd/golangBuild.go
cmd/golangBuild_generated.go
cmd/golangBuild_test.go
resources/metadata/golangBuild.yaml

One may want to publish the binaries to a central repository. The `publish` flag was already there but not implemented.

feat(golangBuild): add support for publishing binaries

---

cmd/golangBuild.go
cmd/golangBuild_generated.go
cmd/golangBuild_test.go
resources/metadata/golangBuild.yaml

Automatically adds the artifact version (if available) to the filename of the generated binaries.

fix(golangBuild): keep track of the artifactversion in binary names

---

cmd/golangBuild.go
cmd/golangBuild_generated.go
cmd/golangBuild_test.go
resources/metadata/golangBuild.yaml

Reverts SAP/jenkins-library#3498
breaks existing scenarios. We need to re-consider the solution

Revert "fix(golangBuild): keep track of the artifactversion in binary names"

---

cmd/sonarExecuteScan.go
integration/integration_sonar_test.go
pkg/sonar/componentService.go
pkg/sonar/componentService_test.go
pkg/sonar/report.go
pkg/sonar/report_test.go
pkg/sonar/types.go

Add additional metrix from sonarqube to sonarscan.json:
1. add uncovered_lines,lines_to_cover,conditions_to_cover,uncovered_conditions so that weighted aggregations can be done for multiple sonar projects
2. add ncloc_language_distribution(Non Commenting Lines of Code Distributed By Language), ncloc (Non commenting lines of code) for language detection including distribution
3. consider branch in sonar componentService

sonarqube coverage: additional metrics

---

pkg/orchestrator/azureDevOps.go

Changes the value returned by getJobName() for azure to a more meaningful variable. Before
projectname -> gitOrganization/repositoryname.
Previously the project name was equal to the gitOrg. Therefore, we can not distinguish the projects.

Changes GetJobName value to repositoryname

---

cmd/detectExecuteScan.go

If the failOn variable for detect is set to NONE and policy violations are found we don't want the pipeline to fail. Anyways an error will be thrown. This behaviour is already documented.

[FIX] Ignore violations if failOn is NONE

---

cmd/abapEnvironmentBuild_test.go

Fix flaky test by ensuring order of items in list is ignored to address https://github.com/SAP/jenkins-library/runs/5105688736?check_suite_focus=true.

Fix test code

---

cmd/kanikoExecute.go
cmd/kanikoExecute_test.go

fixes regression introduced with #3443 which caused builds to fail where Dockerfile was referring to context in higher directory levels.

fix(kanikoExecute): use repository root as context

---

cmd/cloudFoundryDeploy.go
cmd/cloudFoundryDeploy_test.go

See #3531 
Bug was introduced with #3489
Nota bene: there is another potential bug: In case a password contains "a placeholder", e.g. `<% x %>` in lets say: `abc<% x %>123` this placeholder will be replaced in later iterations or it will be found as unresolved placeholder after all replacement are done. Should be adressed in another pull request ...

fix replacement of credentials placeholders in extension files for cf-deploy

---

cmd/kanikoExecute.go
cmd/kanikoExecute_generated.go
cmd/kanikoExecute_test.go
resources/metadata/kanikoExecute.yaml

Reverts SAP/jenkins-library#3542
It looks like piper isn't able to create tmp files when running inside of the kaniko executor image.
```
[2022-02-17T14:39:14.679Z] info  kanikoExecute - error pushing image: writing digest to file failed: open /286492770-kanikoExecute/digest.txt: no such file or directory
```

Revert "feat(kaniko): pass image digests to cpe"

---

pkg/orchestrator/orchestrator.go
pkg/telemetry/telemetry.go

This PR reduces the verbosity of piper.
* on jenkins it's not guaranteed that the GIT_* env vars are always set. It depends on the plugin which is used for cloning the repo (e.g. the Git plugin supports it, the github plugin does not). Since this is solely used for collecting telemetry data and thus not mission critical, we shouldn't consider this a `warning` but `debug` message.
```
17:34:22  warn  artifactPrepareVersion - Could not read env variable GIT_COMMIT using fallback value n/a
17:34:22  warn  artifactPrepareVersion - Could not read env variable GIT_URL using fallback value n/a
17:34:22  warn  artifactPrepareVersion - Could not read env variable GIT_URL using fallback value n/a
```

chore: noise reduction

---

cmd/golangBuild.go
cmd/golangBuild_test.go

Passes `-trimpath` by default to the go build in order to remove system paths from the compiled binaries. This flag was introduced with [Golang 1.13](https://go.dev/doc/go1.13) so I think it's okay to enforce it here.
```
goroutine 1 [running]:
...
main.startServer()
/home/jenkins/workspace/goproject/cmd/main.go:29 +0x1d
main.main()
/home/jenkins/workspace/goproject/cmd/main.go:24 +0x45
```
```
goroutine 1 [running]:
...
main.startServer()
./main.go:29 +0x1d
main.main()
./main.go:24 +0x45
```

fix(golangBuild): remove system paths from the compiled executables

---

cmd/fortifyExecuteScan_generated.go
pkg/config/stepmeta.go
pkg/documentation/generator/parameters.go
pkg/documentation/generator/parameters_test.go
pkg/generator/helper/helper.go
pkg/generator/helper/helper_test.go
pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden
resources/metadata/fortifyExecuteScan.yaml

this was already used in `fortifyExecuteScan`, but had no effect.
Deprecation will be shown in the documentation "Paramerters" > "Overview - Step" table > "Additional information" column and the parameter details.

feat: Add support for deprecating step parameters

---

cmd/kanikoExecute.go
cmd/kanikoExecute_generated.go
cmd/kanikoExecute_test.go
resources/metadata/kanikoExecute.yaml

Since we can't quickly fix the issues some users have on jenkins/jnlp, this PR deactivates the recently introduced docker digest feature by default and makes piper again compatible with kaniko 1.3.0

fix(kaniko): backwards compatibility with kaniko 1.3.0

---

cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_generated.go
cmd/kubernetesDeploy_test.go
resources/metadata/kubernetesDeploy.yaml

Added `valuesMapping` config option, which allows to pass Piper-provided values using custom values paths, e.g.:
```groovy
kubernetesDeploy(
script: this,
deployTool: "helm3",
valuesMapping: {
"subchart.image.tag":        "image.debug.tag",
"subchart.image.repository": "image.debug.repository",
"subchart.image.pullsecret": "secret.dockerconfigjson",
"mysidecar":                 "image.sidecar.gun",
}
)
```
**Important**: should be rebased and merged after https://github.com/SAP/jenkins-library/pull/3548 is closed

feat(kubernetesDeploy): added valuesMapping config option

---

cmd/containerSaveImage.go
cmd/containerSaveImage_generated.go
cmd/containerSaveImage_test.go
cmd/malwareExecuteScan.go
cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_test.go
resources/metadata/containerSaveImage.yaml

There's an issue with the `whitesourceExecuteScan` and the `malwareExecuteScan` steps. Both are not able to pull images from a staging repo in case some other registry credentials are configured in vault (via `docker-config/dockerConfigJSON`).
The RC is our understanding of the `DOCKER_CONFIG` env var. It should point to the directory which contains the docker configuration and not to the file itself.

fix(whitesourceExecuteScan): issue when dockerConfigJSON is set in vault

---

pkg/mock/fileUtils.go
pkg/mock/fileUtils_test.go
pkg/mock/runner.go
pkg/npm/config.go
pkg/npm/config_test.go
pkg/npm/ignore.go
pkg/npm/npm.go
pkg/npm/publish.go
pkg/npm/publish_test.go
pkg/piperutils/slices.go
pkg/piperutils/slices_test.go

Adding unit tests for the already existent publish logic used by `npmExecuteScripts` just to capture the status quo before I start fixing another issue with scoped packages.

chore(npmExecuteScripts): unit tests

---

pkg/mock/fileUtils.go
pkg/npm/config.go
pkg/npm/config_test.go
pkg/npm/publish.go
pkg/npm/publish_test.go
pkg/piperutils/FileUtils.go

Let's piper properly handle the new npmrc format (v2) and adds even more tests.

feat(npmExecuteScripts): config@2 support

---

cmd/whitesourceExecuteScan_generated.go
resources/metadata/whitesourceExecuteScan.yaml

supersedes #3168 since  branch has not been updated and thus cannot be merged

fix(whitesourceExecuteScan): orgToken from Vault

---

pkg/splunk/splunk.go

- Reduces the retries, sending telemetry information to Splunk to 1
- Uses correct hostName

fixes retry when sending telemetry to Splunk

---

cmd/kubernetesDeploy.go
cmd/kubernetesDeploy_generated.go
cmd/kubernetesDeploy_test.go
resources/metadata/kubernetesDeploy.yaml

* If `imageDigests` are set, the `tag` property will be updated to match `<tag>@<digest>` format

feat(kubernetesDeploy): support for image digests 

---

cmd/gitopsUpdateDeployment_generated.go
resources/metadata/gitopsUpdateDeployment.yaml

currently the step gitOpsUpdateDeployment only has jenkins references, extending `username` and `password ` for vault

fix (gitOpsUpdateDeployment) adding vault references for username and password

---

cmd/artifactPrepareVersion.go
cmd/artifactPrepareVersion_generated.go
cmd/artifactPrepareVersion_test.go
pkg/versioning/helm.go
pkg/versioning/helm_test.go
pkg/versioning/versioning.go
pkg/versioning/versioning_test.go
resources/metadata/artifactPrepareVersion.yaml

enhance the step artifactPrepareVersion with
- `buildTool: helm`
- version propagation capability (e.g. propagate application version to helm chart version)
closes #3413

feat(artifactPrepareVersion): helm & propagate version

---

pkg/config/stepmeta.go
pkg/config/stepmeta_test.go

This PR fixes an issue which got introduced with #3641 recently. It is causing issues with retrieving/publishing artifacts from/towards a registry. RC is a missing reference in the CPE.
Affected piper steps:
* golangBuild
* malwareExecuteScan
* whitesourceExecuteScan
* helmExecute
* kubernetesDeploy
* mtaBuild
* npmExecuteScripts
* mavenBuild

fix(cpe): breaking change introduced with #3641

---

cmd/golangBuild.go
cmd/golangBuild_test.go

As per https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies 
docs say the following order is required `go build [-o output] [build flags] [packages]`.
Currently,  `-ldflags` is put after packages and treated as a part of packages. e shall be put it before packages.
The build may fail this way
```
running command: go build -trimpath -o foo-linux.amd64 ./cmd/main.go -ldflags '-linkmode=external'
named files must be .go files: -ldflags
```

fix(golangBuild): order of arguments

---

cmd/kanikoExecute.go
cmd/kanikoExecute_test.go

After hours and hours of testing I figured out the root cause of the issue mentioned in #3652.
Some docker implementations don't like images produced with the `--reproducible` flag of kaniko, thus I'm deactivating it with this PR. Afaik empty layers (like CMD, ENV, etc) shouldn't appear in the manifest. But if the `--reproducible` flag is set, they do. 
This is how the `container-diff` tooling responded when I tried to pull an image with it.
```bash
failed to download Docker image alpine-base:3.15.1: failed to tar container image: image config had layer history which did not match the number of layers, got len(history)=3, len(layers)=4, want len(history)=len(layers)
```
Artifactory did just end with a weird error when I tried to push the image into a registry and did not provide any …

fix(kaniko): deactivate reproducible flag

---

cmd/whitesourceExecuteScan_generated.go
resources/metadata/whitesourceExecuteScan.yaml

this fixes issues when running WhiteSource for golang in a non-Kubernetes scenario.

fix(whitesourceExecuteScan): proper container options for golang

---

cmd/checkmarxExecuteScan.go

The current implementation fails if there are too many whitespaces used in the filterPattern, like:
```YAML
checkmarxExecuteScan:
filterPattern: '!a        , b'
```

fix(checkmarxExecuteScan): split and trim filterPattern

---

cmd/kubernetesDeploy_generated.go
resources/metadata/kubernetesDeploy.yaml

For `deployTool == "kubectl"` we still use tag `2.17.0` should we also bump this to `3.x`?
The 2.17 version contains a rather outdated kubectl and alpine version:
> - 3.8.0 - helm v3.8.0, kubectl v1.23.2, alpine 3.15
> - 3.4.1 - helm v3.4.1, kubectl v1.19.4, alpine 3.12
> - 2.17.0 - helm v2.17.0, kubectl v1.19.4, alpine 3.12
>
> source: https://hub.docker.com/r/dtzar/helm-kubectl

chore(kubernetesDeploy): bump docker image to helm 3.8.1

---

pkg/cnbutils/auth.go
pkg/cnbutils/auth_test.go

The authorisation used in `cnbBuild` also works if only `username` and `password` are present in the `config.json`.

feat(cnbBuild): Support of username/password authorization

---

cmd/checkmarxExecuteScan.go
cmd/checkmarxExecuteScan_generated.go
pkg/checkmarx/cxxml_to_sarif.go
pkg/checkmarx/cxxml_to_sarif_test.go
pkg/checkmarx/reporting.go
pkg/format/sarif.go
pkg/fortify/fpr_to_sarif.go
resources/metadata/checkmarxExecuteScan.yaml

- Added files cxxml_to_sarif.go and cxxml_to_sarif_test.go to package checkmarx
- Added new functions to read Checkmarx XML report, parse XML report into sarif, as well as a function to write the sarif file to disk (in reporting.go)
- Unit tests included
- End-to-end tests have been done with several test repos as well as 2 real-life projects, 1 test on JaaS and 1 test locally
- All new code is hidden behind the convertToSarif boolean feature flag (just as with Fortify)

feat(checkmarxExecuteScan): convert Checkmarx xml report to SARIF

---

.github/workflows/release-go.yml

Reverts SAP/jenkins-library#3703 as the release action uses the binary of the previous release which does not support this flag 🤬

Revert "chore(release): publish all binaries with one piper step"

---

documentation/docs/steps/cnbBuild.md

This PR documents the default excludes applied in `cnbBuild`. Maybe it would be good to add a  link to "Additional Hints" at the top of the [documentation](https://www.project-piper.io/steps/cnbBuild/).

Document default excludes

---

cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
documentation/docs/steps/cnbBuild.md
resources/metadata/cnbBuild.yaml

Since `nc` is no longer used as a workaround for tcp probes, we can switch to the `builder:base` as default.

chore(cnbbuild): Use builder:base instead of builder:full because `nc` is no longer needed

---

.github/CODEOWNERS

The CODEOWNERS file is now structured into the following sections:
- **Default**: assign all files to the jenkins-library-admin team.
- **Steps**: Assign steps to owners. This is done with two rules per step: `stepName*` and `StepName*`. Something like `[sS]tepName*` is not supported.
- **Integration tests**
- **Go packages**: The remaining go packages (not step or integration tests)
- **Misc** anything else, currently only the `CODEOWNERS` file itself.
- **Generated** generated code is explicitly assigned to nobody. In GitHub the last match in the CODEOWNERS file wins. Therefore this section is the last one.
Notice: The `piper-cnb` team does not yet exist in GitHub.
I used `piper-cnb` instead of `piper-cnb-build` because we might later contribute a `CnbRebase` step. I guess it is better …

add more codeowners

---

cmd/mtaBuild.go

Use full file path when trying to publish MTAR in `mtaBuild` step.
This should fix #3734.

fix(mtaBuild): Use correct file path when publishing MTAR

---

src/com/sap/piper/tools/neo/NeoCommandHelper.groovy
test/groovy/com/sap/piper/tools/neo/NeoCommandHelperTest.groovy
vars/neoDeploy.groovy

Dear colleagues,
the NEO cli supports the undocumented parameter `--az-distribution` which allows to control into which availability zone an application is deployed. This parameter is currently not usable with `neoDeploy` step of Piper but would be required for users of BTP NEO that want/need to run their applications on the longer-term available BTP NEO infrastructure.
This parameter is implicitly set by `neo deploy` and `neo rolling-update` commands to value `1` which is the original BTP NEO infrastructure on GMP. In order to switch to the longer-term available infrastructure in CC, the value would need to explicitly set to `2`. Also subsequent calls to `neo deploy` and `neo rolling-update` do make use of this defaulting and do not use the same availability zone assignment as the …

Added parameter to define availability zone for deploy/rolling-update

---

cmd/getDefaults.go
cmd/getDefaults_test.go
pkg/config/run.go

To enable stage conditions to be parsed properly as well.
Does it still make sense to keep the name of this command as `getDefaults`?

feat(getDefaults): add parameter for CRD-style config

---

cmd/golangBuild.go
cmd/golangBuild_generated.go
cmd/golangBuild_test.go
integration/docker_integration_test_executor.go
integration/integration_golang_test.go
integration/testdata/TestGolangIntegration/golang-project1/cmd/helper/helper.go
integration/testdata/TestGolangIntegration/golang-project1/go.mod
integration/testdata/TestGolangIntegration/golang-project2/go.mod
resources/metadata/golangBuild.yaml
vars/golangBuild.groovy

This PR fixes several bugs in the `golangBuild` step:
* When using a single package to build, the output binary name will be incorrect, if `config.Output` ends with a `os.PathSeparator` (`/` or `\`)
* When using multiple packages to build, the `-o` flag **MUST** be a directory (`go build` will produce a binary for each `main` package in the list and put it into the output directory)
* Added missing credentials handling for the private modules.

fix(golangBuild) properly handle multi-package builds

---

cmd/pythonBuild.go
cmd/pythonBuild_generated.go
cmd/pythonBuild_test.go
documentation/docs/steps/pythonBuild.md
documentation/mkdocs.yml
integration/integration_python_build_test.go
resources/metadata/pythonBuild.yaml

- before the build a virtual environment is created 
- the need to run the container with root user is eliminated with the virtual env
- all pip installs needed for cyclone dx and twine use this virutal env
- the virtual environment directory is deleted post build to keep the workspace clean

feat (pythonBuild) enable creation of a virtual environment (venv)

---

documentation/docs/scenarios/abapEnvironmentAddons.md

With Steampunk release 2202 current/previous commitID can be in different branches

Remove previous/current commitID in same branch

---

pkg/docker/docker.go

adjusting the go-containerregistry library to consider dots during registry url parsing by passing the parent base url as well . 
fixes #3668

fix (docker pull) pull image if repository name contains dots

---

cmd/artifactPrepareVersion.go
cmd/artifactPrepareVersion_test.go

Populating versions used new version as base instead of version as retrieved from build descriptor.
The fix addresses this problem.
In addition now also possible to propagate version for `library` versioning.

fix(versioning): correct propagated version

---

go.mod
pkg/checkmarx/cxxml_to_sarif.go
pkg/documentation/generator/main.go
pkg/fortify/fpr_to_sarif.go
pkg/generator/helper/helper.go
pkg/generator/helper/resources.go
pkg/piperutils/strings.go
pkg/piperutils/strings_test.go

Replace [`strings.Title`](https://pkg.go.dev/strings#Title) which is deprecated starting with go 1.18 with [`golang.org/x/text/cases.Title`](https://pkg.go.dev/golang.org/x/text@v0.3.7/cases#Title) as suggested by the go authors.

replace depreacted strings.Title function

---

cmd/malwareExecuteScan.go

The commit https://github.com/SAP/jenkins-library/commit/e6724d7f05f9f7b7a75b96904a487939efce1a91 introduced a new property called `ImageFormat` to the `containerSaveImageOptions` struct.
It also adapted steps such as `protecodeExecuteScan` and `whitesourceExecuteScan` to pass the `ImageFormat`.
However, the `malwareExecuteScan` has not been adapted.
With the latest release, the following happens in our pipelines:
```
[2022-05-19T16:03:04.983Z] + ./piper malwareExecuteScan --defaultConfig .pipeline/piper-defaults.yml,.pipeline/sapgraph-default.yml,.pipeline/sapgraph-monorepo.yml,.pipeline/sapgraph-release.yml,.pipeline/sapgraph-release-monorepo.yml --ignoreCustomDefaults
[2022-05-19T16:03:04.983Z] info  malwareExecuteScan - Using stageName 'Security' from env variable …
```

fix(malwareExecuteScan): Set ImageFormat to tarball

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
resources/metadata/cnbBuild.yaml

Currently the values for `helmDeploy` are derived from the content of `imageNames`. So an image named "my-image" would get the property `image.my_image.repository` when deploying. This might lead to some confusing situations because the name of the property has to be "guessed (s/-/_/g ...).
Also it is strange that the helm chart would have to be dependent on the name of the actual image.
Introducing this `alias` uncouples the names of the property and the actual image. If no `alias` is provided, the imageName is used.

cnbBuild: add alias for imageNames for easier valueMapping in helmDeploy

---

cmd/piper.go
documentation/docs/configuration.md
test/groovy/PiperExecuteBinTest.groovy
vars/piperExecuteBin.groovy

Change piperExecuteBin so that the parameter `ansServiceKeyCredentialsId `set in the hooks section will put that secret information into the environment variable `PIPER_ansServiceKey` for use in the steps.

[ANS] Add servicekey credential to environment

---

.github/workflows/documentation.yaml

This PR updates the version used for mkdocs to 8.3.6.
#3839

fix(docs): update mkdocs docker container version

---

documentation/docs/configuration.md
pkg/log/ansHook.go
pkg/log/ansHook_test.go

Changes the ANS (SAP Alert Notification Service) tag prefixes to _cicd_ instead of  the current _pipeline_.

Change pipeline prefix to pipeline

---

documentation/mkdocs.yml

Changes to update Python markdown extension needed for mkdocs
Fixes https://github.com/SAP/jenkins-library/issues/3839
Tested by forking repo

fix : update mkdocs.yml

---

cmd/pythonBuild.go
cmd/pythonBuild_test.go

Use `twine` in a more CI-friendly way by disabling the progress bar during the upload of a Python package.
At the moment the logs of the `pythonBuild` step look like this, the proposed changes would get rid of the progress bar clutter:
```
info  pythonBuild - Uploading distributions to https://staging.repositories.cloud.sap/stage/reposito
info  pythonBuild - ry/c31a08838081-20220627-142634877-819/
info  pythonBuild - Uploading spotlight_otr_service-1.2.0.20220627142627+493cb2332cfd7b8c8889ca4b9fd
info  pythonBuild - 2b3ac9f7d991c-py3-none-any.whl
info  pythonBuild - 25l
0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/31.1 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.1/31.1 kB • 00:00 • 79.3 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.1/31.1 kB • 00:00 • 79.3 …
```

fix(pythonBuild): Disable progress bar during twine upload

---

cmd/fortifyExecuteScan.go
pkg/fortify/fpr_to_sarif.go
pkg/fortify/fpr_to_sarif_test.go

- "project" parameter was unneeded in the code, removed, unit tests adapted
- ruleID in rules still used kingdom, removed

fix(fortifyExecuteScan): remove unneeded parameter (project), fix rule ID in rules

---

pkg/kubernetes/helm.go
pkg/kubernetes/helm_test.go

helm lint command takes into account value files provided via ```helmValues``` parameter

helmExecute: helm lint command takes into account value files provided via helmValues parameter 

---

cmd/abapAddonAssemblyKitCheckCVs_test.go
cmd/abapAddonAssemblyKitCheckPV_test.go
cmd/abapAddonAssemblyKitCreateTargetVector_test.go
cmd/abapAddonAssemblyKitRegisterPackages.go
cmd/abapAddonAssemblyKitRegisterPackages_test.go
cmd/abapAddonAssemblyKitReleasePackages.go
cmd/abapAddonAssemblyKitReleasePackages_test.go
cmd/abapAddonAssemblyKitReserveNextPackages_test.go
cmd/abapEnvironmentAssembleConfirm.go
cmd/abapEnvironmentAssemblePackages.go
cmd/abapEnvironmentBuild.go
cmd/abapEnvironmentBuild_test.go
cmd/abapEnvironmentCheckoutBranch.go
cmd/abapEnvironmentCheckoutBranch_test.go
cmd/abapEnvironmentCloneGitRepo.go
cmd/abapEnvironmentCloneGitRepo_test.go
cmd/abapEnvironmentCreateSystem.go
cmd/abapEnvironmentCreateTag.go
cmd/abapEnvironmentCreateTag_test.go
cmd/abapEnvironmentPullGitRepo.go
cmd/abapEnvironmentPullGitRepo_test.go
cmd/abapEnvironmentPushATCSystemConfig.go
cmd/abapEnvironmentRunATCCheck.go
cmd/abapEnvironmentRunATCCheck_test.go
cmd/abapEnvironmentRunAUnitTest.go
cmd/abapEnvironmentRunAUnitTest_test.go

I cleaned up issues found by golangci-lint
When looking through the code it seems like there are physical files created during tests. In some places it seems like even outside of a temporary file system.
Maybe this could be cleaned up by using the virtual filesystem we are using in many other steps.
The file creation outside of a temporary directory should in all cases be fixed in my opinion.

chore: cleanup linting issues in abap steps

---

cmd/detectExecuteScan.go
cmd/detectExecuteScan_generated.go
cmd/detectExecuteScan_test.go
cmd/protecodeExecuteScan.go
cmd/protecodeExecuteScan_generated.go
cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_generated.go
cmd/whitesourceExecuteScan_test.go
resources/metadata/detectExecuteScan.yaml
resources/metadata/protecodeExecuteScan.yaml
resources/metadata/whitesourceExecuteScan.yaml

For running open source vulnerability scans in de-coupled processes
it is helpful to allow that steps only create
compliance reports to inform users/teams
but not fail the pipeline.
This can now be achieved constitently with the flag:
`failOnSevereVulnerabilities`

feat: allow OSVM scans to succeed with vulnerabilities

---

cmd/kanikoExecute.go
cmd/kanikoExecute_generated.go
cmd/kanikoExecute_test.go
resources/metadata/kanikoExecute.yaml

pull #3875 allowed writing vault files to a tmp directory. this caused an issue with kanikoExecute where the vault files overwrote the docker config json file , thus causing permission denied error. 
with this change we enhance the docker config if it comes from vault or create a new one with the registry credentials
fixes #3891

fix (kanikoExecute) enhance existing docker config json with additional credential params : user, password and registry Url 

---

pkg/checkmarx/cxxml_to_sarif.go
pkg/checkmarx/cxxml_to_sarif_test.go
pkg/format/sarif.go
pkg/fortify/fortify.go
pkg/fortify/fpr_to_sarif.go
pkg/fortify/fpr_to_sarif_test.go

Various changes for Fortify & Checkmarx SARIF:
- classify findings into audit requirement groups (internal policy)
- common properties bag for both tools (although accepting the fact that some will be empty, requested by internal analytical constraints)
- enhance additional tests for both tools, add some new checks for Checkmarx

Classify Fortify & Checkmarx findings into audit group / Common properties  

---

integration/integration_cnb_test.go
integration/testdata/TestCnbIntegration/project/project-with-id.toml
integration/testdata/TestCnbIntegration/project/project.toml

To mitigate the rate limits on the buildpacks registry side, all integration tests now use the url for buildpack and only one test looks up one buildpack by id.

fix(cnbBuild): use a single test case to lookup buildpacks by ID

---

pkg/npm/npm.go
pkg/npm/npm_test.go

Adding `false` does not what is intended. If the parameters are added to the call, license texts and dev dependencies are included

Cleanup of SBOM generation parameters

---

resources/default_pipeline_environment.yml

While running the pipeline on JFR, the dist folder created during the build stage is not stashed properly and hence, not handed over to `transportRequestUploadCTS` step to perform deployment to abap system. This PR change will resolve the issue.

Add dist folder into build result

---

pkg/checkmarx/reporting.go
pkg/checkmarx/reporting_test.go

This change aims to fix the inconsistent logic in calculating Low/Info audited numbers for reporting (expected logic is the one used in _enforceThresholds()_ ).

fix(checkmarx): inconsistent logic in calculating Low/Info audited numbers

---

cmd/golangBuild.go

We are using golangci-lint version v1.46.2 and we started getting errors:
```21:34:08  debug golangBuild - --------------------------------
21:34:08  info  golangBuild - running command: ./install.sh -b /go/bin v1.46.2
21:34:08  info  golangBuild - golangci/golangci-lint info checking GitHub for tag 'v1.46.2'
21:34:09  info  golangBuild - golangci/golangci-lint info found version: 1.46.2 for v1.46.2/linux/amd64
21:34:11  info  golangBuild - golangci/golangci-lint info installed /go/bin/golangci-lint
21:34:11  info  golangBuild - running command: /go/bin/golangci-lint run --out-format checkstyle
21:34:18  info  golangBuild - panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
21:34:18  info  golangBuild - 
21:34:18  info  golangBuild - goroutine 1 [running]:
21:34:18 …
```

golangBuild: update golangci-lint version

---

cmd/transportRequestUploadCTS_generated.go
resources/metadata/transportRequestUploadCTS.yaml

To be able to set the transportRequestId for the `transportRequestUploadCTS` step when used in the `piperPipelineStageRelease` step we want to set it via config.yaml

Allow transport request id from config

---

cmd/cnbBuild.go

If you have configured a [custom builder](https://www.project-piper.io/steps/cnbBuild/#dockerimage) make sure it supports the [CNB Platform API 0.9](https://github.com/buildpacks/spec/releases/tag/platform%2Fv0.9) (previously 0.8 was required). This can be done be upgrading your builder to the lifecycle 0.14.x in the [builder.toml](https://buildpacks.io/docs/reference/config/builder-config/#lifecycle-_optional_)

cnbBuild: bump platform api version to 0.9 [breaking]

---

go.mod
go.sum

PR #3959 upgraded x/crypto version however: 
https://cs.opensource.google/go/x/crypto/+/5d542ad81a58c89581d596f49d0ba5d435481bcf 
with the newer version of x/crypto there seems to a algorithm mismatch with what x/crypto/ssh uses and what some github instances support 
most like recent version of openSSH removed support for SHA1 key signing , but some github instances may still expect SHA1 (till the time such instances don't remove SHA1 support), the mistmatch can cause handshake failure during authentication, so downgrading the x/crypto version .

fix(ssh auth) downgrade x/crypto to allow ssh auth with all git instances 

---

pkg/kubernetes/helm.go
pkg/kubernetes/helm_test.go

This PR changes permissions for downloaded dependency. 
```helmExecute``` runs docker container (dtzar/helm-kubectl:3.8.0) with ```-u 0``` (because, for example, ```helm dependency update``` tries to read and write files to ```./root/.cache/helm/repository``` in the container).
Dependency is being downloaded to the ```charts``` folder with permissions ```drwxr-xr-x root root```.
Jenkins can’t clean up the workspace - operation not permitted.
```
Error when executing cleanup post condition:
Also:   java.nio.file.FileSystemException: /var/jenkins_home/workspace/uild-helm-with-dependency-5_main/helm/azure-demo-k8s-go/charts/nginx-13.1.6.tgz: Operation not permitted
...
Also:   java.nio.file.FileSystemException: /var/jenkins_home/workspace/uild-helm-with-dependency-5_main/helm/azure-demo-k8s-g …
```

helmExecute: change permissions for downloaded dependency

---

cmd/helmExecute.go

Currently the `helmExecute` step picks a wrong `Chart.yaml` file, if the main helm charts has a nested folder where another `Chart.yaml` file is present.

fix(helmExecute): explicitly set buildDescriptorFile if the chartPath is configured

---

pkg/orchestrator/jenkins.go
pkg/orchestrator/jenkins_test.go

The `_class` field of the objects in the actions array is not always populated, like in this example (notice the `CauseAction` is only the 2nd entry):
```json
{
"_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
"actions": [
{},
{
"_class": "hudson.model.CauseAction",
"causes": [
{
"_class": "hudson.model.Cause$UserIdCause",
"shortDescription": "Started by user John Doe",
"userId": "d012345",
"userName": "John Doe"
},
{
"_class": "org.jenkinsci.plugins.workflow.cps.replay.ReplayCause",
"shortDescription": "Replayed #1"
}
]
},
{
"_class": "jenkins.scm.api.SCMRevisionAction"
}
]
}
```
I have no idea why this happens, but it causes the `GetBuildReason` method to panic. This PR fixes this by ignoring any actions without class.
Log:
```
14:58:12  panic: interface conversion: interface …
```

fix(JenkinsConfigProvider): panic in GetBuildReason

---

pkg/npm/npm.go
pkg/npm/npm_test.go

@cyclonedx/bom removed the executable from major version 4 which does not allow a bom creation from version 4. this is a breaking change see : https://github.com/CycloneDX/cyclonedx-node-module/issues/343
currently pinning the version to @cyclonedx/bom@^3.10.6 ,
in the long run we must think about moving to https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm instead

fix (npmExecuteScripts) pinning @cyclonedx/bom to major version 3

---

cmd/gradleExecuteBuild.go
cmd/gradleExecuteBuild_generated.go
cmd/gradleExecuteBuild_test.go
resources/metadata/gradleExecuteBuild.yaml

PR adds the possibility to get and write to CPE published artifacts names for later usage (for downloading artifacts).

gradleExecuteBuild: get published artifacts names and write those to CPE

---

cmd/cnbBuild_test.go
pkg/cnbutils/project/descriptor.go
pkg/cnbutils/project/descriptor_test.go

Adding something like this to the `project.toml`:
```toml
[[build.env]]
name="BP_NODE_RUN_SCRIPTS"
value=""
```
is silently ignored by `cnbBuild (it works in pack).
We should fix this.

fix(cnbBuild): allow setting empty env variables in project descriptor

---

pkg/sonar/componentService.go
pkg/sonar/issueService.go

This PR fixes building the URL to call sonar API.
If there is a PR then `sonarExecuteScan` gets the results of the completed evaluation of the project from the PR branch, if no - from `branchName`
Issues:
fixes [#3994](https://github.com/SAP/jenkins-library/issues/3994)
#4585 (inner-souce)

sonarExecuteScan: fix building the URL to call sonar API

---

cmd/kanikoExecute.go
cmd/kanikoExecute_generated.go
cmd/kanikoExecute_test.go
resources/metadata/kanikoExecute.yaml

This PR takes care of installing [Syft](https://github.com/anchore/syft) and running it as part of kanikoExecute step.
The SBOM is generated in `cyclonedx-xml` supported by Syft  conforming to the [CycloneDX 1.4 specification](https://cyclonedx.org/specification/overview/)
The generated sbom file name will be bom-docker.xml for Single image Kaniko build or bom-docker-(1/2/3....) for multi image kaniko build.
Unit test changes:
- Renamed variable 'runner' to 'execRunner' , as a new variable 'shellRunner' is now present.
- Success case UT s for single image and multi image 
- Negative use case UTs for single image - Download,installation and syft run failures

Introducing syft to generate SBOMS for kaniko builds

---

resources/metadata/artifactPrepareVersion.yaml

This PR updates the documentation for the `artifactPrepareVersion` step.
When a helm chart contains a nested chart(s), the `additionalTargetDescriptors` parameter needs to be set explicitly.

artifactPrepareVersion: update documentation

---

cmd/kanikoExecute.go
cmd/kanikoExecute_test.go

This PR intends to change the way Syft is installed in Piper as it is better to rely on a release binary than a shell script.
As part of #4093 , syft was installed using a Shell script .
The release of syft is pinned to 60.3 which is the latest version available. Tested with this release and looks good.

Syft install using binary instead of shell script

---

cmd/kanikoExecute_test.go
pkg/whitesource/whitesource.go

fixes #4110 
receiver functions had an incorrect pointer that cause the below error :
`panic: reflect.Set: value of type whitesource.Alert is not assignable to type reporting.IssueDetail`

fix (whitesourceExecuteScan) correct type cast for receiver functions tomarkdown() and title()

---

cmd/kanikoExecute.go
documentation/docs/steps/cnbBuild.md

#4116 installs Syft by shell script. Instead of `&&`, `&` (execute in parallel) is used, introducing a race condition. In pipelines, the step will sometimes fail:
```
info  kanikoExecute - running shell script: /busybox/sh mkdir Syft & tar -zxvf syftBinary.tar.gz -C Syft
info  kanikoExecute - tar: can't change directory to 'Syft': No such file or directory
```

Fix race condition in kanikoExecute

---

cmd/checkmarxExecuteScan.go
cmd/checkmarxExecuteScan_test.go

This PR allows Piper to fail early and with a clear error message if no projectName was provided (mandatory parameter).

fix(checkmarxExecuteScan): Fail with clear error message if no projectName

---

pkg/kubernetes/helm.go
pkg/kubernetes/helm_test.go

When publishing a helm chart under the subfolder, it's not possible to use it as a dependency in the `Chart.yaml`, since the registry's `index.yaml` doesn't include the subfolder in the url to the chart's tarball, resulting in a 404 error during a `helm dependency update`.

fix(helmExecute): do not publish helm charts under subfolders

---

cmd/kanikoExecute.go
cmd/kanikoExecute_generated.go
resources/metadata/kanikoExecute.yaml

This PR introduces Syft PR as a parameter to kanikoExecute step . This was mainly required so as to ease the up gradation to a major release if needed in future.

Expose syft url as a parameter for kanikoExecute

---

.github/workflows/integration-tests-pr.yml
.github/workflows/integration-tests.yml

The sha from the `start` step is accessed here:
https://github.com/SAP/jenkins-library/blob/b7468e81aa27e04470c736a5c9f2423abd2d2678/.github/workflows/integration-tests-pr.yml#L129-L131
I looks like github actions fail silently here: As `needs.start` does not exist, `${{ needs.start.outputs.sha }}` evaluates to an empty string and the `checkout`  action seems to default to the `master` branch in that case.
Which means during the integration tests it uses the "new" code (productive and test code) with the "old" test asset files.

fix ci: missing needs in github action yaml

---

test/groovy/MailSendNotificationTest.groovy
vars/mailSendNotification.groovy

Added check if previous build exists, before verifying recovery status

fix(mailSendNotification): do not send recovery notifications on first build

---

pkg/fortify/fortify.go
pkg/fortify/fortify_test.go

The fix will solve the issue of getting the project version.  
**Example**:  the query _name:1.60_ does not work, but _name:"1.60"_ works.
As the version name is of type string we should consider it as a string in the query.

fix(fortifyExecuteScan): fix project versions api call

---

go.mod
go.sum
pkg/versioning/jsonfile.go

This PR adds the possibility to work with package.json (gets/sets version field) without changing the ordering.
In some cases ordering is significant.
See inner-source issue #4657
(!!!) PR adds usage of the new `github.com/iancoleman/orderedmap` package

`artifactPrepareVersion` doesn’t change the order of entries in the package.json

---

pkg/checkmarx/checkmarx.go
pkg/checkmarx/checkmarx_test.go

Use new Checkmarx APIs to poll the status of the branching before scanning.
If the branching is not completed and Piper starts the scan, it will fail with an error like `The scan's project is either temporarily inactive or deleted.` or `scan canceled`

fix(checkmarx) Improve project branching process

---

cmd/checkmarxExecuteScan.go

Sometimes, the incremental scans in Checkmarx will fail because the last full scan is not consistent.
This PR is adding an auto-healing feature that is triggering a full scan if the last incremental scan failed.

feat(checkmarx) Launch full scan if the last incremental scan failed

---

.github/workflows/consumer-tests-pr.yml
.github/workflows/integration-tests-pr.yml
.github/workflows/integration-tests.yml

Use the new way of producing outputs in a GitHub action as the old way is deprecated and will be removed (on 31st May 2023).
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

chore(GitHub actions): update deprecated output syntax

---

pkg/npm/publish.go
pkg/npm/publish_test.go

See https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/
where it states :the presence of auth related settings that are not scoped to a specific registry found in a config file is no longer supported and will throw errors

fix (npmExecuteScripts) fix for npmrc _auth

---

pkg/orchestrator/gitHubActions.go

`sonarExecuteScan` in GHActions considers the non-PR branch as a pull request.
It is happening because the `isPullRequest` function checks if `GITHUB_HEAD_REF` env var exists and if yes —> it is a PR. And indeed, env var exists, but the value is ‘’, and the length is 0, and it is not a PR.
This PR adds usage of the `truthy` function from the `orchestrator` package, it checks that env var exists and makes additional checks (e.g. length greater than zero).
https://github.com/SAP/jenkins-library/blob/f3c1bf6edc899a88806a4b65cefae70affae0d00/pkg/orchestrator/orchestrator.go#L100-L111

fix(orchestrator): determine if it is a pull request (GH Actions)

---

cmd/kubernetesDeploy.go

Using '-' in `imageNameAlias` and using it in the `ValuesMapping` caused problems due to the missing escaping.

fix(kubernetesDeploy): Escape imageAliases in valueMapping

---

cmd/codeqlExecuteScan.go

When language is set in config.yml there will be two --language flags in 'codeql database create' command. For example, .pipeline/config.yml:
```
codeqlExecuteStep: 
language: 'java' 
...
```
running command:
`codeql database create codeqlDB --overwrite --source-root ./ --language=java --language=java`

fix(codeqlExecuteScan): fixed duplication of '--language' flag

---

pkg/orchestrator/gitHubActions.go
pkg/orchestrator/gitHubActions_test.go

To get the PR number the sonarExecuteScan relies on the orchestrator package. The orchestrator package reads env var GITHUB_EVENT_PULL_REQUEST_NUMBER. There is no mention of GITHUB_EVENT_PULL_REQUEST_NUMBER in the GitHub documentation anymore.
The list of default env vars: https://docs.github.com/en/enterprise-server@3.6/actions/learn-github-actions/variables#default-environment-variables.
The env var GITHUB_EVENT_PULL_REQUEST_NUMBER doesn’t exist --> the orchestrator package returns n/a, which is not good.
The PR fixes this behavior:

Orchestrator/GHActions: fix pr-number determination

---

cmd/mtaBuild.go
test/groovy/templates/PiperPipelineStageInitTest.groovy
vars/piperPipelineStageInit.groovy

This change utilizes the  functionality of dynamic creation of `mta.yaml` file during `mtaBuild` step  if that file does not exist beforehand. Currently,it is not possible with `buildTool` set to `mta` because of initial failure at `piperPipelineStageInit` step.

Fix mta buildtool error

---

vars/dockerExecuteOnKubernetes.groovy

Inside `dockerExecuteOnKubernetes` there is a default stash created for stashing the workspace into a pod. This default stash is only provided in case no stashes are explicitly provided. But also when there is no default stash use (... since we have explicit stashes), the default stash is invalidated.

feat(kubernetes): invalidate default stash only if it has been created

---

vars/dockerExecuteOnKubernetes.groovy

Sometimes it is beneficial to know which file are available in a pod.
When verbose mode is enable we list the first two levels of the current dir.
In case the `find` command is not present in the container, the build status and the stage status will remain unchanged (e.g. build does not fail in that case).

log the first two level of the file system in verbose mode

---

vars/dockerExecuteOnKubernetes.groovy

With #4293 the body closure is not the last statement which gets executed. With that the return value of the call method changed (transitively via `executeOnPod`.
This change in the behaviour is fixed with this change.

dockerExecuteOnKubernetes: return result of body closure

---

integration/integration_cnb_test.go
integration/testdata/TestCnbIntegration/config.yml
pkg/cnbutils/bindings/bindings.go
pkg/cnbutils/bindings/bindings_test.go
pkg/config/vault.go
pkg/config/vault_test.go
resources/metadata/cnbBuild.yaml

Binding content can now be provided via [Vault general purpose secrets](https://www.project-piper.io/infrastructure/vault/#using-vault-for-general-purpose-and-test-credentials)

feat(cnbBuild): support Vault general purpose secrets as a binding content source

---

cmd/cnbBuild_test.go
pkg/cnbutils/privacy/privacy.go
pkg/cnbutils/privacy/privacy_test.go

Instead of hardcoding `<redacted>` string in telemetry, use SHA256 hashed strings.

feat(cnbBuild): use SHA256 hashed values for redacted telemetry properties

---

cmd/integrationArtifactGetServiceEndpoint.go

In our tests often `integrationArtifactGetServiceEndpoint` fails with
```sh
info  integrationArtifactGetServiceEndpoint - [DEBUG] GET https://<address>/api/v1/ServiceEndpoints?$expand=EntryPoints
error integrationArtifactGetServiceEndpoint - a HTTP error occurred! Response body: , Response status code: 200
```
The reason is:
For some reason the "iflowID" (derived from the result.Name) [does not match](https://github.com/SAP/jenkins-library/blob/master/cmd/integrationArtifactGetServiceEndpoint.go#L77) the "config.IntegrationFlowID". Therefore it does not [return here](https://github.com/SAP/jenkins-library/blob/master/cmd/integrationArtifactGetServiceEndpoint.go#L81).
Then the [body is read](https://github.com/SAP/jenkins-library/blob/master/cmd/integrationArtifactGetServiceEndpoint.go#L85) …

Improve error message for integrationArtifactGetServiceEndpoint

---

src/com/sap/piper/DockerUtils.groovy
test/groovy/ContainerPushToRegistryTest.groovy
test/groovy/com/sap/piper/DockerUtilsTest.groovy

This PR solves the #4857 inner-source issue.
The PR adds --multi-arch=all to the skopeo copy command.
--multi-arch=all: copy the full multi-architecture image

feat(containerPushToRegistry): add new --multi-arch=all flag to skopeo

---

cmd/helmExecute.go
cmd/helmExecute_generated.go
pkg/piperenv/templating.go
pkg/piperenv/templating_test.go
resources/metadata/helmExecute.yaml

Allow custom delimiter for go templating in case the values.yaml file already contain templates that are meant to be resolved by `helm` and not piper (see unit test for an example).

feat(helmExecute): Allow custom delimiter

---

cmd/pythonBuild.go
cmd/pythonBuild_test.go
integration/integration_python_test.go

1. Pin Python package for cyclonedx 
2. Replace cyclonedx-bom with [cyclonedx-py](https://github.com/CycloneDX/cyclonedx-python#installation) as it is deprecated
`info  pythonBuild - 
warn  pythonBuild - !!! DEPRECATION WARNING !!!
info  pythonBuild - ! The used call method "cyclonedx-bom" is deprecated.
info  pythonBuild - ! Use "cyclonedx-py" instead.`

fix(Python): Pin version of cyclonedx package for python builds

---

cmd/whitesourceExecuteScan_generated.go
resources/metadata/whitesourceExecuteScan.yaml

This change aims to add checkmarxOne as stash content for whiteSourceExecuteScan step.

fix(whitesource):add stash for checkmarxOne

---

cmd/codeqlExecuteScan.go
pkg/codeql/codeql.go
pkg/codeql/codeql_test.go

fix(codeqlExecuteScan): pagination call for getting codescanning results

---

cmd/codeqlExecuteScan.go
cmd/codeqlExecuteScan_test.go
pkg/codeql/codeql.go
pkg/codeql/codeql_test.go

fix(codeqlExecuteScan): fixed the logic for getting scanning alerts

---

cmd/npmExecuteLint.go

Pure refactoring. Until now we had the call to `npx eslint` twice, but with only one parameter which was different. Now we set the parameter accordingly and invoke `npx eslint` only at one place in the code. That makes understanding the code a little bit easier.

[refactor] avoid code duplication when invoking eslint

---

cmd/npmExecuteLint.go
cmd/npmExecuteLint_generated.go
cmd/npmExecuteLint_test.go
resources/metadata/npmExecuteLint.yaml

Up to now
- we support only output format `checkstyle`
- we redirect the lint results into a log file
With this change
- we support several output formats, default is `checkstyle`
- we provide the option to write the lint results to the log instead to a file. By default the log will still be redirected to a file with the same pattern as before.
How can this change be tested?
- build the `piper` binary (`go build -o piper -tags release`)
- invoke the piper binary on a suitable test project:
```
./piper npmExecuteLint --failOnError --outputFormat stylish --outputFileName ""
```
prints the same logs to the console like BAS does.
```
./piper npmExecuteLint --failOnError --outputFormat checkstyle --outputFileName ""
```
prints the checkstyle format to console.
When `outputFileName` is omitted …

Adjust npmExecuteLint (output-format, print output to console)

---

cmd/detectExecuteScan.go

The issue of failing pipeline in case of license policy volations if the failOn parametr doesn't contain "CRITICAL" value has been fixed by this PR.
Before: pipeline failed with failon Blocker for license violation (CRITICAL level)
Expected behavior: Should only fail if failon CRITICAL

fix(detectExecuteScan): Fix license incorrect fail with FailOn parameter for blackduck

---

cmd/mavenBuild.go

By setting the `stepName` in the `Command` struct of the `utils`, the URL log generation is activated. This is done for all build tools, see for example this line of [golangBuild](https://github.com/SAP/jenkins-library/blob/master/cmd/golangBuild.go#L99).
The `maven.NewUtilsBundle()` function that mavenBuild uses however is shared by multiple steps, and for the others we don't want to generate the URL log, so I used reflection to change the value only in this step.

fix(url-logger): Enable access log generation for mavenBuild

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
integration/integration_cnb_test.go
integration/testdata/TestCnbIntegration/.pipeline/commonPipelineEnvironment/custom/dockerConfigJSON
integration/testdata/TestCnbIntegration/.pipeline/config.json
integration/testdata/TestCnbIntegration/config.yml
pkg/docker/docker.go
pkg/docker/docker_test.go
resources/metadata/cnbBuild.yaml

This change also removes recently (1 day ago) introduced username and password properties, since we observed scenarios where it leads to incorrectly mapped credentials and therefore broken config.json file (username, registry & password are present in CPE, with the user provided registry + `dockerConfigJSON` in `config.yaml`).

fix(cnbBuild): read dockerConfigJSON from CPE and merge it with user-provided

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
go.mod
go.sum
integration/github_actions_integration_test_list.yml
integration/integration_cnb_test.go
integration/testdata/TestCnbIntegration/config.yml
integration/testdata/TestCnbIntegration/project/package.json
pkg/cnbutils/buildpack.go
pkg/cnbutils/buildpack_test.go
pkg/cnbutils/order.go
pkg/cnbutils/order_test.go
pkg/cnbutils/project/descriptor.go
pkg/cnbutils/project/descriptor_test.go
pkg/cnbutils/project/metadata/metadata.go
pkg/cnbutils/project/metadata/metadata_test.go
pkg/cnbutils/project/types/types.go
pkg/cnbutils/project/v01/project.go
pkg/cnbutils/project/v02/project.go
pkg/cnbutils/report.go
pkg/cnbutils/report_test.go
pkg/mock/dockerClient.go
resources/metadata/cnbBuild.yaml

feat(cnbBuild) Add support for pre and post-buildpacks

---

.github/workflows/verify-go.yml
integration/integration_gauge_test.go

Since PR cannot access github action secrets, separating the workflows for unit test and code coverage steps
replaces #4451

fix(ci): add conditional coverage upload to CodeClimate 

---

cmd/golangBuild.go
cmd/golangBuild_test.go
integration/integration_golang_test.go

Pinning to latest stable version :https://github.com/CycloneDX/cyclonedx-gomod/releases/tag/v1.4.0
We missed to pin here #4368

Pin version of golang BOM to 1.4.0

---

pkg/kubernetes/helm.go
pkg/kubernetes/helm_test.go

#4374 broke `helmExecute` if `AdditionalParameters` contained a blank

fix(helmExecute) allow blanks in AdditionalParams again

---

pkg/config/vault.go

With normal log level, only `01:25:49  info  githubCreateIssue - Fetching secrets from Vault at https://vault.../` is printed to the log. It would be interesting to see which parameters have actually been resolved without going into verbose mode.

chore(logs): print parameters resolved from vault with info level

---

cmd/kanikoExecute.go

Adds some verbose logging of the Kaniko command using the [general `verbose` parameter](https://github.com/SAP/jenkins-library/blob/master/cmd/piper.go#L36).

feat(kaniko): Add optional verbose logging for kaniko command

---

cmd/checkIfStepActive.go
pkg/config/evaluation.go
pkg/config/evaluation_test.go
pkg/config/run.go
pkg/config/run_test.go

In piper-stage-config.yml file there should be one more notActiveCondition for this feature to work. Example:
```yaml
spec:
stages:
- name: integration
steps:
- name: sapCumulusUpload
description: 'Performs upload of result files of the previous steps of this stage to Cumulus.'
conditions:
- configKey: pipelineId
notActiveConditions:
- onlyActiveStepInStage: true
```
In general, this condition says that step will be deactivated if all the previous steps are inactive

sapCumulusUpload step deactivation if its the only active step in stage

---

cmd/kanikoExecute_generated.go
resources/metadata/kanikoExecute.yaml

kanikoExecute.multipleImages is not supposed to be configured from STAGES scope. 
one of our users encountered a regression using latest (master) Piper version.

fix(kanikoExecute): remove STAGES scope from multipleImages param

---

cmd/helmExecute_generated.go
resources/metadata/helmExecute.yaml
test/groovy/BuildExecuteTest.groovy
vars/buildExecute.groovy

With this it is possible to e.g. perform a `helm dependency: update` at end of the build phase.
Since the `chartPath` is also used e.g. by `kubernetesDeploy` which is typically used in another stage it makes sense to define the `chartPath` in the `general´ section so that it can be shared. Hence we add also that.

helmExecute triggered by  buildExecute

---

cmd/githubPublishRelease.go
cmd/githubPublishRelease_test.go

Github requests should be executed with pagination to fetch all objects.
This PR fixes a bug when githubPublishRelease didn't mention all the closed issues and PRs.

fix(githubPublishRelease): ListByRepo - enable pagination

---

vars/seleniumExecuteTests.groovy

It's implementation is in Groovy.
https://github.com/SAP/jenkins-library/blob/jliempt/seleniumDocs/vars/seleniumExecuteTests.groovy

chore(docs): Document selenium step being Jenkins-only

---

pkg/orchestrator/azureDevOps.go
pkg/orchestrator/gitHubActions.go
pkg/orchestrator/gitHubActions_test.go
pkg/orchestrator/jenkins.go
pkg/orchestrator/orchestrator.go

Few notes about implementation:
1) GitHub Actions runnerr version is unavailable through API and envvars. So OrchestratorVersion is currently unimplemented.
2) Logs for a running job are not available through API, so logs for the last (running) stage will be skipped.

feat(orchestrator): add implementation for GitHub

---

README.md
documentation/docs/guidedtour.md
documentation/docs/index.md
documentation/docs/infrastructure/customjenkins.md
documentation/docs/pipelines/abapEnvironment/configuration.md
documentation/docs/scenarios/abapEnvironmentAddons.md
documentation/docs/steps/isChangeInDevelopment.md
documentation/docs/steps/neoDeploy.md
documentation/docs/steps/transportRequestUploadSOLMAN.md
documentation/docs/steps/xsDeploy.md

The markdown linting check is failing for PRs that trigger it. Fixing documentation for failing checks.
Removing unused links for violating MD053 rules.
Removing space between "*" and "Step" in abapEnvironmentAddons.md for violating MD037/no-space-in-emphasis rule.
Changing * to _ in neoDeploy.md for violating MD049/emphasis-style rule.
Fixing links in transportRequestUploadSOLMAN.md:10 and abapEnvironment/configuration.md:134

fix(docs): fixing documentation for violating markdownlint rules.

---

test/groovy/SetupCommonPipelineEnvironmentTest.groovy
vars/setupCommonPipelineEnvironment.groovy

When users create organization pipelines in Jenkins and use the productive branch with a slash the ref is split wrong. Example: for branch `origin/test/001` splitting will create `test`.

fix(setupCommonPipelineEnvironment): setting git ref for branch with slashes in name

---

cmd/whitesourceExecuteScan.go

toolrecord file:
- drop the hardcoded default url
- use the more user-friendly project ID instead of the project token

toolrecord/whitesource: improve URL generation 

---

cmd/codeqlExecuteScan.go

Sometimes users configure Vault and Jenkins. Now if Vault credentials are wrong, and Jenkins is correct, users are unaware which credentials have been used. For this they have to explicitly set - skipvault:true. Added logging with this info.

fix(codeqlExecuteScan): logging when use both Vault and Jenkins Credentials config

---

cmd/batsExecuteTests.go
cmd/gitopsUpdateDeployment.go
cmd/gitopsUpdateDeployment_generated.go
cmd/gitopsUpdateDeployment_test.go
pkg/git/git.go
pkg/git/git_test.go
resources/metadata/gitopsUpdateDeployment.yaml

when using enterprise github instance the step will fail as it will not trust the x509 root certs from enterprise github instance. this PR introduces an new list parameter to download the certs and add it to the `CAbundle` option for the git operations
- [x ] Tests

fix (gitOpsUpdateDeployment) add CA bundle options to plain clone and commit to trust enterprise github instances

---

cmd/helmExecute_generated.go
resources/metadata/helmExecute.yaml
vars/helmExecute.groovy

in the same way how this is done for the targetRepositoryCredentialsId

fix(helm): forward sourceRepositoryCredentialsId from groovy to go layer

---

pkg/vault/client.go

Reverts SAP/jenkins-library#4475
Reverting because retrying might be causing issues with locking in Vault.

Revert "chore(vault): custom retry check function"

---

pkg/splunk/splunk.go

Since `github/owner` and `github/repository` are written to CPE by [logic written in groovy](https://github.com/SAP/jenkins-library/blob/7ab2386337c287ce89b41820b41369fca7e87bf9/vars/commonPipelineEnvironment.groovy#L212-L213), `github/owner` and `github/repository` are not filled for ADO and Actions.
This PR allows reading repository name from `git/repository` CPE and repository owner from `git/organization` CPE which were written to CPE by go step (sapPipelineInit.go), so that the `owner` and `repository` are available for Jenkins, ADO and Actions.

Splunk: use `repository` and `organization` CPE from `git` instead of `github` folder

---

pkg/config/vault.go
pkg/vault/client.go

This PR gives some structure to the vault log output which previously looked like this:
Now it will look like this:

chore(vault): structure vault logs

---

pkg/checkmarxone/reporting.go

This PR aims to change the Low query name to Name (instead of Query) since this naming is required by the policy as code framework.

[CxOne] Update Name field in reporting 

---

pkg/codeql/github_repo_upload.go
pkg/codeql/github_repo_upload_test.go

Fixed unzipping db sources to exclude codeqlDB from uploaded project to Github.

fix(codeqlExecuteScan): exclude codeqlDB from uploaded sources to github

---

cmd/cnbBuild.go
cmd/cnbBuild_generated.go
cmd/cnbBuild_test.go
integration/integration_cnb_test.go
pkg/cnbutils/user.go
pkg/command/command.go
pkg/mock/fileUtils.go
pkg/mock/runner.go
pkg/piperutils/fileUtils.go
resources/metadata/cnbBuild.yaml

The `cnbBuild` will read CNB user information from environment variables to enable support for Paketo Jammy builders.
It enforces to run piper as root, the user for CNB lifecycle will be taken from the CNB_USER_ID and CNB_GROUP_ID. When the process is invoked, privileges are dropped down to this gid/uid.
Also this PR introduces two new features to the core packages:
- `RunExecutableWithAttrs` which allows to pass `syscall.SysProcAttr` to the execution.
- Recursive `Chown`

feat(cnbBuild): support builders with different CNB user ids

---

.github/workflows/release-go.yml
.github/workflows/upload-go-master.yml

#4625  causes the Windows binary build to fail. It was [discussed and accepted,](https://github.com/SAP/jenkins-library/pull/4625#discussion_r1365401213) so this PR removes the logic related to creating the Windows binary.

Remove logic related to Windows binary

---

cmd/npmExecuteScripts.go
cmd/npmExecuteScripts_generated.go
cmd/npmExecuteScripts_test.go
resources/metadata/npmExecuteScripts.yaml

Added option to skip installing dev. dependencies by providing **production** parameter of type boolean, skipped if true.

feat(npmExecuteScripts): added option to skip installing dev. deps.

---

cmd/codeqlExecuteScan.go
cmd/codeqlExecuteScan_test.go
pkg/codeql/reporting.go
pkg/codeql/reporting_test.go

Refactored codeql reports generation to allow it to be used as standalone tool.

fix(codeqlExecuteScan): refactored codeql reporting

---

cmd/detectExecuteScan.go

In #4595 a typo was committed that prevents Go private packages from being correctly set up in the `detectExecute` step

fix(detectExecute): logic of fetching golang private packages

---

integration/integration_tms_export_test.go
integration/integration_tms_upload_test.go

As we have changed the [default serviceKey parameter for the tms steps](https://github.com/SAP/jenkins-library/pull/4661), we need to adapt the serviceKey parameter used in the integration tests.

Use new env var for tms service key

---

pkg/config/stepmeta.go
pkg/config/stepmeta_test.go
vars/dockerExecute.groovy
vars/dockerExecuteOnKubernetes.groovy

`containerMountPath` did not work and was partly commented out. For now, it only accepts `mountPath` with the name volume. If provided, the `mountPath` will be used as `containerMountPath`.

Add support for volume mounts

---

cmd/codeqlExecuteScan.go
cmd/codeqlExecuteScan_test.go

Download settings files for maven if GlobalSettingsFile and/or ProjectSettingsFile is url.

fix(codeqlExecuteScan): support http(s) urls for maven settings files

---

cmd/getConfig.go
cmd/getConfig_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/stepmeta.go
pkg/config/stepmeta_test.go

Condition did not work for sidecars because the were only evaluated, but never actually added to the config.

Fix sidecar conditionals

---

test/groovy/CheckmarxExecuteScanTest.groovy
vars/checkmarxExecuteScan.groovy
vars/checkmarxOneExecuteScan.groovy

This change aims to align Cx/CxOne steps with others to no longer fail when the checkmarx_reports.json JSON file is not found in the workspace.

fix(checkmarx):disable failOnMissingReports

---

go.mod
go.sum
pkg/codeql/github_repo_upload.go
pkg/codeql/github_repo_upload_test.go

Uploading CodeQL sources from non-GitHub SCM to GitHub fails if the target repo is empty. The fix is to initialize an empty repository before using it.

fix(codeqlExecuteScan): init empty GitHub repo before mirroring code

---

cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_generated.go
pkg/whitesource/configHelper.go
pkg/whitesource/scanOptions.go
pkg/whitesource/scanUA.go
resources/metadata/whitesourceExecuteScan.yaml

Feature - whitesourceExecuteScan - adding ability to scan multiple docker images

---

cmd/whitesourceExecuteScan.go

The issue was caused by the images that have "/" in the name triggering the failure of renaming the downloaded image file and trying to find the parent "folder" in the image tag (owner/image:version is an example)

Fix for the whitesource multiple images scan feature

---

documentation/docs/infrastructure/vault.md
pkg/config/vault.go
pkg/config/vault_test.go

support for multiple values in `vaultCredentialEnvPrefix` and `vaultTestCredentialEnvPrefix` (with backward compatibility to single string)
closes https://github.com/SAP/jenkins-library/issues/4740

feat(configs): vaultCredentialEnvPrefix to support several prefixes

---

cmd/whitesourceExecuteScan.go
cmd/whitesourceExecuteScan_generated.go
pkg/whitesource/scan.go
resources/metadata/whitesourceExecuteScan.yaml

Fixed issue with empty project tokens after scanning

---

cmd/batsExecuteTests.go
cmd/gitopsUpdateDeployment.go
cmd/gitopsUpdateDeployment_test.go
pkg/git/git.go
pkg/git/git_test.go

gitopsUpdateDeployment doesn't take into account **branchName** parameter when clonning a repo. This leads to a bug when specifying branchName other than **default** (main or master). In that case git clones **default** branch and then tries to check out to **branchName** (which doesn't exist in cloned repo) and then creates that **branchName** from **default** branch.
This PR fixes this bug by passing branchName into clone function

fix(gitopsUpdateDeployment): take into account branch name when clonning

---

cmd/detectExecuteScan.go
cmd/detectExecuteScan_generated.go
cmd/detectExecuteScan_test.go
pkg/docker/docker.go
pkg/documentation/generator/main.go
resources/metadata/detectExecuteScan.yaml

This has following prerequisites to `jenkins-library` (cherry-picked):
* #4672 Allow `sidecars` to have `conditions`
* #4673 Add `volumeMount` support to `sidecars`
The enhances `detectExecuteScan` to not only scan the workspace, but also all images that can be found in the `cpe`. If `kanikoExecute` or `cnbBuild` produce images, the information will be written to the `cpe`. In order to do these scans, a sidecar is needed. The sidecar is different for the distro that is scanned. The user can configure this via the new parameter `containerDistro` (default "ubuntu").
The user can can use `scanImages: false` to prevent this.

feat(detectExecuteScan): Also scan images that are in the CPE

---

cmd/detectExecuteScan.go

Leftover from https://github.com/SAP/jenkins-library/pull/4678
This block of code also prevents users from setting `imageNameTags` directly as a property to the step (CPE will still be empty)

fix(detectExecuteScan): do not read `imageNameTags` directly from CPE

---

cmd/containerSaveImage.go
cmd/detectExecuteScan.go
cmd/detectExecuteScan_test.go

If the image name to scan contains special symbols (like `/`) the step fails to create a tarball.
Underlying function `runContainerSaveImage` generates sanitized name for the tarball, escaping special symbols and replacing them with `_`.

fix(detectExecuteScan): sanitize container image name before saving

---

cmd/pythonBuild.go
cmd/pythonBuild_generated.go
resources/metadata/pythonBuild.yaml

currently cyclone dx sbom is generated without pip installing the dependencies . this PR beings in the ability to run pip install if it finds the requirement.txt file . the file path is defaulted in parameter `requirementsFilePath` and can be overwritten as needed

feat (pythonBuild) include pip install of requirements.txt before cyclone dx sbom generation

---

cmd/cnbBuild.go
cmd/cnbBuildAttr.go
cmd/cnbBuildAttr_windows.go

Currently the `go build` fails on windows machines with the following error:
```
cmd\cnbBuild.go:589:3: unknown field Credential in struct literal of type "syscall".SysProcAttr
cmd\cnbBuild.go:589:24: undefined: syscall.Credential
```
Because on Windows the `exec_windows.go` contains the struct like this:
```go
type SysProcAttr struct {
HideWindow                 bool
CmdLine                    string // used if non-empty, else the windows command line is built by escaping the arguments passed to StartProcess
CreationFlags              uint32
Token                      Token               // if set, runs new process in the security context represented by the token
ProcessAttributes          *SecurityAttributes // if set, applies these security attributes as the descriptor for the new …
```

fixes `go build` on windows

---

cmd/cnbBuild.go
cmd/cnbBuild_test.go
pkg/cnbutils/auth.go
pkg/cnbutils/auth_test.go

This change validates that credentials for the target registry (excluding localhost) can be found in the provided secret. If it is not present, it fails the run and exits with a hopefully more descriptive error on what went wrong.

feat(cnbBuild): validate docker credentials

---

resources/default_pipeline_environment.yml

This change allows usage of `stashNoDefaultExcludes` parameter, 
as otherwise I think it it impossible to stash back the .git repository.
It should not affect anything if `stashNoDefaultExcludes` is not used.

exclude .git on stashBack

---

pkg/maven/settings.go
pkg/maven/settings_test.go

Errors with unmarshalling the `settings.xml` for adding staging repository secrets were not being handled.

fix(maven): Add proper error handling for invalid settings.xml when publishing

---

cmd/artifactPrepareVersion_generated.go
resources/metadata/artifactPrepareVersion.yaml

When build tool is CAP, artifactPrepareVersion works with pom.xml --> mvn needed --> the step should run inside docker container

Run artifactPrepareVersion inside a docker container for CAP apps

---

.github/workflows/documentation.yml
.github/workflows/update-go-dependencies.yml
.github/workflows/upload-go-master.yml
.github/workflows/verify-go.yml
Dockerfile
go.mod
go.sum
integration/testdata/TestGolangIntegration/golang-project1/go.mod
integration/testdata/TestGolangIntegration/golang-project2/go.mod
pkg/http/http_cert_logon_test.go
src/com/sap/piper/PiperGoUtils.groovy

This PR fixes `go: github.com/buildpacks/lifecycle@v0.18.4 requires go@1.21, but 1.20 is requested` when `go 1.21` or newer is used, `go 1.20` ignores that issue

feat: bump go to 1.21

---

pkg/config/config.go

typo: config.go, more spaces in warning

---

cmd/gcpPublishEvent.go
cmd/gcpPublishEvent_generated.go
pkg/events/events.go
pkg/events/events_test.go
pkg/gcp/pubsub.go
resources/metadata/gcpPublishEvent.yaml

Makes it possible to insert additional data into the `eventData` JSON, which is useful when the `eventData` comes from the pipeline env.
This also fixes the format of the `"data"` part of the CloudEvent. If you pass a string to `cloudEvent.SetData()`, it will be marshalled and ends up with duplicated escape characters (for example `{\\\\"testKey\\\\": \\\\"testValue\\\\"}`), which causes problems when unmarshalling the data. Passing a `map[string]interface{}` solves it.

feat(gcpPublishEvent): Add additionalEventData param

---

cmd/cnbBuild_generated.go
cmd/kanikoExecute_generated.go
cmd/kanikoExecute_test.go
integration/integration_cnb_test.go
pkg/syft/syft.go
pkg/syft/syft_test.go
resources/metadata/cnbBuild.yaml
resources/metadata/kanikoExecute.yaml

Bump the rather outdated version of the `syft` command using for generating a `sbom` for images.

chore(deps): update syft version to 1.4.1

---

cmd/cnbBuild.go
pkg/syft/syft.go
pkg/syft/syft_test.go

Based on https://github.com/SAP/jenkins-library/pull/4933
In case of images built with cloud native buildpacks, creating the sbom is only about collecting the sboms already on the image.

feat(cnbbuild): cnbbuild collects SBOM of the produced images

---

pkg/whitesource/configHelper.go

Fixes:
In whitesourceExcuteScan piper step the buildDescriptorExcludeList parameter is not excluding the npm modules during scanning. To address this, we have implemented the ignoreDirectoryPatterns functionality specifically for NPM modules to exclude the specified modules during the scan.

Improving buildDescriptorExcludeList for npm

---

cmd/detectExecuteScan.go

Added a precise scan properties pattern to differentiate between two similar detect scan properties(--detect.excluded.directories.defaults.disabled and --detect.excluded.directories).

Fixed excluded directories with pattern

---

cmd/piper.go

This PR disables sendong telemetry data to Pendo, since Pendo subscription has been disabled
same as https://github.com/SAP/jenkins-library/pull/4788

Disable telemetry reporting

---

resources/default_pipeline_environment.yml

This change extends the visibility of **dist** folder produced during the Build stage. Currently it is stashed only if the **dist** folder is on root. With this change, it is stashed from the sub folders of the sources.

Find dist folder from sources

---

pkg/config/vault.go

Checking types is meaningless here since it will always be true for string parameters. It's reasonable to check value.

fix vaultDisableOverwrite handling

---

pkg/http/http.go

This change will skip logging http request bodies if it's byte content (for example when uploading binaries). Logging binary contents doesn't make sense.

Skip logging of request byte content

---

cmd/mtaBuild.go
cmd/mtaBuild_generated.go
cmd/mtaBuild_test.go
resources/metadata/mtaBuild.yaml

The step currently always sets the timestamp in the MTA descriptor file. However, the [MTA Deploy Service](https://help.sap.com/docs/btp/sap-business-technology-platform/content-deployment) can do this too, and Piper doing it in the first place can cause issues for users. Therefore this PR makes this behaviour configurable, but keeps the default behaviour as is in order to not affect existing pipelines.

feat(mtaBuild): Add enableSetTimestamp parameter

---

cmd/vaultRotateSecretId.go

This PR 
- changes the log level from Debug to Info - it is helpful to see secret ID expiration time
- adds new Info level log - it helps to see what step does

vaultRotateSecretID: Update logging

---

cmd/azureBlobUpload_generated.go
resources/metadata/azureBlobUpload.yaml

This PR adds the possibility to fetch jsonCredentialsAzure from Vault for the azureBlobUpload step.

Add the possibility to fetch jsonCredentialsAzure from Vault

---

pkg/vault/client.go
pkg/vault/client_test.go

Vault support complex types, like objects, array or simple integers as key values. This PR introduces support for these keys, marshalling these types to JSON strings when possible.

feat(vault): support complex data types in secrets

---

cmd/cnbBuild.go
pkg/cnbutils/copy_project.go
pkg/cnbutils/copy_project_test.go
pkg/mock/fileUtils.go
pkg/piperutils/fileUtils.go

Copy projects with symlinks

---

cmd/sonarExecuteScan_generated.go
resources/metadata/sonarExecuteScan.yaml

Adds trustengine resource reference for the token parameter. This means that the Sonar token will be retrieved from there if it's not found in Vault.

feat(sonar): Enable trustengine for token retrieval

---

pkg/transportrequest/cts/upload.go
pkg/transportrequest/cts/upload_test.go

The error message from the [previous PR](https://github.com/SAP/jenkins-library/pull/5123) is not caught as expected due to missing return value. This fixes the problem.
- [x ] Tests

fix: add missing return value for error

---

cmd/artifactPrepareVersion.go
cmd/artifactPrepareVersion_test.go

This PR fixes issues when sometimes too long string written to the CPE git.commitMessage
Related task: [HSPIPER-347
](https://jira.tools.sap/browse/HSPIPER-347)

fix: too long string written to cpe git.commitMessage

---

pkg/config/evaluation.go

fix(Central Build): Fix handling legacy stage name for Jenkins pipelines

---

pkg/transportrequest/cts/upload.go
pkg/transportrequest/cts/upload_test.go

This fix supports passing of namespace prefix to the application name which was not considered with the old PR #5123.
- [ x] Tests

Fix: validate app name

---

cmd/gcpPublishEvent.go
pkg/events/events.go
pkg/events/events_test.go

Add identifier data to create uuid in events

---

cmd/mavenBuild.go
cmd/mavenBuild_test.go
cmd/mtaBuild.go
cmd/mtaBuild_generated.go
cmd/mtaBuild_test.go
pkg/npm/publish.go
pkg/npm/publish_test.go
pkg/piperutils/cyclonedxBom.go
pkg/piperutils/cyclonedxbom_test.go
resources/metadata/mtaBuild.yaml

As part of [HSPIPER-290](https://jira.tools.sap/secure/RapidBoard.jspa?rapidView=34089&projectKey=HSPIPER&view=detail&selectedIssue=HSPIPER-290) we need to add build artifacts for mta

feat: add build artifacts metadata for mtaBuild

---

pkg/cnbutils/project/metadata/metadata.go
pkg/cnbutils/project/metadata/metadata_test.go

[https://buildpacks.io/docs/for-platform-operators/how-to/build-inputs/declare-source-metadata/#source-_required_](describe) property is not meant to contain special characters and is optional anyway.

[cnbBuild] Remove commit message from project-metadata.toml

---

pkg/documentation/generator.go
pkg/documentation/generator/description.go
pkg/documentation/generator/main.go

This PR intends to include "GitHub Actions" tab for all the piper go steps via a flag` --includeGHA`. This flag is then used by piper documentation repository to generate the "GitHb Actions" tab for steps.
Modified the document generator files (generator folder and generator.go) to include flag `--include GHA`

Modify document generator to include GHA

---

resources/com.sap.piper/pipeline/stashSettings.yml

This reverts commit 28fb2b77bf7ba6af5000955e1664b8d3ec12195d.
The bug also appears when the class files are present.

Revert "Unstash class files for Compliance stage (#5192)"

---

pkg/documentation/generator/description.go

This PR aligns the sample step description for ADO and GHA .
I have added flags parameter for both as I think it will be easier for users to follow documentation with this parameter

Align description of ADO and GHA

---

pkg/documentation/generator/parameters.go

"Jenkins-specific" text label has been incorrectly set for all the steps parameters (details) not defined in related step metadata yml files. This fix explicitly checks if the param/secret name in jenkinsParams before adding such text label.
https://jira.tools.sap/browse/HSPIPER-237

fix(documentation): check param for jenkinsParams before appending Jenkins-specific text

---

resources/com.sap.piper/pipeline/stashSettings.yml

Now - as we know more details - we know that unstashing the class files will resolve the sonar issue.
For more details see the [original](https://github.com/SAP/jenkins-library/pull/5192) pull request.
We also discussed that the absense of `sonar-project.properties` could cause the issue. But this file is present. It is unstashed from the `sources`-stash.

Unstash class files for Compliance stage (#5192)

---

.gitattributes

From the testing it looks like just the attribute file is sufficient to exclude files. 
Tested: https://github.com/D074360/minimal-github-actions
Note: As our workflows are run from composite workflows from other repository this approach might not be sufficient.

Exclude README and CONTRIBUTING files from release packages

---

cmd/pythonBuild.go
cmd/pythonBuild_generated.go
cmd/pythonBuild_test.go
resources/metadata/pythonBuild.yaml

Adds ability for users to pass parameters to `setup.py` rather than only the `python` binary.

feat: add ability to pass flags to setup.py in pythonBuild step

---

cmd/detectExecuteScan.go
cmd/detectExecuteScan_generated.go
cmd/detectExecuteScan_test.go
pkg/whitesource/configHelper.go
resources/metadata/detectExecuteScan.yaml

Added the detect 10 parameter, user can use useDetect10 field to use the detect version 10 in their scan.
Change the repo name from detect.synopsys.com to detect.blackduck.com as per vendor instruction. 
Changed the  failErrorLevel flag from true to false as by-default.

feat(detect): Add support for Detect 10

---

pkg/splunk/data.go
pkg/splunk/splunk.go
pkg/splunk/splunk_test.go

This exposes the used orchestrator to the telemetry data sent to Splunk.

chore(Splunk): expose orchestrator to Splunk

---

.github/renovate.json

By default  'go mod tidy' and updating imports for PRs (in case of major module version upgrade) are disabled, so we had to do it on our own. This PR enables those features.
* https://github.com/renovatebot/renovate/blob/main/docs/usage/golang.md#how-it-works
* https://docs.renovatebot.com/configuration-options/#postupdateoptions

chore(renovate): enable 'go mod tidy' and updating imports for PRs

---

cmd/cnbBuild.go
go.mod
go.sum

Update mergo package to latest version.
Update imports to use new vanity URL for the package (https://github.com/darccio/mergo?tab=readme-ov-file#100)

fix(deps): Update version of mergo v1.0.0->v1.0.1

---

cmd/mavenBuild.go

`versioning.GetArtifact` for maven build [refers to some opts](https://github.com/SAP/jenkins-library/blob/f376166c7fe79772303365a89c11c86bfdefb07c/pkg/versioning/versioning.go#L141-L155) for `maven.EvaluateOptions` that later [used](https://github.com/SAP/jenkins-library/blob/f376166c7fe79772303365a89c11c86bfdefb07c/pkg/maven/maven.go#L108-L110) by `maven.Evaluate`.
This PR adds missed opts so they could be used by maven.Evaluate and other methods.

(fix): Add missed opts used by versioning.GetArtifact

---

.github/workflows/integration-tests.yml
.github/workflows/release-go.yml

feat: enhance release workflow with integration test status and dry run option

---

cmd/cloudFoundryDeploy_generated.go
documentation/docs/steps/cloudFoundryDeploy.md
resources/metadata/cloudFoundryDeploy.yaml

This PR improves the documentation of the cloudFoundryDeploy step by summarising and listing down various capabilities and removing some deprecated links.

Improve CF documentation

---

documentation/docs/steps/cloudFoundryDeploy.md

Add note on docker image deployment for the cloudFpundryDeploy step

(docu)CloudFoundryDeploy: add note about docker image deployments

---

pkg/versioning/gomodfile.go
pkg/versioning/gomodfile_test.go

- GOlang module name must comply with the naming conventions as defined per [`golang.org/x/mod/module.CheckPath`](https://pkg.go.dev/golang.org/x/mod/module#CheckPath)
- if module path just consists of a name, `groupID` is not set
When a golang module has no `/` in it's name, the code is currently failing.
```
panic: runtime error: slice bounds out of range [:-1]
goroutine 1 [running]:
github.com/SAP/jenkins-library/pkg/versioning.(*GoMod).GetCoordinates(0xc0001612c0)
/home/runner/work/jenkins-library/jenkins-library/pkg/versioning/gomodfile.go:101 +0x345
github.com/SAP/jenkins-library/cmd.runArtifactPrepareVersion(0xc000c798b8, 0x0?, 0xc000966700, {0x0, 0x0}, {0x3c51288, 0xc00098e3c0}, {0x3c49fd8, 0xc0010b5bc0}, 0x384d8d8)
/home/runner/work/jenkins-library/jenkins-library/cmd/artifactPrep …
```

fix(golang): handle errors with simple module names

---

pkg/checkmarxone/checkmarxone.go

This PR is fixing an error in the PUT /api/projects to update tags.
The API returns a 400 when a query is assigned to the application.
The workaround is to remove the applicationIds from the JSON payload.

fix(checkmarxOneExecuteScan) Fix API error in 3.30

---

cmd/mavenBuild_generated.go
resources/metadata/mavenBuild.yaml

This fixes a typo in the vault lookup path for `altDeploymentRepositoryPassword` parameter.

fix(maven build): typo in vault lookup path for altDeploymentRepositoryPassword

---

cmd/mtaBuild_generated.go
resources/metadata/mtaBuild.yaml

This fixes a typo in the vault lookup path for mtaDeploymentRepositoryPassword parameter.

fix(mta build): typo in vault lookup path for mtaDeploymentRepositoryPassword

---

pkg/orchestrator/jenkins.go

Otherwise, it misidentifies branches such as `S4HPROC...`

Check for prefix instead of substring

---

resources/default_pipeline_environment.yml

jdk11 version is quite outdate and JaaS team now supports jdk17 version of the JNLP image.

deps: update jdk version for JNLP image

---

pkg/splunk/data.go
pkg/splunk/splunk.go
pkg/splunk/splunk_test.go
pkg/telemetry/data.go
pkg/telemetry/telemetry.go

Telemetry data is missing clear distinction between GPP and custom pipelines. This PR will add a field to Splunk data that will be filled during pipeline execution.

feat(Splunk): add TemplateName field to Splunk data

---

pkg/npm/npm.go

We cannot clearly see in the log when a package list provided from outside is used. Hence adding a log-message.

Provide log message in case externally provided package list is used.

---

cmd/githubPublishRelease.go
cmd/githubPublishRelease_generated.go
resources/metadata/githubPublishRelease.yaml

When uploading large asset or in case of slow network, the step fails to get the response headers due to timeout:
`net/http: timeout awaiting response headers`
Increasing timeout should solve that issue.

feat(githubPublishRelease): make GitHub API timeout configurable

---

cmd/detectExecuteScan_generated.go
resources/metadata/detectExecuteScan.yaml

The coding using the parameter was removed with https://github.com/SAP/jenkins-library/commit/94a33844a09f6e5c92735d301e351daa1c193db5. The parameter description should have been removed in that same commit. When something is deprecated, it still works. This parameter does not.

Remove documentation for minScanInterval parameter of detectExecuteScan

---

pkg/sonar/issueService_test.go

In unit tests from sonar package the set of assertions to check slices equality has been changed to call elements matching function.

chore(tests): check equality of slices replaced by elements matching assertion

---

pkg/splunk/data.go
pkg/splunk/splunk.go
pkg/splunk/splunk_test.go

Currently on Splunk we can only check whether an error actually occurred but we don't capture its contents. That makes it hard for us to decide on which common errors we should focus.

feat(splunk): enhance error details

---

cmd/detectExecuteScan.go
cmd/detectExecuteScan_generated.go
resources/metadata/detectExecuteScan.yaml

Deprecate `useDetect8` flag for `detectExecuteScan` command. In case it's used step will default to `detect10.sh` download.

deprecate 'useDetect8'

---

.github/workflows/release-go.yml

added a custom script that will update or create dynamic tags which always point to latest release. For example, when v1.2.4 is released, tags v1 and v1.2 will be updated (or created) to point to the same commit as v1.2.4
related pr: https://github.com/SAP/project-piper-action/pull/291

ci(release): update/create dynamic tags with each release

---

cmd/sonarExecuteScan.go
cmd/sonarExecuteScan_test.go

The categories has been initialized to refer an empty list.
In case of no issues detected at static code check the
sonarscan report should contains empty list for Errors entry
instead of null value.

fix(sonar): Fix null value for errors entry in sonarscan report

---

cmd/pythonBuild_generated.go
integration/integration_python_test.go
resources/metadata/pythonBuild.yaml

This updates the Python version used in `pythonBuild` step to `v3.10` as the current version is reaching [EOL](https://devguide.python.org/versions/).

fix(deps):update python to v3.10 for pythonBuild

---

cmd/checkmarxOneExecuteScan.go
cmd/checkmarxOneExecuteScan_test.go
pkg/checkmarxone/checkmarxone.go

Fixes:
- full scans were incorrectly counted as incremental because the API response was not containing the actual scan type but the requested type
- incremental scans based on the primary branch were not following the full scan cycle parameter
- default branch name will be the cxone default: .unknown (instead of "n/a")

fix(CxOne): Fix incremental scan count and full scan cycle handling
