cmd/mavenExecuteIntegration.go, cmd/mavenExecuteStaticCodeChecks.go, cmd/mtaBuild.go, pkg/maven/maven.go, pkg/maven/maven_test.go
=> Pass settings file also to install-file

.github/workflows/release-go.yml
cf https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Replace deprecated set-env github actions command

cmd/whitesourceExecuteScan.go, cmd/whitesourceExecuteScan_generated.go, pkg/whitesource/scanMaven.go, pkg/whitesource/scanOptions.go, resources/metadata/whitesource.yaml
=> Install artifacts before whitesource scan

cmd/whitesourceExecuteScan.go, cmd/whitesourceExecuteScan_generated.go, cmd/whitesourceExecuteScan_test.go, pkg/generator/helper/helper.go, pkg/generator/helper/helper_test.go, pkg/generator/helper/resources.go, pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden, pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden, resources/metadata/whitesource.yaml, vars/commonPipelineEnvironment.groovy
writes WhiteSourrce project name output as list into the pipeline environment
=> fix(whitesourceExecuteScan) properly handle output resources

cmd/githubCheckBranchProtection_generated.go, resources/metadata/githubbranchprotection.yaml
The github branch protection code should also be fetched from vault
=> Fetch GithubBranchProtection token from vault

pkg/log/fatalHook.go
=> fix(permissions) allow deletion of errors file

pkg/versioning/descriptorUtils.go
remove reference to Fortify since this is not Fortify-related
=> fix(descriptorUtils) improve error message

cmd/abapEnvironmentCreateSystem.go, cmd/abapEnvironmentCreateSystem_generated.go, cmd/abapEnvironmentCreateSystem_test.go, resources/metadata/abapEnvironmentCreateSystem.yaml
=> Adapt parameter names

cmd/abapEnvironmentRunATCCheck.go
=> Fix ATC issue

resources/default_pipeline_environment.yml, test/groovy/SlackSendNotificationTest.groovy
I have used the colors from blue ocean.
=> change slack color to reflect all states

pkg/versioning/gradle.go, pkg/versioning/gradle_test.go, pkg/versioning/inifile.go, pkg/versioning/properties.go, pkg/versioning/properties_test.go, pkg/versioning/versioning.go, pkg/versioning/versioning_test.go, resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml
add basic functionality to get and set version for `gradle`- based project
=> versioning: gradle

pkg/config/vault.go, pkg/config/vault_test.go
fix bug which lead to not resolving aliases
=> (Vault) consider alias during secret resolving

DEVELOPMENT.md
Adds section about parallel testing in development documentation
=> Enhance development documentation regarding parallel testing

cmd/gitopsUpdateDeployment_test.go, pkg/git/git_test.go
Marks all tests regarding to gitops as parallizable.
=> Marks tests as parallizable

test/groovy/templates/AbapEnvironmentPipelineStageCloneRepositoriesTest.groovy, vars/abapEnvironmentPipelineStageCloneRepositories.groovy
=> Unify strategy spelling

resources/com.sap.piper/pipeline/stageDefaults.yml
This change adds runStep conditions for the steps mavenExecuteIntegration and 
npmExecuteScripts for the stage Integration.
=> Add runStep conditions for mavenExecuteIntegration and npmExecuteScripts in Integration stage

.codeclimate.yml, .markdownlint.yml, DEVELOPMENT.md, documentation/architecture/decisions/nexusUpload.md, documentation/docs/guidedtour.md, documentation/docs/index.md, documentation/docs/pipelines/cloud-sdk/build-tools.md, documentation/docs/pipelines/cloud-sdk/cloud-qualities.md, documentation/docs/pipelines/cloud-sdk/configuration.md, documentation/docs/pipelines/cloud-sdk/introduction.md, documentation/docs/scenarios/CAP_Scenario.md, documentation/docs/scenarios/abapEnvironmentAddons.md, documentation/docs/scenarios/changeManagement.md, documentation/docs/scenarios/ui5-sap-cp/Readme.md, documentation/docs/scenarios/upload-to-transportrequest/Readme.md, documentation/docs/scenarios/xsa-deploy/Readme.md, documentation/docs/stages/examples.md, documentation/docs/stages/introduction.md, documentation/docs/steps/neoDeploy.md, documentation/docs/steps/uiVeri5ExecuteTests.md
activate rules and fix findings: 
- [MD001 (header-increment)](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time)
- [MD007 (ul-indent)](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md007---unordered-list-indentation)
- [MD022 (blanks-around-headers)](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022---headings-should-be-surrounded-by-blank-lines)
- [MD026 (no-trailing-punctuation)](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026---trailing-punctuation-in-heading)
- [MD030 (list-marker-space)](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md030---spaces-after-list-markers)
- [MD031 …
=> chore: fix markdownlint findings

documentation/docs/stages/introduction.md
The documentation is outdated because the stages do have default implementations now. This PR updates that.
=> Document default implementation of stages

documentation/docs/scenarios/abapEnvironmentAddons.md
=> Build and Publish Add-on Products on SAP Cloud Platform ABAP Environment: Move limitations to top

documentation/docs/scenarios/abapEnvironmentAddons.md
=> Build and Publish Add-on Products on SAP Cloud Platform ABAP Environment: Change troubleshooting links

cmd/githubPublishRelease_generated.go, resources/metadata/githubrelease.yaml
=> [typo] relese -> release

pkg/checkmarx/checkmarx.go, pkg/checkmarx/checkmarx_test.go
=> Checkmarx team name configuration compatibility

pkg/checkmarx/checkmarx.go, pkg/checkmarx/checkmarx_test.go
=> Checkmarx configuration compatibility fix

cmd/whitesourceExecuteScan_generated.go, resources/metadata/whitesource.yaml
=> Fix workingDir for mta whitesource scan

documentation/docs/steps/checksPublishResults.md
changes:
- fixs list of prerequisites 
- add code blocks to default values
- correct sample parameter `threshold`
=> fix(docs): typo in sample parameter

cmd/abapEnvironmentCreateSystem.go, cmd/abapEnvironmentCreateSystem_test.go
=> Add parent_saas_appname

cmd/abapEnvironmentCreateSystem_generated.go, cmd/cloudFoundryCreateServiceKey_generated.go, cmd/cloudFoundryCreateService_generated.go, cmd/cloudFoundryDeleteService_generated.go, cmd/cloudFoundryDeploy_generated.go, resources/metadata/abapEnvironmentCreateSystem.yaml, resources/metadata/cloudFoundryCreateService.yaml, resources/metadata/cloudFoundryCreateServiceKey.yaml, resources/metadata/cloudFoundryDeleteService.yaml, resources/metadata/cloudFoundryDeploy.yaml
Fix cloudfoundry fetching secrets from vault
=> fix cloudfoundry deployment

documentation/docs/pipelines/abapEnvironment/configuration.md, documentation/docs/pipelines/abapEnvironment/introduction.md, documentation/docs/pipelines/abapEnvironment/stages/ATC.md, documentation/docs/pipelines/abapEnvironment/stages/build.md, documentation/docs/pipelines/abapEnvironment/stages/cloneRepositories.md, documentation/docs/pipelines/abapEnvironment/stages/confirm.md, documentation/docs/pipelines/abapEnvironment/stages/initialChecks.md, documentation/docs/pipelines/abapEnvironment/stages/integrationTest.md, documentation/docs/pipelines/abapEnvironment/stages/post.md, documentation/docs/pipelines/abapEnvironment/stages/prepareSystem.md, documentation/docs/pipelines/abapEnvironment/stages/publish.md, documentation/docs/steps/abapEnvironmentCloneGitRepo.md, documentation/docs/steps/abapEnvironmentPullGitRepo.md, documentation/mkdocs.yml, vars/abapEnvironmentPipelineStageConfirm.groovy, vars/abapEnvironmentPipelineStageIntegrationTests.groovy
This documentation aims to provide more details about the stages of the ABAP Environment Pipeline
=> Add stage docu

vars/cloudFoundryDeploy.groovy
=> [Docu] Fix switheroo of deployType and deployTool typo

documentation/docs/scenarios/abapEnvironmentAddons.md
link multitenant application in ABAP Environment in the scenario
=> link multitenant application in ABAP Environment

pkg/abap/build/bfw.go
in case this is really important it should be logged and not
emitted to stdout.
=> Remove strange 'Hello', most likly troubleshoot leftover

DEVELOPMENT.md
Signed-off-by: Fabian Reh <fabian.reh@sap.com>
Adds section about how to sign commits in git
=> Add section about signing commits in git.

vars/piperExecuteBin.groovy
=> fix(piperExecuteBin): define variable

vars/commonPipelineEnvironment.groovy
=> fix(CPE): correct handling of complex (json) data in writeToDisk

cmd/abapEnvironmentCreateSystem.go, cmd/abapEnvironmentCreateSystem_test.go
Marshalling only worked, if the boolean had the value "true".
With this fix, a pointer to the boolean is used, which fixes this issue.
=> Fix marshalling booleans

cmd/transportRequestUploadCTS.go, cmd/transportRequestUploadCTS_test.go, pkg/transportrequest/cts/upload.go, pkg/transportrequest/cts/upload_test.go
In the near future we will have more upload actions, like
SOLMAN, RFC. Here we prepare the package structure for that.
=> [refactoring] Make room for other upload action: move package

pkg/config/config.go, pkg/config/vault.go, pkg/config/vault_test.go
Vault Parameters are now also whitelisted for custom defaults.
=> [Vault] Mixin Vault Parameters for default config

documentation/docs/pipelines/abapEnvironment/configuration.md, documentation/docs/pipelines/abapEnvironment/introduction.md, documentation/docs/pipelines/abapEnvironment/stages/cloneRepositories.md, documentation/docs/scenarios/abapEnvironmentAddons.md, documentation/docs/scenarios/abapEnvironmentTest.md
=> Docu improvements

documentation/docs/scenarios/abapEnvironmentAddons.md
=> Add commitID to Add-on Doku

cmd/abapEnvironmentCheckoutBranch_test.go, cmd/abapEnvironmentCloneGitRepo_test.go, cmd/abapEnvironmentPullGitRepo_test.go, cmd/abapEnvironmentRunATCCheck_test.go, pkg/abaputils/abaputils_test.go
Reverts SAP/jenkins-library#2570
=> Revert "Parallel test processing for abaputils"

documentation/docs/CNAME
Need CNAME file with new docu URL
=> Add CNAME file to documentation

cmd/cloudFoundryCreateServiceKey_generated.go, cmd/cloudFoundryDeleteService_generated.go, resources/metadata/cloudFoundryCreateServiceKey.yaml, resources/metadata/cloudFoundryDeleteService.yaml
This change increases the ppiper/cf-cli version. This change would fix an issue with org names containing special characters.
=> Increase cf-cli for createServiceKey and deleteService

resources/default_pipeline_environment.yml
=> fix(PR): avoid NPE in PR label handling

cmd/sonarExecuteScan.go
=> fix(sonar): prevents step from contacting sonar API for legacy systems

cmd/fortifyExecuteScan.go
=> fortifyExecuteScan: Pull request version not considered on upload

pkg/config/config.go, pkg/config/config_test.go, pkg/config/stepmeta.go, pkg/config/stepmeta_test.go
=> fix(config): properly handle empty values from cpe

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_generated.go, cmd/fortifyExecuteScan_test.go, resources/metadata/fortify.yaml
=> Fortify cmd parameters for scan

cmd/abapEnvironmentCloneGitRepo.go, documentation/docs/pipelines/abapEnvironment/configuration.md, documentation/docs/pipelines/abapEnvironment/introduction.md, documentation/docs/pipelines/abapEnvironment/stages/cloneRepositories.md, documentation/docs/scenarios/abapEnvironmentAddons.md, documentation/docs/scenarios/abapEnvironmentTest.md
=> remove warnings

pkg/versioning/versioning.go, pkg/versioning/versioning_test.go
=> Add support for yarn

pkg/http/http.go
=> fix(http.go): Retry also on connection refused

cmd/abapEnvironmentCreateSystem.go
=> Fix step not showing error status

pkg/whitesource/configHelper.go
=> fix(whitesourceExecuteScan): Stop enforce aggregation

cmd/mtaBuild_generated.go, cmd/nexusUpload_generated.go, cmd/whitesourceExecuteScan_generated.go, integration/integration_mta_build_test.go, integration/testdata/TestMtaIntegration/npm/Dockerfile, resources/metadata/mtaBuild.yaml, resources/metadata/nexusUpload.yaml, resources/metadata/whitesource.yaml
update dockerimage from 1.0.16.1 to 1.1.1 
https://sap.github.io/cloud-mta-build-tool/whatsnew/
=> feat(mta): update MBT build tool to latest release 1.1.1

.codeclimate.yml, .github/workflows/documentation.yaml, .github/workflows/integration-tests-pr.yaml, .github/workflows/integration-tests.yaml, .github/workflows/markdown.yml, .github/workflows/release-go.yml, .github/workflows/verify-go.yml, .github/workflows/verify-groovy.yml, .github/workflows/verify-yaml.yml, .markdownlint.yml, .yamllint.yml, resources/metadata/abapAddonAssemblyKitCheckCVs.yaml, resources/metadata/abapAddonAssemblyKitCheckPV.yaml, resources/metadata/abapAddonAssemblyKitCreateTargetVector.yaml, resources/metadata/abapAddonAssemblyKitPublishTargetVector.yaml, resources/metadata/abapAddonAssemblyKitRegisterPackages.yaml, resources/metadata/abapAddonAssemblyKitReleasePackages.yaml, resources/metadata/abapAddonAssemblyKitReserveNextPackages.yaml, resources/metadata/fortify.yaml, resources/metadata/githubbranchprotection.yaml, resources/metadata/githubcommentissue.yaml, resources/metadata/githubcreateissue.yaml, resources/metadata/githubcreatepr.yaml, resources/metadata/githubrelease.yaml, resources/metadata/githubstatus.yaml, resources/metadata/karma.yaml, resources/metadata/kubernetesdeploy.yaml, resources/metadata/sonar.yaml, resources/metadata/whitesource.yaml
add [yamllint-github-action](https://github.com/karancode/yamllint-github-action) to run [yamllint](https://github.com/adrienverge/yamllint) on step metadata files and config files.
=> chore(ci): add yamllint action

pkg/whitesource/whitesource.go, pkg/whitesource/whitesource_test.go
some errors go unnoticed so far ...
This is to resolve this problem.
=> fix(whitesource) proper error message when tokens are not found

cmd/abapEnvironmentRunATCCheck_generated.go, documentation/docs/pipelines/abapEnvironment/configuration.md, documentation/docs/pipelines/abapEnvironment/extensibility.md, documentation/mkdocs.yml, resources/metadata/abapEnvironmentRunATCCheck.yaml
Add documentation for generating HTML document in abapEnvironmentRunATCCheck in new Extensibility Section for ABAP environment pipeline.
=> Docu changes for ATC step

documentation/docs/scenarios/abapEnvironmentAddons.md
=> Fix limitation abapEnvironmentAddons

cmd/integrationArtifactDeploy_generated.go, cmd/integrationArtifactGetMplStatus_generated.go, cmd/integrationArtifactGetServiceEndpoint_generated.go, cmd/integrationArtifactUpload_generated.go, resources/metadata/integrationArtifactDeploy.yaml, resources/metadata/integrationArtifactGetMplStatus.yaml, resources/metadata/integrationArtifactGetServiceEndpoint.yaml, resources/metadata/integrationArtifactUpload.yaml
=> Fix docu typos

documentation/docs/pipelines/abapEnvironment/configuration.md, documentation/docs/pipelines/abapEnvironment/stages/cloneRepositories.md
AddonBuild strategy is deprecated and should be removed from documentation
=> AddonBuild = deprecated

cmd/whitesourceExecuteScan.go
=> fix(whitesourceExecuteScan): Add retry capability for download

cmd/protecodeExecuteScan.go, cmd/protecodeExecuteScan_generated.go, cmd/protecodeExecuteScan_test.go, resources/metadata/protecode.yaml
align versioning parameter
related to #1846
=> feat(protecode): rename artifactVersion to version

documentation/docs/steps/whitesourceExecuteScan.md
=> docs: Removed obsolete scanType, add buildTool

cmd/uiVeri5ExecuteTests_generated.go, resources/metadata/uiVeri5ExecuteTests.yaml
=> docs: Improve guidance for testOptions migration

documentation/docs/scenarios/abapEnvironmentAddons.md
=> Update limitations in abapEnvironmentAddons

cmd/pipelineCreateScanSummary.go, cmd/pipelineCreateScanSummary_generated.go, cmd/pipelineCreateScanSummary_test.go, resources/metadata/pipelineCreateScanSummary.yaml
=> feat(pipelineCreateSummary): enhance content with reference link

LICENSE
Use license text from https://choosealicense.com/licenses/apache-2.0/
fixes #2852
=> chore(license): update LICENSE text

pkg/jenkins/jenkins.go, pkg/jenkins/jenkins_test.go, pkg/jenkins/mocks/Jenkins.go
=> fix(jenkins): correct interface

cmd/whitesourceExecuteScan.go
=> fix(whitesourceExecuteScan): Amend setting client options

.github/workflows/release-go.yml, .github/workflows/upload-go-master.yml
Make binaries available also for 
* MAC (darwin x86_64)
* Windows (win x86_64)
=> chore: release binaries for darwin and win

.github/workflows/release-go.yml
* fix the current release build ( the downloads were overwriting each other) 
* removed the copying of the downloaded files for windows and darwin since only one of the files is being used.  (just name the downloads correctly)
=> Fix: publish release workflow

vars/readPipelineEnv.groovy, vars/writePipelineEnv.groovy
* add more null checks in read and write pipeline env
=> fix(cpe): add more null checks in read and writePipelineEnv

vars/commonPipelineEnvironment.groovy, vars/writePipelineEnv.groovy
fixes StackOverflowError occuring when cpe contains `null` values in the JSON
=> fix(commonPipelineEnvironment): StackOverflowError

cmd/npmExecuteScripts_generated.go, resources/metadata/npmExecuteScripts.yaml
- Use docker image with CAs installed so Vault lookup works
=> fix(npmExecuteScripts): replace docker image by one that has CAs installed

cmd/writePipelineEnv.go
- consume pipeline variable from env variable if set. Old behaviour otherwise
=> feat(commonPipelineEnv): consume pipeline environment from env variable if set 

pkg/piperenv/CPEMap.go
- make sure all directories have the correct permissions
=> fix(commonPipelineEnvironment): make sure files and directories have the correct permissions

vars/writePipelineEnv.groovy
* Pass Piper Environment JSON via env variable instead of STDIN
=> feat(commonPipelineEnvironment): pass environment JSON via instead of STDIN

cmd/mavenBuild.go, cmd/mavenBuild_generated.go, cmd/mavenBuild_test.go, resources/metadata/mavenBuild.yaml
=> feat(mavenBuild): accept build profiles

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_test.go
Reverts SAP/jenkins-library#2916
=> Revert "fix(fortifyExecuteScan): Support MTA interdepedencies"

cmd/integrationArtifactTriggerIntegrationTest_generated.go, cmd/integrationArtifactTriggerIntegrationTest_test.go, resources/metadata/integrationArtifactTriggerIntegrationTest.yaml
=> CPI- Remove platform from triggerIntegration step

cmd/integrationArtifactDeploy_generated.go, cmd/integrationArtifactDownload_generated.go, cmd/integrationArtifactGetMplStatus_generated.go, cmd/integrationArtifactGetServiceEndpoint_generated.go, cmd/integrationArtifactTriggerIntegrationTest_generated.go, cmd/integrationArtifactUpdateConfiguration_generated.go, cmd/integrationArtifactUpload_generated.go, resources/metadata/integrationArtifactDeploy.yaml, resources/metadata/integrationArtifactDownload.yaml, resources/metadata/integrationArtifactGetMplStatus.yaml, resources/metadata/integrationArtifactGetServiceEndpoint.yaml, resources/metadata/integrationArtifactTriggerIntegrationTest.yaml, resources/metadata/integrationArtifactUpdateConfiguration.yaml, resources/metadata/integrationArtifactUpload.yaml, vars/integrationArtifactTriggerIntegrationTest.groovy
1. Improve iFlow serviceKey credential ID name
2. Improve overall description of CPI serviceKeys
=> CPI - Improve serviceKey parameter name and description

cmd/transportRequestUploadCTS.go, cmd/transportRequestUploadCTS_generated.go, cmd/transportRequestUploadCTS_test.go, resources/metadata/transportRequestUploadCTS.yaml
This PR improves the go code of the step cmd/transportRequestUploadCTS.go regarding
- support common pipeline environment
- support docker image
- aliases
- help text
Scope: GO code only
Risk: low
=> CTS Upload Go

cmd/integrationArtifactGetMplStatus.go, cmd/integrationArtifactGetMplStatus_test.go
1. Add DISCARDED state in query filter for IntegrationArtifactGetMplStatus command
=> Integration Artifact command Fixes

documentation/docs/scenarios/abapEnvironmentAddons.md
=> add-on product name should only include uppercase characters

cmd/piper.go, cmd/piper_test.go
=> chore: export GitHub token unmarshalling

cmd/integrationArtifactUpload.go, cmd/integrationArtifactUpload_generated.go, cmd/integrationArtifactUpload_test.go, documentation/docs/steps/integrationArtifactUpload.md, pkg/cpi/mockingUtils.go, resources/metadata/integrationArtifactUpload.yaml
1. Change the API from IntegrationDesigntimeArtifactSaveAsVersion to  IntegrationDesigntimeArtifacts  for Update operation 
2. Remove integration flow version and use "Active"
=> integrationArtifactUpload Fixes

documentation/mkdocs.yml
Change SAP Cloud Platform ABAP Environment to SAP BTP, ABAP Environment
=> Change SCP to BTP in titles of ABAP Environment Pipeline scenarios

cmd/pipelineCreateScanSummary.go
=> chore(pipelineCreateScanSummary): update issue text

cmd/integrationArtifactDeploy.go, cmd/integrationArtifactDeploy_generated.go, cmd/integrationArtifactDeploy_test.go, documentation/docs/steps/integrationArtifactDeploy.md, pkg/cpi/mockingUtils.go, resources/metadata/integrationArtifactDeploy.yaml
The version is not really necessary, and the name is not used anyway.
=> CPI - Remove iFlow version

documentation/docs/steps/gitopsUpdateDeployment.md, documentation/mkdocs.yml
=> Create missing documentation for step gitopsUpdateDeployment

cmd/integrationArtifactGetMplStatus.go
=> handle nil jsonResult

documentation/docs/scenarios/abapEnvironmentAddons.md
Add further details with regards to troubleshooting and permanent system
Order of steps in troubleshooting table adjusted
=> Update troubleshooting/permanent system in abapEnvironmentAddons.md

documentation/docs/scenarios/abapEnvironmentTest.md
- Let's have same structure here as in scenario with add-on build with "example section"
- Let's align wording for transient and permanent system
=> Continuous Testing on SAP BTP, ABAP Environment: Separate section for example

cmd/cloudFoundryDeploy.go, cmd/cloudFoundryDeploy_generated.go, cmd/cloudFoundryDeploy_test.go, documentation/docs/steps/cloudFoundryDeploy.md, resources/metadata/cloudFoundryDeploy.yaml
This PR adds the CommitHash of the current build to the deployment details written into the influx database.
=> CommitHash for deployment details in influx

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_generated.go, resources/metadata/fortify.yaml
Added new influx field containing the SSC projectVersionId
=> Enhance fortify influx data

src/com/sap/piper/Utils.groovy
=> Adds retry mechanism for JNLP4-connect issues in unstash function

pkg/config/evaluation.go, pkg/config/evaluation_test.go
=> fix(checkIfStepActive): respect explicit (de-)activation

pkg/fortify/reporting.go
=> fortifyExecuteScan: Fix overall report status

cmd/checkmarxExecuteScan.go, cmd/checkmarxExecuteScan_test.go
=> checkmarxExecuteScan: Improve error message on compliance issues

test/groovy/templates/PiperPipelineStageInitTest.groovy, vars/piperPipelineStageInit.groovy
- [ x]  Tests
- [ x] Documentation
=> Enables skipping the checkout in piperPipelineInitStage step by providing stashes

cmd/cnbBuild.go, cmd/cnbBuild_test.go, documentation/docs/steps/cnbBuild.md, integration/integration_cnb_test.go
Added documentation for custom builders and checks for correct builder image. In case if provided image is not a real builder, meaningful error will be raised.
#3020
=> cnbBuild documentation for custom builders

resources/default_pipeline_environment.yml
=> Add default for cnbBuild step to not stash back anything

cmd/abapEnvironmentAssemblePackages.go
=>  Update Assemble Package with Package Type

documentation/docs/scenarios/abapEnvironmentAddons.md
to correct formatting of caution box
=> Fix caution box in add-on build scenario

documentation/docs/scenarios/abapEnvironmentAddons.md
Further details regarding versioning limitations
=> Update abapEnvironmentAddons.md: Further version limitations

cmd/cnbBuild.go, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/project/project.toml, pkg/cnbutils/project/descriptor.go, pkg/cnbutils/project/descriptor_test.go
=> fix(cnbBuild): use relative path for filtering files

cmd/abapAddonAssemblyKitReserveNextPackages.go
=> add missing spaces in error message

cmd/integrationArtifactDeploy.go, cmd/integrationArtifactDownload.go, cmd/integrationArtifactGetMplStatus.go, cmd/integrationArtifactGetServiceEndpoint.go, cmd/integrationArtifactResource.go, cmd/integrationArtifactUnDeploy.go, cmd/integrationArtifactUpdateConfiguration.go, cmd/integrationArtifactUpload.go
Fix for CPI (Integration Artifact) steps print out bytes in error case #3121
=> IntegrationArtifact Fixes for issue #3121

cmd/cnbBuild.go, cmd/cnbBuild_test.go, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/project/project.toml
=> fix(cnbBuild): exclude registry domain from the imageNameTag CPE field

integration/integration_cnb_test.go
Reactivates integration test cnb_test.
=> Removes t.Skip() and activates integration test

documentation/docs/scenarios/abapEnvironmentAddons.md
Minor changes to wording/typos
=> Update abapEnvironmentAddons.md: Minor changes to wording/typos

vars/sonarExecuteScan.groovy
=> feat(sonar): use go-based certificate loading

cmd/cnbBuild.go, cmd/cnbBuild_generated.go, cmd/cnbBuild_test.go, documentation/docs/steps/cnbBuild.md, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/config_env.yml, pkg/cnbutils/env.go, pkg/cnbutils/env_test.go, pkg/cnbutils/project/descriptor.go, pkg/cnbutils/project/descriptor_test.go, resources/metadata/cnbBuild.yaml
refactored buildEnvVars input argument (merging with the variables defined in a project descriptor file), added `resourceRef` to the `buildpacks` argument.
=> feat(cnbBuild): refactored buildEnvVars, buildpacks input properties

documentation/docs/pipelines/abapEnvironment/configuration.md
=> Remove explicit SAP_COM_* configuration

cmd/cnbBuild_generated.go, resources/metadata/cnbBuild.yaml
=> added the beta notification for cnbBuild step

cmd/whitesourceExecuteScan_generated.go, resources/metadata/whitesourceExecuteScan.yaml
=> Fix alias definition for agentUrl

test/groovy/CnbBuildTest.groovy, vars/cnbBuild.groovy
=> fix(cnbBuild): failOnError

pkg/documentation/generator/main.go, pkg/documentation/generator/main_test.go
* remove unnecessary sections in case stage does not contain steps (e.g. confirm stage)
* improve readibiliy of condition section
* fix naming
=> doc: improve stage documentation

cmd/malwareExecuteScan_generated.go, resources/metadata/malwareExecuteScan.yaml
Adds support to resolve credentials for the malware service from vault.
=> feat(malwareExecuteScan): support for vault

cmd/sonarExecuteScan_generated.go, resources/metadata/sonarExecuteScan.yaml
**changes**
- correct the VaultSecretName for the sonar token
=> fix(sonar): correct VaultSecretName

pkg/docker/docker.go
=> fix (dockerconfigjson)  correct directory permission

cmd/abapEnvironmentRunAUnitTest.go, cmd/abapEnvironmentRunAUnitTest_test.go, documentation/docs/pipelines/abapEnvironment/stages/Test.md, documentation/docs/steps/abapEnvironmentRunAUnitTest.md
=> Unify config for ATC/AUnit

test/groovy/templates/AbapEnvironmentPipelineStageInitTest.groovy, vars/abapEnvironmentPipelineStageInit.groovy
Hello Colleagues,
please refer to the changes required. We had issues with **stash** but that should be fixed with this PR.
=> fix stash and adapt unit tests accordingly

pkg/config/vault.go
Closes #3438
not required
not required
=> Fix typo: these are not test credentials

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_test.go
=> Fix potential nil reference

cmd/fortifyExecuteScan.go
=> Address further nil references

cmd/gradleExecuteBuild_generated.go, resources/metadata/gradleExecuteBuild.yaml
=> Update gradle version

cmd/gradleExecuteBuild_generated.go, resources/metadata/gradleExecuteBuild.yaml
=> Update image for gradle build

cmd/cnbBuild.go, cmd/cnbBuild_test.go, pkg/cnbutils/privacy/privacy.go, pkg/cnbutils/privacy/privacy_test.go
=> collecting the telemetry data for cnbBuild

cmd/cnbBuild.go, cmd/cnbBuild_test.go
Do not write the complete path to telemetry, but rather if it was used at all and if an archive was targeted.
=> fix(cnbBuild) do not add complete path to telemetry

documentation/docs/scenarios/abapEnvironmentAddons.md
Clarify delta calculation depending on different delivery package types
=> Clarify delta calculation of different package types

cmd/mavenBuild_generated.go, cmd/mtaBuild_generated.go, cmd/npmExecuteScripts_generated.go, resources/metadata/mavenBuild.yaml, resources/metadata/mtaBuild.yaml, resources/metadata/npmExecuteScripts.yaml
=> fix (build dependency) typo corrections

cmd/golangBuild_generated.go, resources/metadata/golangBuild.yaml
Just a minor one. It must be `repositoryUrl` instead of `repositoryURL`
=> fix(golangBuild): targetRepositoryUrl

pkg/http/http.go
=> fix(httpclient): folder permissions

cmd/golangBuild.go, cmd/golangBuild_test.go
Staging repo expects PUT instead of POST.
=> fix(golangBuild): use PUT instead of POST

cmd/golangBuild.go, cmd/golangBuild_generated.go, cmd/golangBuild_test.go, resources/metadata/golangBuild.yaml
Artifacts shall be published into a subfolder in the target repository like:
`/go/<modulename>/<version>/<binaryname>`
=> feat(golangBuild): publish to subfolder

cmd/golangBuild.go, cmd/golangBuild_test.go
Staging repo returns with status 201 instead of 200.
=> fix(golangBuild): expect status 201 instead of 200

cmd/sonarExecuteScan.go, pkg/sonar/componentService.go, pkg/sonar/report.go, pkg/sonar/report_test.go
- [ x ] Tests
- [ x ] Documentation
=> fix(sonarExecuteScan): error handling for report metrics of pullRequests

.pipeline/config.yml, cmd/golangBuild.go, cmd/golangBuild_generated.go, cmd/golangBuild_test.go, resources/metadata/golangBuild.yaml
Was implemented BOM creation using CycloneDX.
=> feat(golangBuild): add BOM creation

cmd/golangBuild.go, cmd/golangBuild_test.go
Fixes
```
11:36:38  info  golangBuild - go: downloading github.com/CycloneDX/cyclonedx-gomod v1.2.0
11:36:38  info  golangBuild - go install: github.com/CycloneDX/cyclonedx-gomod@latest: module github.com/CycloneDX/cyclonedx-gomod@latest found (v1.2.0), but does not contain package github.com/CycloneDX/cyclonedx-gomod
```
=> fix(golangBuild): cyclonedx-gomod import path

documentation/docs/pipelines/abapEnvironment/extensibility.md, documentation/docs/pipelines/abapEnvironment/stages/Test.md, documentation/docs/scenarios/abapEnvironmentAddons.md, documentation/docs/scenarios/abapEnvironmentTest.md
Additional ATC check details.  In particular different quality gate configuration for add-on build scenario.
=> Update ATC Check details for add-on build scenario

cmd/cnbBuild.go, cmd/getConfig.go
=> Collect buildTool in cnbBuild metrics

cmd/cnbBuild.go, cmd/cnbBuild_test.go, cmd/getConfig.go, pkg/cnbutils/privacy/privacy.go, pkg/cnbutils/privacy/privacy_test.go, pkg/config/config.go
=> feat(cnbBuild): added dockerimage to the telemetry data

cmd/golangBuild.go, cmd/golangBuild_generated.go, cmd/golangBuild_test.go, pkg/buildsettings/buildSettings.go, pkg/buildsettings/buildSettings_test.go, resources/metadata/golangBuild.yaml
=> feat(buildsettings): golang and future tools

documentation/docs/scenarios/abapEnvironmentAddons.md
2202 release is live, no more branching limitation
=> Remove branching limitation

integration/testdata/TestCnbIntegration/project/package.json, integration/testdata/TestMtaIntegration/npm/package.json
=> fix(cnbBuild): fixed nodejs integration tests

integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/project/project.toml
=> pinned builder and buildpacks versions for cnbBuild integration tests

cmd/checkmarxExecuteScan.go, cmd/checkmarxExecuteScan_generated.go, resources/metadata/checkmarxExecuteScan.yaml
=> Add toggle for GH issue creation

cmd/kanikoExecute_generated.go, resources/metadata/kanikoExecute.yaml
=> fix(kanikoExecute) Apply workaround for multi stage builds

cmd/cnbBuild.go, cmd/kubernetesDeploy_test.go, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/config.yml
=> bug(cnbBuild) Skip restoring image content

cmd/cnbBuild.go, cmd/cnbBuild_test.go, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/config.yml, integration/testdata/TestCnbIntegration/config_env.yml, integration/testdata/TestCnbIntegration/config_multi_image.yml, integration/testdata/TestCnbIntegration/config_preserve_files.yml
=> fix(cnbBuild): filter overall buildpacks key in the telemetry data

cmd/cnbBuild_generated.go, pkg/cnbutils/target_image.go, pkg/cnbutils/target_image_test.go, resources/metadata/cnbBuild.yaml
=> feat(cnbBuild) read target image name from github cpe

cmd/whitesourceExecuteScan_generated.go, pkg/whitesource/configHelper.go, resources/metadata/whitesourceExecuteScan.yaml
=> chore(whitesourceExecuteScan): Gradle config changes

documentation/docs/guidedtour.md, documentation/docs/infrastructure/customjenkins.md
=> Removing deprecated cx-server from doc

cmd/mavenBuild.go
=> fix (mavenBuild) adding resilience to maven install / verify 

pkg/orchestrator/orchestrator.go, pkg/orchestrator/orchestrator_test.go, pkg/splunk/splunk.go
Activates debug information for environment variables in the orchestrator package.
=> Activates debug information for environment variables

cmd/abapEnvironmentCheckoutBranch_generated.go, cmd/abapEnvironmentCloneGitRepo_generated.go, cmd/abapEnvironmentCreateSystem_generated.go, cmd/abapEnvironmentPullGitRepo_generated.go, resources/metadata/abapEnvironmentCheckoutBranch.yaml, resources/metadata/abapEnvironmentCloneGitRepo.yaml, resources/metadata/abapEnvironmentCreateSystem.yaml, resources/metadata/abapEnvironmentPullGitRepo.yaml
=> Change metadata: Cloud Platform -> BTP

cmd/containerSaveImage_generated.go, cmd/golangBuild_generated.go, cmd/helmExecute_generated.go, cmd/kubernetesDeploy_generated.go, cmd/malwareExecuteScan_generated.go, cmd/mavenBuild_generated.go, cmd/mtaBuild_generated.go, cmd/npmExecuteScripts_generated.go, cmd/whitesourceExecuteScan_generated.go, pkg/config/stepmeta.go, pkg/config/stepmeta_test.go, resources/metadata/containerSaveImage.yaml, resources/metadata/golangBuild.yaml, resources/metadata/helmExecute.yaml, resources/metadata/kubernetesDeploy.yaml, resources/metadata/malwareExecuteScan.yaml, resources/metadata/mavenBuild.yaml, resources/metadata/mtaBuild.yaml, resources/metadata/npmExecuteScripts.yaml, resources/metadata/whitesourceExecuteScan.yaml
=> feat: support cpe credentials for multiple repos

cmd/fortifyExecuteScan.go, pkg/format/sarif.go, pkg/fortify/fpr_to_sarif.go, pkg/fortify/fpr_to_sarif_test.go, pkg/fortify/reporting.go, pkg/whitesource/reporting.go
- Added parameter for the issue category in generated SARIF files, in properties
- Adapted SARIF format for better handling of missing objects (omitempty)
- Adapted unit tests to check new returns
=> feat(fortifyExecuteScan): added parameter to generated sarif file

integration/integration_cnb_test.go
=> chore(cnbBuild) unify integration test args

test/groovy/CommonStepsTest.groovy, vars/helmExecute.groovy
=> Add helmExecute.groovy

pkg/orchestrator/azureDevOps.go, pkg/orchestrator/azureDevOps_test.go
=> fix(orchestrator) reuse of SOURCEBRANCH

integration/integration_golang_test.go, integration/integration_gradle_test.go, integration/integration_maven_test.go
currently integration test run for ~25 min , trying to include some parallel execution within the test to improve the performance
=> feat (integration test) improve performance 

cmd/containerSaveImage_test.go, cmd/malwareExecuteScan_test.go, cmd/protecodeExecuteScan_test.go, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/config_multi_image.yml, pkg/cnbutils/buildpack.go, pkg/cnbutils/buildpack_test.go, pkg/cnbutils/mock.go, pkg/cnbutils/report.go, pkg/docker/docker.go, pkg/mock/dockerClient.go, pkg/piperutils/FileUtils.go
* custom buildpacks will be re-used during a multi-image build
=> feat(cnbBuild): cache buildpacks during multi-image build

.github/workflows/release-go.yml
Correct release creation to create release only once.
=> fix(release process): correct copy&paste issue

cmd/cnbBuild.go
=> feat(cnbBuild): exclude .git folder from cnb workspace by default

documentation/mkdocs.yml
=> add abapEnvironmentPushATCSystemConfig to mkdocs

cmd/mavenBuild.go
=> fix (mavenBuild) changing trust store permission

.github/workflows/release-go.yml
Reverts SAP/jenkins-library#3719
=> chore(release): publish all binaries with one piper step

documentation/mkdocs.yml
Added a scenario documentation for usage of gcts pipeline steps.
=> Added scenario for gcts pipeline steps

pkg/documentation/generator/defaults.go, pkg/documentation/generator/parameters.go
=> fix (docu) default value for dockerImage when no conditions 

pkg/whitesource/configHelper.go, pkg/whitesource/configHelper_test.go
Update log level to trace when verbose is set to true
=> whitesourceExecuteScan : add log level trace

pkg/checkmarx/cxxml_to_sarif.go, pkg/checkmarx/reporting.go, pkg/fortify/fpr_to_sarif.go, pkg/fortify/fpr_to_sarif_test.go, pkg/fortify/reporting.go
Added new logging messages to ensure easier debugging for teams that would use the SARIF converter
=> feat(sarif): logging improvements

pkg/abap/build/bfw.go
=> enableBuildWithoutValues

pkg/kubernetes/helm.go, pkg/kubernetes/helm_test.go
=> fix runHelmAdd

.gitignore, cmd/abapEnvironmentRunATCCheck.go, cmd/abapEnvironmentRunATCCheck_generated.go, cmd/abapEnvironmentRunATCCheck_test.go, cmd/abapEnvironmentRunAUnitTest.go, cmd/abapEnvironmentRunAUnitTest_test.go, pkg/abaputils/osl.go, resources/metadata/abapEnvironmentRunATCCheck.yaml
=> Feature: ATC & AUNIT - ObjectSetLibrary(OSL) usage

.github/CODEOWNERS
=> Extend codeowners (ABAP)

.gitignore, documentation/docs/pipelines/abapEnvironment/stages/cloneRepositories.md
=> Fix .gitignore

cmd/golangBuild.go, cmd/golangBuild_generated.go, pkg/versioning/gomodfile.go, resources/metadata/golangBuild.yaml
=> Golang build publish binaries and add group id

vars/abapEnvironmentPipelineStageIntegrationTests.groovy, vars/abapEnvironmentPipelineStagePost.groovy
=> Add debug flag to stage config

documentation/docs/scenarios/abapEnvironmentAddons.md
Add-on Registration is now in Landscape Portal app, remove process description for service request
=> Add-on Registration now in Landscape Portal app

pkg/abaputils/abaputils.go, pkg/abaputils/manageGitRepositoryUtils.go, pkg/abaputils/manageGitRepositoryUtils_test.go
=> Handle empty http response correctly

cmd/cnbBuild.go, cmd/cnbBuild_generated.go, cmd/cnbBuild_test.go, pkg/buildsettings/buildSettings.go, pkg/buildsettings/buildSettings_test.go, resources/metadata/cnbBuild.yaml
=> feat(cnbBuild): generate buildSettingInfo

pkg/checkmarx/cxxml_to_sarif.go, pkg/format/sarif.go, pkg/fortify/fpr_to_sarif.go
- Add ruleGUID as part of the results property bag (for Checkmarx: QueryID)
- Fortify ruleID pattern changed from fortify-kingdom/class/subclass to fortify-class/subclass
- Checkmarx ruleID pattern changed from checkmarx-queryID to checkmarx-language/queryID
=> feat(sarif): add GUID as part of properties, change ruleID 

DEVELOPMENT.md, Dockerfile, src/com/sap/piper/PiperGoUtils.groovy
This PR upgrades the "Dockerfile" to go 1.18.
=> Upgrade Dockerfile to Go 1.18

pkg/checkmarx/cxxml_to_sarif.go
- Removed an useless code block
- Added the "Security-Severity" parameter for Checkmarx SARIF to show severity on GHAS uploads
=> feat(checkmarxExecuteScan): SARIF code cleanup, added security-severity

cmd/kubernetesDeploy_generated.go, resources/metadata/kubernetesDeploy.yaml
=> kubernetesDeploy: mark the image parameter as deprecated

pkg/orchestrator/azureDevOps.go, pkg/orchestrator/gitHubActions.go, pkg/orchestrator/jenkins.go, pkg/orchestrator/jenkins_test.go, pkg/orchestrator/orchestrator.go, pkg/orchestrator/unknownOrchestrator.go
Adds GetChangeSet functionality to Jenkins orchestrator to retrieve change set information e.g. which PR(s) have been build in that pipeline run.
=> feat(orchestrator package) Adds GetChangeSet functionality to Jenkins provider

vars/piperPipelineStageInit.groovy
Mention explicitly 'productiveBranch' to be a fixed branch name
=> fix(docu): Mention productiveBranch to be a fixed branch name

cmd/abapEnvironmentCreateTag_generated.go, resources/metadata/abapEnvironmentCreateTag.yaml
=> Add alias to CreateTag

pkg/log/ansHook.go, pkg/log/ansHook_test.go
=> [ANS] remove Pipeline word in subject

vars/commonPipelineEnvironment.groovy
=> feat (commonPipelineEnvironment) enhance the cpe map to read git head commit id 

cmd/cnbBuild_generated.go, resources/metadata/cnbBuild.yaml
=> docs(cnbBuild): use correct address for the buildpacks in the example

.github/workflows/upload-go-master.yml
=> feat (release process) publishing master binary once after all builds

cmd/githubPublishRelease.go
=> feat (githubPublishRelease) creating release with assestPathList

.github/workflows/upload-go-master.yml
Reverts SAP/jenkins-library#3885
=> Revert "feat (release process) publishing master binary once after all builds"

cmd/abapAddonAssemblyKitReserveNextPackages_generated.go, resources/metadata/abapAddonAssemblyKitReserveNextPackages.yaml
=> Fix documentation for abapAddonAssemblyKitReserveNextPackages

documentation/docs/configuration.md
=> [ANS] Fix ANS hook configuration documentation

integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/project/project-with-id.toml, integration/testdata/TestCnbIntegration/project/project.toml
=> cnbBuild: update buildpack versions for integration tests

pkg/log/url.go
=> url log permission hotfix

pkg/whitesource/whitesource.go
=> fix: addig correct ws api call

pkg/orchestrator/jenkins.go, pkg/orchestrator/jenkins_test.go, pkg/orchestrator/orchestrator.go
Read the complete changeSet list from Jenkins API
=> fix: complete changeSet list

cmd/checkmarxExecuteScan.go, cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_test.go
- Improve checkmarx logs
- Fortify spotcheck logic consistent with checkmarx low
=> fix(fortify): Fortify spotcheck logic consistent with checkmarxs low

pkg/config/evaluation.go, pkg/config/evaluation_test.go
Co-authored-by: Raman Susla <raman_susla@epam.com>
Co-authored-by: Ashly Mathew <ashly.mathew@sap.com>
=> fix(checkIfStepActive): nested key logic

cmd/whitesourceExecuteScan.go, pkg/whitesource/reporting.go, pkg/whitesource/reporting_test.go, pkg/whitesource/testdata/sbom.golden, pkg/whitesource/whitesource.go, pkg/whitesource/whitesource_test.go
=> Fix SBOM component generation

pkg/fortify/fortify_test.go, pkg/fortify/reporting.go
json report new flag **isSpotChecksPerCategoryAudited** for spotchecks
=> feat(fortifyExecuteScan): json report new flag

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_generated.go, cmd/fortifyExecuteScan_test.go, resources/metadata/fortifyExecuteScan.yaml
set python version to sourceanalyzer translate
=> feat(fortifyExecuteScan): set python version

cmd/githubPublishRelease_generated.go, resources/metadata/githubPublishRelease.yaml, vars/githubPublishRelease.groovy
Signed-off-by: Ashly Mathew <ashly.mathew@sap.com>
Relates to #3355
=> Changes to point release commitish to head commit

pkg/config/vault.go
=> fix: register base64 encoded secret

pkg/config/evaluation.go, resources/com.sap.piper/pipeline/abapEnvironmentPipelineStages.yml, resources/com.sap.piper/pipeline/stageDefaults.yml, test/groovy/templates/AbapEnvironmentPipelineStageInitTest.groovy, test/groovy/templates/PiperInitRunStageConfigurationTest.groovy, vars/piperExecuteBin.groovy, vars/piperInitRunStageConfiguration.groovy
- stageDefaults modified to V1 format
- Enable Jenkins to use go step
- Remove duplicate groovy code
Depends on 
https://github.com/SAP/jenkins-library/pull/3939
=> Enable Jenkins to use checkIfStepActive go step

cmd/checkIfStepActive.go, vars/piperExecuteBin.groovy, vars/piperInitRunStageConfiguration.groovy
=> Fix for checkIfStepActive custom config

cmd/helmExecute.go, cmd/helmExecute_generated.go, resources/metadata/helmExecute.yaml
Rename ```CPE``` output ```custom/remoteHelmChartPath``` to ```custom/helmChartUrl```
=> helmExecute: rename ```remoteHelmChartPath``` to ```helmChartUrl```

resources/default_pipeline_environment.yml, test/groovy/NpmExecuteEndToEndTestsTest.groovy, test/groovy/templates/PiperPipelineStageAcceptanceTest.groovy, vars/npmExecuteEndToEndTests.groovy, vars/piperPipelineStageAcceptance.groovy
=> Set script 'ci-e2e' as default for acceptance stage

test/groovy/NpmExecuteEndToEndTestsTest.groovy, vars/npmExecuteEndToEndTests.groovy
Without this change, pipeline runs on the node, even though it is running on kubernetes but still pod name is not set.
~- [ ] Documentation~
=> [E2E Tests step] Allow Conditional check with on_k8s env variable

test/groovy/templates/PiperPipelineStageAcceptanceTest.groovy, vars/piperPipelineStageAcceptance.groovy
Using already existing step `npmExecuteEndToEndTests` to run wdi5 tests.
=> Revert changes from PR #3982

test/groovy/NpmExecuteEndToEndTestsTest.groovy, vars/npmExecuteEndToEndTests.groovy
I'm testing adaptations to see if we can get this step to work for us
=> Adapt npmExecuteEndToEndTests

.github/workflows/consumer-tests-pr.yml, .github/workflows/consumer-tests.yml, .github/workflows/integration-tests-pr.yml
- Integration tests workflow fix
- Timeout for integration tests execution decreased to 10 min
- Consumer tests moved to separate workflow
Integration tests workflow execution time reduced from 25+ min to ~9 min
[![Integration tests](https://github.com/SAP/jenkins-library/actions/workflows/integration-tests.yml/badge.svg)](https://github.com/SAP/jenkins-library/actions/workflows/integration-tests.yml)
=> Integration tests workflow fix

.github/workflows/consumer-tests-pr.yml, .github/workflows/consumer-tests.yml, .github/workflows/integration-tests-pr.yml, .github/workflows/integration-tests.yml, .github/workflows/parse_integration_test_list.go, go.mod, integration/github_actions_integration_test_list.yml
* Dynamic version detection of Golang 
* Dynamic Golang integration tests run matrix
* Golang timeout to build set at 5 min
* Golang integration test timeout to run set at 10 min
* Consumer tests timeout set at 20 min
=> (feat) Golang integration tests dynamic workflow

pkg/cnbutils/sbom.go
=> cnbBuild: Remove leftover Printf

documentation/docs/scenarios/abapEnvironmentAddons.md
Change documentation to reuse software component before leading software component in order of addon.yml file
=> Reuse software component before leading software component

cmd/detectExecuteScan.go, cmd/detectExecuteScan_test.go, pkg/blackduck/blackduck.go, pkg/blackduck/reporting.go, pkg/blackduck/reporting_test.go, pkg/checkmarx/cxxml_to_sarif.go, pkg/format/assessment.go, pkg/format/sarif.go, pkg/fortify/fpr_to_sarif.go
=> Fix(detectExecuteScan): rework struct methods to meet interface requirements

resources/com.sap.piper/pipeline/abapEnvironmentPipelineDefaults.yml
=> Adapt default

cmd/whitesourceExecuteScan.go, cmd/whitesourceExecuteScan_test.go, pkg/format/assessment.go, pkg/whitesource/reporting.go, pkg/whitesource/reporting_test.go, pkg/whitesource/whitesource.go
=> fix(whitesourceExecuteScan): Fix processing of assessment

cmd/cnbBuild.go, cmd/cnbBuild_generated.go, cmd/cnbBuild_test.go, resources/metadata/cnbBuild.yaml
=> feat(cnbBuild) Allow run-image to be specified

cmd/sonarExecuteScan_generated.go, resources/metadata/sonarExecuteScan.yaml
=> sonarExecuteScan: update sonar image version

cmd/gradleExecuteBuild.go, cmd/gradleExecuteBuild_generated.go, resources/metadata/gradleExecuteBuild.yaml
=> Update gradle execute build

cmd/abapEnvironmentRunATCCheck.go, cmd/abapEnvironmentRunATCCheck_test.go
Improved failOnSeverity Handling with more suitable error message
Unit Tests
=> Corr atc fail on severity

cmd/abapEnvironmentPushATCSystemConfig.go
=> Corr push atc conf - more consistent error handling

cmd/cnbBuild.go
=> cnbBuild: temporary remove experimental createBOM feature

.github/workflows/documentation.yml
=> fix(workflow): pin mkdocs-material version to v8.5.11

cmd/kanikoExecute_test.go, integration/integration_cnb_test.go, pkg/syft/syft.go, pkg/syft/syft_test.go
=> fix(syft): correctly set DOCKER_CONFIG env variable

cmd/abapEnvironmentCheckoutBranch_generated.go, cmd/abapEnvironmentCloneGitRepo_generated.go, cmd/abapEnvironmentCreateSystem_generated.go, cmd/abapEnvironmentCreateTag_generated.go, cmd/abapEnvironmentPullGitRepo_generated.go, cmd/abapEnvironmentPushATCSystemConfig_generated.go, cmd/abapEnvironmentRunATCCheck_generated.go, cmd/abapEnvironmentRunAUnitTest_generated.go, resources/metadata/abapEnvironmentCheckoutBranch.yaml, resources/metadata/abapEnvironmentCloneGitRepo.yaml, resources/metadata/abapEnvironmentCreateSystem.yaml, resources/metadata/abapEnvironmentCreateTag.yaml, resources/metadata/abapEnvironmentPullGitRepo.yaml, resources/metadata/abapEnvironmentPushATCSystemConfig.yaml, resources/metadata/abapEnvironmentRunATCCheck.yaml, resources/metadata/abapEnvironmentRunAUnitTest.yaml
Reverts SAP/jenkins-library#4159
=> Revert "Increase docker image version"

resources/default_pipeline_environment.yml
See piper-ita issue 450.
This PR updates jnlp image for Open Source project defaults.
=> Update jnlp image

.github/workflows/integration-tests-pr.yml, .github/workflows/integration-tests.yml
=> Add TMS service key to environment in integration test workflow job

documentation/docs/steps/detectExecuteScan.md
=> added info for rapid scan in detectExecution

cmd/codeqlExecuteScan_generated.go, resources/metadata/codeqlExecuteScan.yaml
Added stashes for codeql metadata.
=> fix(codeql): added stashes

.github/workflows/verify-go.yml
Fixes the failing linting action by updating the go version for the action.
=> chore(pipeline): update linting action

cmd/artifactPrepareVersion_generated.go, resources/metadata/artifactPrepareVersion.yaml
Reverts SAP/jenkins-library#4226
=> Revert "artifactPrepareVersion: Add usage of gradle docker image if buildTool is gradle"

integration/github_actions_integration_test_list.yml, integration/integration_sonar_test.go
=> fix(sonar): update integration test

src/com/sap/piper/DockerUtils.groovy, test/groovy/ContainerPushToRegistryTest.groovy
The PR fixes #4771 inner-source GH issue
=> fix(containerPushToRegistry): Add possibility to copy image from private registry

cmd/helmExecute_generated.go, cmd/kubernetesDeploy_generated.go, resources/metadata/helmExecute.yaml, resources/metadata/kubernetesDeploy.yaml
I know floating tags are controversial, but as no one feels responsible for updating this regularly I guess this is just the best option, because using a version of helm that is more than a year old is also no good solution.
=> Use floating tag for helm images

cmd/codeqlExecuteScan.go, cmd/codeqlExecuteScan_generated.go, resources/metadata/codeqlExecuteScan.yaml
Added parameters threads and ram which can be set in pipeline config. Set threads to 0 by default
=> fix(codeqlExecuteScan): added parameters threads and ram

cmd/codeqlExecuteScan.go
Added logging codeql image version, refactored setting ram and threads parameters
=> feat(codeqlExecuteScan): added logging codeql version

cmd/golangBuild_generated.go, resources/metadata/golangBuild.yaml
=> golangBuild: Update golangci-lint version

cmd/containerExecuteStructureTests.go, cmd/containerExecuteStructureTests_generated.go, cmd/containerExecuteStructureTests_test.go, pkg/command/command.go, resources/metadata/containerExecuteStructureTests.yaml
=> chore (containerExecuteStructureTests): switch default container

cmd/mavenBuild_generated.go, resources/metadata/mavenBuild.yaml
Add ability to set "flatten: false" as a step parameter for mavenBuild.
=> Add Step scope for mavenBuild

cmd/codeqlExecuteScan_generated.go, resources/metadata/codeqlExecuteScan.yaml
=> docs(codeqlExecuteScan): Improve codeqlExecuteScan githubToken docs

cmd/abapEnvironmentCheckoutBranch_test.go, cmd/abapEnvironmentCloneGitRepo_test.go, cmd/abapEnvironmentPullGitRepo_test.go, pkg/abaputils/manageGitRepositoryUtils.go, pkg/abaputils/manageGitRepositoryUtils_test.go
=> Adapt to backend API changes

pkg/abaputils/manageGitRepositoryUtils.go, pkg/abaputils/manageGitRepositoryUtils_test.go
=> Improve logging for ABAP steps

resources/metadata/gradleExecuteBuild.yaml
Because of piper-doc issue 585 , and to create this PR.
=> Add description to long description for gradle step

cmd/codeqlExecuteScan.go, cmd/codeqlExecuteScan_test.go
=> fix(codeqlExecuteScan): checkForCompliance flag refactoring

src/com/sap/piper/DockerUtils.groovy, test/groovy/ContainerPushToRegistryTest.groovy, test/groovy/com/sap/piper/DockerUtilsTest.groovy
=> fix(containerPushToRegistry): add new --multi-arch=all flag to skopeo 

cmd/sonarExecuteScan_generated.go, resources/metadata/sonarExecuteScan.yaml
=> Upgrade sonar scanner cli image version to 4.8

cmd/detectExecuteScan.go, pkg/toolrecord/toolrecord.go
fix toolrun keys section; add timestamp in context to detect older files if needed
close #4365
=> detectExecuteScan: fix toolrun data

cmd/gradleExecuteBuild.go, integration/testdata/TestGradleIntegration/java-project-with-bom-plugin/build.gradle
Pin schema version of cyclonedx to 1.4
=> fix(Gradle): Pin schema version of cyclonedx

src/com/sap/piper/Utils.groovy, test/groovy/com/sap/piper/UtilsTest.groovy
There are a some methods related to stashing which are not unit tested.
With that pull-request we add some basic unit-tests.
=> stashing tests

cmd/cnbBuild.go, cmd/cnbBuild_generated.go, integration/docker_test_executor.go, integration/integration_cnb_test.go, integration/integration_gitops_test.go, integration/testdata/TestCnbIntegration/config.json, resources/metadata/cnbBuild.yaml
=> feat(cnbBuild): support setting registry username and password via parameters

cmd/cnbBuild.go, integration/integration_cnb_test.go, pkg/cnbutils/auth.go
=> fix(cnbBuild): correctly construct docker config using credentials

resources/default_pipeline_environment.yml
=> chore(stash): add .cds file for SAP CAP

cmd/codeqlExecuteScan.go, pkg/codeql/reporting.go
Added field querySuite to codeql audit report.
=> fix(codeqlExecuteScan): added querySuite to codeql audit report

cmd/checkmarxOneExecuteScan_generated.go, resources/metadata/checkmarxOneExecuteScan.yaml
=> fix(checkmarxOne): added missing report

documentation/docs/steps/dockerExecute.md, vars/dockerExecute.groovy, vars/dockerExecuteOnKubernetes.groovy
Added in minor changes to documentation to make it more understandable for users especially when trying to pull a private docker image via dockerExecute and dockerExecuteOnKubernetes
=> Enhance step documentation for docker groovy steps

cmd/golangBuild.go, cmd/golangBuild_test.go, integration/integration_golang_test.go
Added log for cyclonedx  command
=> adding verbose log of cyclonedx

cmd/cnbBuild.go, cmd/cnbBuild_test.go, pkg/buildpacks/buildpacks.go, pkg/buildpacks/telemetry.go
=> Refactor buildpacks telemetry

cmd/kanikoExecute.go, cmd/kanikoExecute_generated.go, cmd/kanikoExecute_test.go, resources/metadata/kanikoExecute.yaml
This PR adds the ability to run kanikoExecute step with multiple images build option (via kaniko sub-context feature)
=> kanikoExecute: add multiple build

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_generated.go, cmd/fortifyExecuteScan_test.go, pkg/fortify/fortify.go, pkg/fortify/fortify_test.go, resources/metadata/fortifyExecuteScan.yaml
=> feat(fortifyExecuteScan): Fortify proxy parameter

cmd/detectExecuteScan.go, cmd/detectExecuteScan_generated.go, resources/metadata/detectExecuteScan.yaml
=> added detect8 support

cmd/checkmarxOneExecuteScan.go, cmd/checkmarxOneExecuteScan_generated.go, cmd/checkmarxOneExecuteScan_test.go, cmd/golangBuild.go, pkg/checkmarxone/checkmarxone.go, pkg/checkmarxone/checkmarxone_test.go, pkg/checkmarxone/reporting.go, pkg/checkmarxone/reporting_test.go, resources/metadata/checkmarxOneExecuteScan.yaml
=> Cxone release supporting applications

documentation/docs/steps/dockerExecuteOnKubernetes.md
=> docs(dockerExecuteOnKubernetes): fixing broken example 3

pkg/checkmarxone/reporting_test.go
=> fix(cxone): fix test cases

documentation/docs/steps/karmaExecuteTests.md
=> fix(docs): add Karma deprecation notice

cmd/detectExecuteScan.go
=> removed detect npm args uppercase enforcement

cmd/detectExecuteScan.go, cmd/detectExecuteScan_test.go
=> detect-removed-temporary-unmap-enforcement

pkg/vault/client.go
=> chore(vault): custom retry check function

cmd/cnbBuild_test.go, cmd/getConfig.go, cmd/getConfig_test.go, cmd/getDefaults.go, cmd/kanikoExecute_test.go
Exporting generateConfig function and applying minor changes
=> feat(config): exporting generateConfig function and applying minor changes

cmd/artifactPrepareVersion.go, cmd/artifactPrepareVersion_generated.go, cmd/artifactPrepareVersion_test.go, pkg/certutils/certutils.go, pkg/certutils/certutils_test.go, pkg/orchestrator/gitHubActions_test.go, resources/metadata/artifactPrepareVersion.yaml
This PR adds the possibility to provide custom certificates via new customTlsCertificateLinks parameter.
=> artifactPrepareVersion: support custom certificates

cmd/gctsExecuteABAPQualityChecks.go
=> gCTSExecuteABAPQualityCheck_namespace_objects

cmd/cloudFoundryDeploy.go
=> Add warning message when cf native builds uses bg deployment

cmd/abapLandscapePortalUpdateAddOnProduct.go, cmd/abapLandscapePortalUpdateAddOnProduct_test.go
=> Abap environment update addon product

cmd/abapLandscapePortalUpdateAddOnProduct.go, cmd/abapLandscapePortalUpdateAddOnProduct_test.go
Reverts SAP/jenkins-library#4680
=> Revert "Abap environment update addon product"

cmd/cnbBuild.go, integration/integration_cnb_test.go, integration/testdata/TestCnbIntegration/project/project-with-id.toml, integration/testdata/TestCnbIntegration/project/project.toml
https://github.com/buildpacks/spec/releases/tag/platform%2Fv0.12
=> feat(cnbBuild): Bump `CNB_PLATFORM_API` to `0.12`

cmd/codeqlExecuteScan.go, cmd/codeqlExecuteScan_test.go
=> fix(codeqlExecuteScan): Fix for GlobalSettingsFile url checks

cmd/getConfig.go, cmd/getConfig_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/stepmeta.go, pkg/config/stepmeta_test.go
Reverts SAP/jenkins-library#4672
The PR might have broken something, I'm investigating it and using this revert PR to do tests.
=> Revert "Fix sidecar conditionals"

pkg/abap/aakaas/targetVector.go
=> Missing Space in Error Message targetVector.go

cmd/whitesourceExecuteScan.go, pkg/whitesource/configHelper.go
=> Mend fix for the config path calculation

cmd/helmExecute.go, cmd/helmExecute_test.go
Hi team,
This aims to fix #3881 .
Thanks,
Adrien
=> Run helm dependency before helm lint

pkg/abaputils/sap_com_0948.go
=> Fix initial request

go.mod, go.sum
dependency updates from renovate bot for the current pull requests:
https://github.com/SAP/jenkins-library/pull/4793
https://github.com/SAP/jenkins-library/pull/4791
https://github.com/SAP/jenkins-library/pull/4711
=> renovate dependency updates 

pkg/abaputils/manageGitRepositoryUtils.go
=> Only print logs if error occurred

pkg/telemetry/data.go
This PR adds new fields to the custom data struct, it is needed for piper-library steps
=> Extend custom telemetry data

cmd/kubernetesDeploy.go, cmd/kubernetesDeploy_test.go
Provide Helm values also if they contain dashes.
=> Support dashes in Helm values

cmd/detectExecuteScan.go, cmd/utils.go, cmd/whitesourceExecuteScan.go, pkg/log/log.go
Provided ability to show workspace content inside MEND and BD steps.
=> Display workspace content for debugging

cmd/containerSaveImage.go, cmd/whitesourceExecuteScan.go
=> whitesource image scan removing the timestamp and commit id

cmd/abapAddonAssemblyKitReserveNextPackages.go, cmd/abapAddonAssemblyKitReserveNextPackages_test.go
=> shorten commits to common length prior compare

cmd/cnbBuild.go, cmd/cnbBuild_test.go, pkg/cnbutils/auth.go, pkg/cnbutils/auth_test.go
Apparently this pr caused some regression.
This reverts commit df2e976eaab00e3dc71f2fec117d23a67a085742.
=> Revert "feat(cnbBuild): validate docker credentials (#4840)"

cmd/codeqlExecuteScan.go, cmd/codeqlExecuteScan_generated.go, cmd/codeqlExecuteScan_test.go, pkg/codeql/flags.go, pkg/codeql/flags_test.go, resources/metadata/codeqlExecuteScan.yaml
Added params databaseCreateFlags and databaseAnalyzeFlags as open configs for 'codeql database create' and 'codeql database analyze' commands.
=> feat(codeqlExecuteScan): added open configs for codeql database creation and analysis

cmd/sonarExecuteScan_generated.go, resources/metadata/sonarExecuteScan.yaml
Instead of https://github.com/SAP/jenkins-library/pull/4878, since `go generate` needs to be executed.
=> chore(sonar): Update Sonar default image to 5.0

cmd/detectExecuteScan.go
=> fix(detectExecuteScan) Hide repositoryPassword from logs

cmd/abapEnvironmentAssemblePackages.go, cmd/abapEnvironmentAssemblePackages_test.go, pkg/abaputils/descriptor.go, pkg/abaputils/descriptor_test.go
Provide addonDescriptor (reduced) to build system
=> ABAP: Provide addonDescriptor to build system

cmd/detectExecuteScan.go, cmd/detectExecuteScan_generated.go, resources/metadata/detectExecuteScan.yaml
=> Added detect9

pkg/abap/build/connector.go
=> increase http timeout

pkg/abap/aakaas/productVersionHeader.go
=> Bug: update semantic versions in case they contained wildCards missing

pkg/http/http.go
=> typo Update http.go

test/groovy/CommonStepsTest.groovy, vars/gcpPublishEvent.groovy
Without it, the step can't be called by Jenkins.
=> feat(events): Add gcpPublishEvent Groovy file

cmd/sonarExecuteScan_generated.go, resources/metadata/sonarExecuteScan.yaml
Update serverUrl param documentation
=> sonarExecuteScan: update documentation

pkg/documentation/generator/parameters.go
=> documentation: Add Vault resource to parameters

cmd/detectExecuteScan.go
=> detectExecuteScan - fix for diagnostics folder path

cmd/abapAddonAssemblyKitPublishTargetVector_generated.go, pkg/abap/aakaas/targetVector.go, resources/metadata/abapAddonAssemblyKitPublishTargetVector.yaml
longer polling; continue polling in case of undesired status
=> Publish TargetVector enhanced retry

pkg/whitesource/scanUA.go
Implemented a retry logic for downloading JRE from GitHub.com, enhancing the resiliency of our CI/CD pipeline.
Fixes - https://jira.tools.sap/browse/ALBATROSS-652
=> Resilience improvement for mend JRE download

vars/abapEnvironmentPipelineStageIntegrationTests.groovy
=> moved user confirmation to in front of the system deletion

cmd/ansSendEvent.go, cmd/cloudFoundryDeploy.go, cmd/cnbBuild.go, cmd/cnbBuild_test.go, cmd/contrastExecuteScan.go, cmd/detectExecuteScan.go, cmd/jsonApplyPatch.go, cmd/malwareExecuteScan.go, cmd/mavenExecute.go, cmd/mavenExecuteIntegration.go, cmd/mavenExecuteStaticCodeChecks.go, cmd/nexusUpload.go, cmd/readPipelineEnv.go, cmd/readPipelineEnv_test.go, cmd/terraformExecute.go, cmd/version.go, cmd/whitesourceExecuteScan.go, cmd/writePipelineEnv.go, go.mod, pkg/cnbutils/auth.go, pkg/cnbutils/auth_test.go
=> feat(cnbBuild): warn users when dockerConfigJSON is missing necessary credentials

pkg/abaputils/abaputils.go, pkg/abaputils/sap_com_0948.go, pkg/abaputils/sap_com_0948_test.go
=> OData V4 error message handling

pkg/orchestrator/jenkins.go, pkg/orchestrator/orchestrator.go
This PR aligns jenkins username parameter throughout Piper libraries. 
~~- [ ] Documentation~~
=> Align jenkins username parameter throughout library

cmd/abapAddonAssemblyKitCheck.go, cmd/abapAddonAssemblyKitCheck_generated.go, resources/metadata/abapAddonAssemblyKitCheck.yaml
=> add OriginHash to aakaas check

cmd/abapEnvironmentCloneGitRepo_generated.go, resources/metadata/abapEnvironmentCloneGitRepo.yaml
=> [ABAP] Add possible values and default for ByoG

cmd/mavenBuild.go, cmd/mavenBuild_test.go
Separate execution of makeBom goal and makeAggregateBom goal as it was causing anomaly in Azure dev ops.
=> Fix maven build failures due to makeBom goal

cmd/mavenBuild.go, cmd/mavenBuild_test.go
=> Run makeBOM after aggregateBOM

cmd/mavenBuild.go
=> Flatten the simple bom

resources/com.sap.piper/pipeline/abapEnvironmentPipelineDefaults.yml
=> change pipeline defaults to STANDARD

pkg/versioning/versioning.go
=> Add additional info to coordinates

cmd/whitesourceExecuteScan.go, cmd/whitesourceExecuteScan_generated.go, pkg/whitesource/scanOptions.go, pkg/whitesource/scanUA.go, resources/metadata/whitesourceExecuteScan.yaml
=> WhitesourceExecuteScan Added an option to use Global Config FIle for Multi Module Projects

pkg/vault/client.go, vars/sonarExecuteScan.groovy
removed readPipelineEnv step call since sonar step doesn't export anything to CPE.
=> fix(sonar): allign groovy part of Sonar step with common piperExecuteBin

pkg/vault/client.go
There was an issue when lifecycle manager never exits in case of  all attempts failed.
Added some debug logging
=> fix(vault): client locks in case of failure of all attempts

test/groovy/TestsPublishResultsTest.groovy, vars/testsPublishResults.groovy
due to missing quoting, command injection was possible via pipeline configuration.
=> fix: command injection vulnerability

cmd/mavenBuild.go, cmd/mavenBuild_test.go
This PR just updates the version of the cycloneDX plugin.
=> Update version of org.cyclonedx:cyclonedx-maven-plugin

src/com/sap/piper/BashUtils.groovy, src/com/sap/piper/tools/neo/NeoCommandHelper.groovy, test/groovy/ArtifactSetVersionTest.groovy, test/groovy/ContainerPushToRegistryTest.groovy, test/groovy/HealthExecuteCheckTest.groovy, test/groovy/NeoDeployTest.groovy, vars/artifactSetVersion.groovy, vars/containerPushToRegistry.groovy, vars/dockerExecute.groovy, vars/healthExecuteCheck.groovy, vars/mailSendNotification.groovy, vars/neoDeploy.groovy
=> Fix more potential command injection via quoting

vars/npmExecute.groovy, vars/piperExecuteBin.groovy, vars/sonarExecuteScan.groovy
- Add quoting to further steps
- Use import alias for quoting function
=> Final round of adding quoting to prevent command injection

.github/PULL_REQUEST_TEMPLATE.md
=> docs: update pr template to include inner source update reminder

src/com/sap/piper/ConfigurationHelper.groovy, src/com/sap/piper/StageNameProvider.groovy
=> handle new naming strategy for Central Build stage name

cmd/mavenBuild.go
=> Renamed maven simple bom to skip uploading to cumulus

go.mod, go.sum
=> Update circl from 1.3.3 to 1.5.0

cmd/fortifyExecuteScan_generated.go, resources/metadata/detectExecuteScan.yaml, resources/metadata/fortifyExecuteScan.yaml, resources/metadata/protecodeExecuteScan.yaml, resources/metadata/sonarExecuteScan.yaml, resources/metadata/whitesourceExecuteScan.yaml
Correct the anchor for the MkDocs page.
=> fix(docs): fix doc anchor

go.mod, go.sum
=> Updated all instances of circl to 1.3.7

pkg/config/config.go, src/com/sap/piper/ConfigurationHelper.groovy, src/com/sap/piper/StageNameProvider.groovy, vars/commonPipelineEnvironment.groovy, vars/piperPipelineStageBuild.groovy
=> fix passing default params to Central Build stage steps

cmd/abapEnvironmentCreateSystem_test.go, cmd/abapEnvironmentPushATCSystemConfig_test.go, cmd/abapEnvironmentRunATCCheck_test.go, cmd/abapEnvironmentRunAUnitTest_test.go, cmd/abapLandscapePortalUpdateAddOnProduct_test.go, cmd/cloudFoundryCreateServiceKey_test.go, cmd/cloudFoundryCreateService_test.go, cmd/gcpPublishEvent_test.go, cmd/integrationArtifactDeploy_test.go, cmd/integrationArtifactTransport.go, cmd/malwareExecuteScan_test.go, cmd/readPipelineEnv_test.go, pkg/abaputils/abaputils.go, pkg/abaputils/abaputils_test.go, pkg/abaputils/sap_com_0510.go, pkg/abaputils/sap_com_0948.go, pkg/cloudfoundry/Authentication.go, pkg/cloudfoundry/Authentication_test.go, pkg/cloudfoundry/CloudFoundry_test.go, pkg/cloudfoundry/ManifestUtils_test.go, pkg/cloudfoundry/Vars_test.go, pkg/cpi/mockingUtils.go
fixes https://github.com/SAP/jenkins-library/issues/4989
=> Fix deployment failure with CF if password contains special char

cmd/npmExecuteTests_generated.go, documentation/docs/steps/npmExecuteTests.md, resources/metadata/npmExecuteTests.yaml
=> docs: fix npmExuceteTests documentation formatting issues

.github/workflows/release-go.yml
=> Remove README and CONTRIBUTING files from release 2nd try

.github/workflows/release-go.yml
=> Set archive name from env

.github/workflows/release-go.yml
Reverted changes as its causing multiple failures
=> Revert changes done to release action

vars/writePipelineEnv.groovy
=> feat: allow passing values to writePipelineEnv

vars/writePipelineEnv.groovy
Reverts SAP/jenkins-library#5261
=> Revert "feat: allow passing values to writePipelineEnv"

documentation/docs/steps/npmExecuteTests.md
=> fix(docs): correct warning in step docs

cmd/abapEnvironmentRunATCCheck.go, cmd/abapEnvironmentRunATCCheck_test.go
=> Fix uncaught error in ATC Step

documentation/docs/steps/cloudFoundryDeploy.md
=> fix(docu): cloudFoundryDeploy remove dead link

documentation/docs/steps/isChangeInDevelopment.md
=> fix: invalid anchors

pkg/gcs/gcsClient.go, pkg/gcs/retry.go
=> fix(gcs): Catch errors from Google API properly

pkg/splunk/data.go, pkg/splunk/splunk.go
Exposes the commitSHA that the binary is based on to Splunk.
=> feat(telemetry): report binary version

cmd/getConfig.go, pkg/config/config.go
this will output stage-config.json like below:
```json
{
"someParam1": "value1",
"someParam2": "value2",
"hooks": {
"someServiceName": {
"serverURL": "https://some-service.example.com"
}
},
"someParam3": "value4"
}
```
=> feat: output hooks values in stage-config.json

.github/CODEOWNERS
=> chore(sonar): drop code ownership for sonar

.github/CODEOWNERS
This PR makes sonar team as code owners for sonar related files
=> Update CODEOWNERS for Sonar files

integration/integration_mta_test.go, integration/integration_tms_export_test.go, integration/integration_tms_upload_test.go
Attempt to unblock PR merges by skipping failing integration tests
=> fix(integration): Skip failing intergration tests for now

cmd/cnbBuild.go
=> fix(cnbBuild): ignore custom piper binary names

cmd/checkmarxOneExecuteScan.go
The way the filter patterns were processed could lead to files being wrongly included.
This PR is updating the code to make sure that a file is included if matched by at least one include pattern and no exclude pattern.
=> Fix filterPattern processing

cmd/mtaBuild_generated.go, cmd/npmExecuteScripts_generated.go, resources/metadata/mtaBuild.yaml, resources/metadata/npmExecuteScripts.yaml
Follow up of #5362
Some formatting changes for documentation of the step
=> fix(npmExecuteScripts): fix formatting of yaml for documentation

cmd/sonarExecuteScan.go
=> Revert PR 5366 as it seems it's causing issues

vars/setupCommonPipelineEnvironment.groovy
=> Check for prefix instead of substring in gitBranch

cmd/sonarExecuteScan.go, cmd/sonarExecuteScan_test.go, pkg/sonar/issueService.go, pkg/sonar/issueService_test.go, pkg/sonar/report.go, pkg/sonar/report_test.go, pkg/sonar/types.go
Implement hotsport security report for Piper sonarscan extension.
=> feat(sonar): add hotspot security report

cmd/sonarExecuteScan.go, pkg/sonar/report.go, pkg/sonar/report_test.go
Reverts SAP/jenkins-library#5427
=> Revert "feat(sonar): create combined report for Sonar scans"

cmd/abapEnvironmentAssemblePackages.go, cmd/abapEnvironmentAssemblePackages_generated.go, cmd/abapEnvironmentAssemblePackages_test.go, resources/metadata/abapEnvironmentAssemblePackages.yaml
allows alternative phase names
=> ABAP assemblePackages Alternative phase name

pkg/abap/build/connector.go
=> ABAP Better logging

cmd/contrastExecuteScan_generated.go, resources/metadata/contrastExecuteScan.yaml
This change aims to remove unused params (containers, etc.) & links; enable the compliance check by default.
=> Contrast: remove internal link; set compliance check by default
