vars/handlePipelineStepErrors.groovy
Fixes issue https://github.com/SAP/jenkins-library/issues/20
=> add further information to library step

README.md
Badge shows the result of the latest master build. Click forwards to the build history. More details [here](https://docs.travis-ci.com/user/status-images/).
=> Build Result Transparency

src/com/sap/piper/DefaultValueCache.groovy
=> fix default value cache get instance

documentation/docs/steps/neoDeploy.md, test/groovy/NeoDeploymentTest.groovy, vars/neoDeploy.groovy
Adding support to deploy/update WAR file to SAP CP
=> Neo deploy - Add support for WAR file deployment/rolling-update

.editorconfig
**changes**
- change the indent for YAML files
=> adapt editor config for yaml files

.travis.yml
return to workspace
needed for #70
=> correct docs command

test/groovy/MTABuildTest.groovy
- Removes unused code
- Removes duplicate code
- Ensures there is only one scope per unit test
- Formats Groovy code style following: https://github.com/SAP/jenkins-library/blob/master/CONTRIBUTING.md#code-style-1
- Formats blanks and new lines following previous format
=> Clean up MTABuildTest

documentation/docs/steps/artifactSetVersion.md, documentation/mkdocs.yml, resources/default_pipeline_environment.yml, src/com/sap/piper/GitUtils.groovy, src/com/sap/piper/versioning/ArtifactVersioning.groovy, src/com/sap/piper/versioning/DockerArtifactVersioning.groovy, src/com/sap/piper/versioning/MavenArtifactVersioning.groovy, test/groovy/ArtifactSetVersionTest.groovy, test/groovy/com/sap/piper/GitUtilsTest.groovy, test/groovy/com/sap/piper/versioning/ArtifactVersioningTest.groovy, test/groovy/com/sap/piper/versioning/DockerArtifactVersioningTest.groovy, test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy, test/groovy/util/JenkinsReadFileRule.groovy, test/groovy/util/JenkinsReadMavenPomRule.groovy, test/groovy/util/JenkinsShellCallRule.groovy, test/groovy/util/JenkinsWriteFileRule.groovy, test/resources/DockerArtifactVersioning/Dockerfile, test/resources/MavenArtifactVersioning/pom.xml, test/resources/MavenArtifactVersioning/snapshot/pom.xml, test/resources/artifactSetVersion/Dockerfile, vars/artifactSetVersion.groovy, vars/commonPipelineEnvironment.groovy
It contains:
* versioning step artifactSetVersion
* versioning implementation for Maven & Docker
* enhancements to commonPipelineEnvironment
* new default configuration
* new utils object for git-related tasks
* automated tests incl. new Rules and resources
So far missing:
=> Step for automatic versioning

src/com/sap/piper/ConfigurationMerger.groovy, src/com/sap/piper/MapUtils.groovy, test/groovy/com/sap/piper/ConfigurationMergerTest.groovy, test/groovy/com/sap/piper/MapUtilsTest.groovy
**changes**
- extend configuration merger to handle deep structure (needed for #58 #60)
=> extend config merger to handle deep config structures

test/groovy/ToolValidateTest.groovy, vars/toolValidate.groovy
Small clean up of ToolValidateTest before adding tests with new configuration, and log improvement on toolValidate step following the format of other steps.
before PR #75
=> Clean up tool validate

src/com/sap/piper/ConfigurationMerger.groovy, test/groovy/com/sap/piper/ConfigurationMergerTest.groovy, vars/artifactSetVersion.groovy, vars/checksPublishResults.groovy, vars/influxWriteData.groovy, vars/mavenExecute.groovy, vars/mtaBuild.groovy, vars/neoDeploy.groovy
The characteristics of a list are
o the order of the entries is significant
o duplicates are allowed
The characteristics of a set are
o the order is not significant
o duplicates are not allowed.
When describing keys for a step the characteristics of a
set applies here, whereas the characteristics of a list does
not apply.
=> Replace usage of lists for denoting keys by sets.

src/com/sap/piper/ConfigurationMerger.groovy, test/groovy/MTABuildTest.groovy, vars/mtaBuild.groovy
=> mtaJarLocation as step configuration

test/groovy/ArtifactSetVersionTest.groovy, test/groovy/util/JenkinsEnvironmentRule.groovy, test/groovy/util/JenkinsStepRule.groovy
**changes**
- add new rule for generic step loading
- add new rule for commonPipelineEnvironment loading
- use new rules in artifactSetVersion step
=> add rules for step and env loading

test/groovy/ArtifactSetVersionTest.groovy, test/groovy/ChecksPublishResultsTest.groovy, test/groovy/DockerExecuteTest.groovy, test/groovy/DurationMeasureTest.groovy, test/groovy/InfluxWriteDataTest.groovy, test/groovy/MTABuildTest.groovy, test/groovy/NeoDeployTest.groovy, test/groovy/PipelineExecuteTest.groovy, test/groovy/SetupCommonPipelineEnvironmentTest.groovy, test/groovy/ToolValidateTest.groovy
**changes**
- use JenkinsStepRule and JenkinsEnvironmentRule in all tests
=> use new rules

src/com/sap/piper/ConfigurationHelper.groovy, test/groovy/com/sap/piper/ConfigurationHelperTest.groovy, vars/artifactSetVersion.groovy
**changes**
- add ConfigLoader object
- improve readability by method chaining
=> change configuration loading 

test/groovy/ArtifactSetVersionTest.groovy, vars/artifactSetVersion.groovy
=> Fix the syntax error in artifactSetVersion step

documentation/docs/steps/mtaBuild.md, test/groovy/MTABuildTest.groovy, vars/mtaBuild.groovy
Issue https://github.com/SAP/jenkins-library/issues/74
=> add extension to mtaBuild

vars/dockerExecute.groovy
In our pipeline it failed multiple times because the class of p is not serializable.
=> Annotate docker plugin check as non cps

src/com/sap/piper/tools/JavaArchiveDescriptor.groovy, test/groovy/com/sap/piper/tools/JavaArchiveDescriptorTest.groovy
issue https://github.com/SAP/jenkins-library/issues/141
=> compatibility code for new feature

vars/fetchUrl.groovy, vars/mavenExecute.groovy
Removing step fetchUrl to solve issue #55 
Version is not increased to new major version.
Change is not backward compatible due to removed step.
=> remove fetchUrl Step

src/com/sap/piper/VersionUtils.groovy, src/com/sap/piper/tools/ToolDescriptor.groovy, test/groovy/com/sap/piper/tools/ToolDescriptorTest.groovy, vars/neoDeploy.groovy, vars/toolValidate.groovy
Issue https://github.com/SAP/jenkins-library/issues/26
=> Add multiple versions verification

src/com/sap/piper/ConfigurationHelper.groovy, test/groovy/com/sap/piper/ConfigurationHelperTest.groovy
=> general default section mixed in automatically.

pom.xml, resources/default_pipeline_environment.yml, src/com/sap/piper/Utils.groovy, test/groovy/InfluxWriteDataTest.groovy, test/groovy/MavenExecuteTest.groovy, test/groovy/PipelineStashFilesAfterBuildTest.groovy, test/groovy/PipelineStashFilesBeforeBuildTest.groovy, test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy, test/groovy/util/BasePiperTest.groovy, test/groovy/util/BasePiperTestContext.groovy, test/groovy/util/JenkinsEnvironmentRule.groovy, test/groovy/util/JenkinsReadJsonRule.groovy, test/groovy/util/LibraryLoadingTestExecutionListener.groovy, test/groovy/util/Rules.groovy, vars/commonPipelineEnvironment.groovy, vars/pipelineStashFiles.groovy, vars/pipelineStashFilesAfterBuild.groovy, vars/pipelineStashFilesBeforeBuild.groovy
added steps which help to stash files across the pipeline in an easy way.
This also includes an update to the test framework in order to speed up tests
=> add steps for file stashing

documentation/docs/steps/pipelineStashFiles.md, documentation/mkdocs.yml, resources/default_pipeline_environment.yml, test/groovy/PipelineStashFilesAfterBuildTest.groovy, test/groovy/PipelineStashFilesBeforeBuildTest.groovy, vars/pipelineStashFilesAfterBuild.groovy, vars/pipelineStashFilesBeforeBuild.groovy
This contains some cleanups to the code
plus documentation for the step
=> pipelineStashFiles - cleanup & documentation

test/groovy/ArtifactSetVersionTest.groovy, test/groovy/ChecksPublishResultsTest.groovy, test/groovy/DockerExecuteTest.groovy, test/groovy/DurationMeasureTest.groovy, test/groovy/InfluxWriteDataTest.groovy, test/groovy/MTABuildTest.groovy, test/groovy/MavenExecuteTest.groovy, test/groovy/NeoDeployTest.groovy, test/groovy/PipelineExecuteTest.groovy, test/groovy/SetupCommonPipelineEnvironmentTest.groovy, test/groovy/TestsPublishResultsTest.groovy, test/groovy/ToolValidateTest.groovy, test/groovy/com/sap/piper/EnvironmentUtilsTest.groovy, test/groovy/com/sap/piper/FileUtilsTest.groovy, test/groovy/com/sap/piper/GitUtilsTest.groovy, test/groovy/com/sap/piper/MtaUtilsTest.groovy, test/groovy/com/sap/piper/tools/JavaArchiveDescriptorTest.groovy, test/groovy/com/sap/piper/tools/ToolDescriptorTest.groovy, test/groovy/com/sap/piper/versioning/DockerArtifactVersioningTest.groovy, test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy, test/groovy/util/BasePiperTest.groovy, test/groovy/util/BasePiperTestContext.groovy, test/groovy/util/JenkinsDockerExecuteRule.groovy
* use new base class for testing
* initialize jenkins unit test framework only once for all test classes
* minor test cleanups
=> speed up tests

src/com/sap/piper/GitUtils.groovy, test/groovy/com/sap/piper/GitUtilsTest.groovy
Dedicated method checking if we are currently inside a git working tree.
=> git utils: is inside working tree

documentation/docs/steps/mtaBuild.md, src/com/sap/piper/tools/JavaArchiveDescriptor.groovy, test/groovy/com/sap/piper/tools/JavaArchiveDescriptorTest.groovy
- Update MTA Builder download link
- Include special characters on MTA Builder name
- Update tests with MTA Builder name containing special characters
=> Update mta build

src/com/sap/piper/ConfigurationMerger.groovy, src/com/sap/piper/MapUtils.groovy, test/groovy/com/sap/piper/MapUtilsTest.groovy
**changes**
- extract `merge` function from `ConfigurationHelper` to `MapUtils` to reuse for merging of corporate defaults (pr #)
=> extract map merging to MapUtils

resources/default_pipeline_environment.yml, src/com/sap/piper/mta/MtaMultiplexer.groovy, test/groovy/SnykExecuteTest.groovy, test/groovy/com/sap/piper/mta/MtaMultiplexerTest.groovy, vars/snykExecute.groovy
**changes**
- add new step `snykExecute` to execute scan with [snyk.io](https://snyk.io)
- add multiplexer for MTA handling
=> add step for snyk open source vulnerability scan

documentation/docs/steps/transportRequestCreate.md, documentation/docs/steps/transportRequestRelease.md, documentation/docs/steps/transportRequestUploadFile.md, test/groovy/TransportRequestCreateTest.groovy, test/groovy/TransportRequestReleaseTest.groovy, test/groovy/TransportRequestUploadFileTest.groovy, vars/transportRequestCreate.groovy, vars/transportRequestRelease.groovy, vars/transportRequestUploadFile.groovy
the official term in SAP-SolutionManager is 'change document'.
The term 'change' as reflected in 'changeId' is ambigous and could also be understand in the
sense of a change in a revision control system.
Choosing appropriate terms for parameters here deceases the amount of documentation
required for explaining what is really denoted by the parameter.
=> Change parameter name 'changeId' to 'changeDocumentId'

test/groovy/NewmanExecuteTest.groovy
o we are in the default package, hence package 'steps' is inappropriate
o there is also no grovvy shebang in other test files, why should it be here?
=> Remove wrong package declaration and stange grovvy shebang

resources/default_pipeline_environment.yml, test/groovy/NewmanExecuteTest.groovy
The newman JUnit test testExecuteNewmanWithFolder fails on windows. This PR fixes it.
=> adapt the NewmanExecuteTest to windows file system

src/com/sap/piper/ConfigurationHelper.groovy, test/groovy/com/sap/piper/ConfigurationHelperTest.groovy
=> read nested properties

documentation/docs/configuration.md, src/com/sap/piper/ConfigurationHelper.groovy, test/groovy/com/sap/piper/ConfigurationHelperTest.groovy, vars/artifactSetVersion.groovy, vars/checkChangeInDevelopment.groovy, vars/cloudFoundryDeploy.groovy, vars/newmanExecute.groovy, vars/pipelineStashFilesAfterBuild.groovy, vars/pipelineStashFilesBeforeBuild.groovy, vars/setupCommonPipelineEnvironment.groovy, vars/snykExecute.groovy, vars/testsPublishResults.groovy, vars/transportRequestCreate.groovy, vars/transportRequestRelease.groovy, vars/transportRequestUploadFile.groovy
Telemetry reporting is added to all steps using ConfigurationHelper.
Other steps need to be switched to ConfigurationHelper first.
=> add telemetry reporting to steps

vars/neoDeploy.groovy
preparation for telemetry reporting in this step: #243
=> neoDeploy: switch to chained ConfigurationHelper

.travis.yml, pom.xml
**changes**
- use `mvn clean test` instead of `mvn test`
- deactivate Findbugs
- limit push builds to master branch
=> change TravisCI build

src/com/sap/piper/ConfigurationHelper.groovy
... with that an IDE knowns more about the type.
=> Be more typed inside ConfigurationHelper

src/com/sap/piper/cm/ChangeManagement.groovy
The cm command line is emitted to the log. Helpful for trouble shooting.
=> Emit cm command line to log.

src/com/sap/piper/Utils.groovy, test/groovy/CloudFoundryDeployTest.groovy, test/groovy/com/sap/piper/UtilsTest.groovy
**changes:**
- notify about disabled reporting
=> notify about deactivated SWA reporting

vars/neoDeploy.groovy
**changes:**
- add web analytics
=> neoDeploy: add web analytics

documentation/docs/steps/mtaBuild.md, test/groovy/MtaBuildTest.groovy, vars/mtaBuild.groovy
**changes:**
- Execute MTA build in a docker container, like other build types too.
=> Execute MTA builder in Docker

.travis.yml, gh-pages-deploy.sh
**changes:**
-
- [x ] changed entrypoint
=> fix docu deployment

.travis.yml
=> change script persmission

gh-pages-deploy.sh
=> added github.com to knownhosts

gh-pages-deploy.sh
=> create .ssh dir

vars/dockerExecuteOnKubernetes.groovy
**changes:**
- fix issue with stash overriding in error case
=> dockerExecuteOnKubernetes: fix stash overriding

documentation/docs/steps/seleniumExecuteTests.md
Update to documentation of step `seleniumExecuteTests`
=> seleniumExecuteTests - Documentation Update

test/groovy/DockerExecuteOnKubernetesTest.groovy, vars/dockerExecuteOnKubernetes.groovy
**changes:**
- use stashing for *sidecar* case
- condense pod execution
=> executeDockerOnKubernetes: support workspace/container stashing for sidecar case

test/groovy/CommonStepsTest.groovy, vars/durationMeasure.groovy, vars/handlePipelineStepErrors.groovy, vars/pipelineExecute.groovy, vars/pipelineStashFiles.groovy, vars/prepareDefaultValues.groovy, vars/toolValidate.groovy
Asserts that each step (modulo whitelist) comes with a STEP_NAME
field.
=> STEP_NAME test

vars/healthExecuteCheck.groovy
**changes:**
add collection of telemetry for step healthExecuteCheck
=> add telemetry to healthExecuteCheck

vars/commonPipelineEnvironment.groovy
add additional git information to `commonPipelineEnvironment`:
* git https url
* git branch
* github organization
* github repository
=> enhance commonPipelineEnvironment with additional information

documentation/docs/steps/mailSendNotification.md, documentation/mkdocs.yml, resources/com.sap.piper/templates/mailFailure.html, resources/com.sap.piper/templates/mailRecover.html, resources/default_pipeline_environment.yml, test/groovy/MailSendNotificationTest.groovy, test/groovy/util/JenkinsSetupRule.groovy, test/groovy/util/JenkinsShellCallRule.groovy, vars/commonPipelineEnvironment.groovy, vars/mailSendNotification.groovy
This step allows to send email notifications in case of pipeline failures.
=> add step mailSendNotification

documentation/docs/steps/pipelineRestartSteps.md, documentation/mkdocs.yml, resources/default_pipeline_environment.yml, src/com/sap/piper/JenkinsUtils.groovy, test/groovy/PipelineRestartStepsTest.groovy, test/groovy/com/sap/piper/JenkinsUtilsTest.groovy, test/groovy/util/BasePiperTest.groovy, test/groovy/util/BasePiperTestContext.groovy, vars/pipelineRestartSteps.groovy
This step allows to restart a set of steps in order to retry in case of e.g. infrastructure failures which first need to be fixed.
=> add step pipelineRestartSteps

documentation/docs/steps/dockerExecute.md, resources/default_pipeline_environment.yml, test/groovy/DockerExecuteTest.groovy, vars/dockerExecute.groovy
**changes:**
- use docker networks
=> dockerExecute: use docker network to connect sidecar containers

pom.xml, test/groovy/CheckChangeInDevelopmentTest.groovy, test/groovy/DockerExecuteTest.groovy, test/groovy/TestsPublishResultsTest.groovy
**changes:**
- add `src` and `vars` to groovy resources for better code coverage reporting
=> add sources for code coverage

resources/com.sap.piper/templates/error.log, test/groovy/HandlePipelineStepErrorTest.groovy, vars/handlePipelineStepErrors.groovy
**changes:**
- extract error message to template
- add tests for `handlePipelineStepErrors`
=> handlePipelineStepErrors: extract error message to template

.codeclimate.yml
**changes:**
- add config file for [Code Climate](https://codeclimate.com/github/SAP/jenkins-library)
- activate plugin for [CodeNarc](https://docs.codeclimate.com/docs/codenarc)
- activate plugin for [EditorConfig](https://docs.codeclimate.com/docs/editorconfig)
- activate plugin for [FIXME](https://docs.codeclimate.com/docs/fixme)
- activate plugin for [MarkdownLint](https://docs.codeclimate.com/docs/markdownlint)
- activate plugin for [ShellCheck](https://docs.codeclimate.com/docs/shellcheck)
related to #356
=> add config for Code Climate

.editorconfig, documentation/docs/steps/githubPublishRelease.md, template/StepTestTemplateTest.groovy
=> fix Code Climate findings

template/StepTestTemplateTest.groovy, test/groovy/ChecksPublishResultsTest.groovy, test/groovy/DurationMeasureTest.groovy, test/groovy/InfluxWriteDataTest.groovy, test/groovy/MtaBuildTest.groovy, test/groovy/NeoDeployTest.groovy, test/groovy/PipelineExecuteTest.groovy, test/groovy/PipelineStashFilesAfterBuildTest.groovy, test/groovy/PipelineStashFilesBeforeBuildTest.groovy, test/groovy/PrepareDefaultValuesTest.groovy, test/groovy/SetupCommonPipelineEnvironmentTest.groovy, test/groovy/ToolValidateTest.groovy, test/groovy/TransportRequestCreateTest.groovy, test/groovy/TransportRequestReleaseTest.groovy, test/groovy/TransportRequestUploadFileTest.groovy
=> correct step invokation in tests

vars/neoDeploy.groovy
**changes:**
- adds `script` to `dockerExecute` call
fixes #376
=> neoDeploy: add missing script

documentation/docs/steps/karmaExecuteTests.md, resources/default_pipeline_environment.yml
**changes:**
- add `localhost` and `karma`/`selenium` to proxy excludes
- add default stashes
=> karmaExecuteTests: extend default proxy excludes and stashes

vars/cloudFoundryDeploy.groovy
**changes:**
- adds `script` to `dockerExecute` call
see #305
=> cloudFoundryDeploy - adapt to changes in dockerExecute

vars/mailSendNotification.groovy
Do not create failure in case `gitSshKeyCredentialsId` is not configured.
Only provide warning message.
=> mailSendNotification - add resilience

vars/pipelineStashFilesAfterBuild.groovy, vars/pipelineStashFilesBeforeBuild.groovy
**changes:**
- resolve `${STEP_NAME}` in log message
=> pipelineStashFiles: resolve STEP_NAME in log message

vars/cloudFoundryDeploy.groovy
**changes:**
fix stashing with empty list
=> cloudFoundryDeploy - fix stashing

vars/batsExecuteTests.groovy, vars/snykExecute.groovy
**changes:**
- add passing of madatory `script` parameter
closes #381
=> Docker execution - make sure that script is passed

Jenkinsfile
=> Update mail recipients

documentation/docs/steps/cloudFoundryDeploy.md
=> Docu: Typo

.github/PULL_REQUEST_TEMPLATE.md
=> Fixing PULL_REQUEST_TEMPLATE.md

documentation/docs/steps/influxWriteData.md
=> docs: clean influx page

documentation/docs/steps/newmanExecute.md
fixed step name in documentation
=> fix documentation

vars/checkChangeInDevelopment.groovy, vars/influxWriteData.groovy
=> Remove unneeded imports for ConfigurationMerger, ConfigurationLoader

src/com/sap/piper/ConfigurationHelper.groovy
**changes:**
- add the ability to report the mixed config from within the `ConfigurationHelper` on `verbose: true`
=> ConfigurationHelper: report config on verbose

test/groovy/CloudFoundryDeployTest.groovy, test/groovy/util/JenkinsReadFileRule.groovy
=> Proposal: how we can do it without changing the read file rule.

README.md
=> Exchanged "deployment" with "delivery"

documentation/bin/createDocu.groovy
* Do not remove significant white spaces from documentation.
* The first blank after the asterisk is not taken into account since this looks better
=> fix docu generator formatting

vars/dockerExecute.groovy, vars/dockerExecuteOnKubernetes.groovy
**changes**:
- added `jenkinsKubernetes` config key to `STEP_CONFIG_KEYS` and `PARAMETER_KEYS`
- rest stays the same
=> dockerExecuteOnKubernetes: correct parameter keys

documentation/docs/steps/dockerExecute.md, vars/dockerExecute.groovy
**changes:**
- generate documentation for `dockerExecute` step
useful for verification of #479
=> dockerExecute: generate docs

documentation/docs/scenarios/ui5-sap-cp/Readme.md
Adapt scenario title, add figure title, and minor linguistic and layout changes
=> Adapt scenario so that it matches the template

documentation/docs/scenarios/changeManagement.md, documentation/mkdocs.yml
Change title to be consistent with other scenarios and add links to detailed description of the parameters used in this scenario.
=> Doc: Change title and add parameters

documentation/mkdocs.yml
=> publish docu for step uiVeri5ExecuteTests

documentation/bin/createDocu.groovy, documentation/docs/steps/dockerExecuteOnKubernetes.md, vars/dockerExecuteOnKubernetes.groovy
**changes:**
- generate documentation for `dockerExecuteOnKubernetes ` step
- order parameter keys
- fix whitespace issue in `generateDocumentation` script
=> dockerExecuteOnKubernetes: generate documentation

documentation/docs/scenarios/CAP_Scenario.md
=> 📄 Describe Cloud Application Programming Model Scenario

documentation/mkdocs.yml
Add "Build and Deploy Applications with Jenkins and the SAP Cloud Application Programming Model" to "Scenarios"
=> Add CAP Scenario

documentation/docs/scenarios/changeManagement.md
=> Changed size of figure title

documentation/docs/steps/mtaBuild.md, resources/default_pipeline_environment.yml, test/groovy/MtaBuildTest.groovy
=> Configure default mta build image to ppiper/mta-archive-builder

documentation/docs/steps/uiVeri5ExecuteTests.md
=> uiVeri5ExecuteTests, documentation update

.github/CONTRIBUTING.md
=> Document how to trigger integration tests.

documentation/docs/steps/snykExecute.md, documentation/mkdocs.yml, vars/snykExecute.groovy
=> snykExecute: add missing documentation

consumer-test/integrationTestController.sh
=> Show correct logs in integration tests

test/groovy/DockerExecuteTest.groovy, vars/dockerExecute.groovy
=> Wait for sidecar container to be ready

documentation/docs/steps/neoDeploy.md, test/groovy/NeoDeployTest.groovy, vars/neoDeploy.groovy
=> Make source for neo configurable in the config file

vars/seleniumExecuteTests.groovy
**changes:**
- fix type of `GENERAL_CONFIG_KEYS `
=> seleniumExecuteTests: fix type

documentation/docs/steps/seleniumExecuteTests.md, vars/seleniumExecuteTests.groovy, vars/uiVeri5ExecuteTests.groovy
**changes:**
- generate docs for `seleniumExecuteTests`
- use `@see` annotation for `uiVeri5ExecuteTests`
=> seleniumExecuteTests & uiVeri5ExecuteTests: improve documentation

documentation/docs/scenarios/ui5-sap-cp/Readme.md
=> update documentation for neoDeploy step parameters

vars/commonPipelineEnvironment.groovy, vars/setupCommonPipelineEnvironment.groovy
**changes:**
- add build link to `step_data`
- add build link to `pipeline_data`
=> influx: report build link to influx measurements

consumer-test/integrationTestController.sh, consumer-test/runTest.sh
No change in behaviour, just changes suggested by IntelliJ
=> Fix typos and small IDE hints

documentation/docs/steps/slackSendNotification.md, vars/slackSendNotification.groovy
**changes:** 
- generate documentation for `slackSendNotification` step
=> slackSendNotification: generate documentation

documentation/docs/steps/newmanExecute.md, vars/newmanExecute.groovy
**changes:** 
- generate documentation for `newmanExecute` step
=> newmanExecute: generate documentation

test/groovy/SetupCommonPipelineEnvironmentTest.groovy, vars/commonPipelineEnvironment.groovy, vars/setupCommonPipelineEnvironment.groovy
Removes code related to deprecated config.properties file.
=> Remove config.properties

documentation/docs/steps/transportRequestCreate.md
=> Prerequiste transportRequestCreate: SOLMAN ST720 SP08 or higher

src/com/sap/piper/analytics/Telemetry.groovy, test/groovy/com/sap/piper/analytics/TelemetryTest.groovy
**changes:**
- use `httpRequest` step to avoid issue with missing workspace
=> web analytics: use httpRequest step

resources/default_pipeline_environment.yml, src/com/sap/piper/Utils.groovy, test/groovy/PipelineStashFilesAfterBuildTest.groovy, test/groovy/PipelineStashFilesBeforeBuildTest.groovy, vars/pipelineStashFilesAfterBuild.groovy, vars/pipelineStashFilesBeforeBuild.groovy
=> update stashing behavior

documentation/docs/steps/handlePipelineStepErrors.md, vars/handlePipelineStepErrors.groovy
=> handlePipelineStepErrors: generate docu

documentation/docs/steps/healthExecuteCheck.md, vars/healthExecuteCheck.groovy
=> healthExecuteCheck: generate docu

documentation/docs/steps/mavenExecute.md, vars/mavenExecute.groovy
=> mavenExecute: generate docu

documentation/docs/steps/durationMeasure.md, vars/durationMeasure.groovy
=> durationMeasure: generate docu

documentation/docs/steps/pipelineExecute.md, vars/pipelineExecute.groovy
=> pipelineExecute: generate docu

documentation/docs/steps/mtaBuild.md, vars/mtaBuild.groovy
=> mtaBuild: generate docu

documentation/docs/steps/handlePipelineStepErrors.md, vars/handlePipelineStepErrors.groovy
=> fix unstable docs build

documentation/docs/steps/batsExecuteTests.md, vars/batsExecuteTests.groovy
=> batsExecuteTests: generate docu

documentation/docs/steps/prepareDefaultValues.md, vars/prepareDefaultValues.groovy
=> prepareDefaultValues: generate docu

documentation/docs/steps/containerExecuteStructureTests.md, vars/containerExecuteStructureTests.groovy
=> containerExecuteStructureTests: generate docu

documentation/docs/steps/pipelineRestartSteps.md, vars/pipelineRestartSteps.groovy
=> pipelineRestartSteps: generate docu

documentation/docs/steps/setupCommonPipelineEnvironment.md, vars/setupCommonPipelineEnvironment.groovy
=> setupCommonPipelineEnvironment: generate docu

documentation/docs/steps/testsPublishResults.md, vars/testsPublishResults.groovy
=> testsPublishResults: generate docu

resources/default_pipeline_environment.yml, src/com/sap/piper/Utils.groovy, test/groovy/PipelineExecuteTest.groovy, test/groovy/com/sap/piper/UtilsTest.groovy, vars/pipelineExecute.groovy
=> remove utils.getMandatoryParameter()

documentation/docs/steps/checksPublishResults.md, vars/checksPublishResults.groovy
=> checksPublishResults: generate docu

vars/checkChangeInDevelopment.groovy
=> checkChangeInDevelopment: update documentation

documentation/docs/steps/transportRequestCreate.md, vars/transportRequestCreate.groovy
=> transportRequestCreate: generate docu

.travis.yml
**changes:**
- correct folder pushed to `gh-pages` branch to `docs-gen`
=> Travis: fix docs generation

documentation/docs/steps/transportRequestUploadFile.md, vars/transportRequestUploadFile.groovy
=> transportRequestUploadFile: generate docu

documentation/docs/steps/transportRequestRelease.md, vars/transportRequestRelease.groovy
=> transportRequestRelease: generate docu

documentation/docs/steps/githubPublishRelease.md, vars/githubPublishRelease.groovy
=> githubPublishRelease: generate docu

documentation/docs/steps/artifactSetVersion.md, vars/artifactSetVersion.groovy
=> artifactSetVersion: generate docu

documentation/docs/steps/cloudFoundryDeploy.md, test/groovy/CloudFoundryDeployTest.groovy, vars/cloudFoundryDeploy.groovy
=> cloudFoundryDeploy: generate docu

documentation/docs/steps/multicloudDeploy.md, src/com/sap/piper/CloudPlatform.groovy, src/com/sap/piper/DeploymentType.groovy, src/com/sap/piper/Utils.groovy, test/groovy/MulticloudDeployTest.groovy, test/groovy/util/JenkinsMockStepRule.groovy, test/groovy/util/JenkinsStepRule.groovy, test/resources/deploy/pom.xml, vars/multicloudDeploy.groovy
So far I only got the requirement of keeping compatibility with the following [step](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/master/vars/deployToCloudPlatform.groovy).
Any other requirements are welcomed.
Therefore, tests may not be finished.
Solves issue [#335](https://github.com/SAP/jenkins-library/issues/335)
=> add multicloud deployment step

documentation/docs/steps/influxWriteData.md, vars/influxWriteData.groovy
=> influxWriteData: generate docu

documentation/docs/steps/neoDeploy.md, vars/neoDeploy.groovy
=> neoDeploy: generate docu

documentation/docs/steps/pipelineStashFiles.md, documentation/docs/steps/pipelineStashFilesAfterBuild.md, documentation/docs/steps/pipelineStashFilesBeforeBuild.md, vars/pipelineStashFiles.groovy, vars/pipelineStashFilesAfterBuild.groovy, vars/pipelineStashFilesBeforeBuild.groovy
=> pipelineStashFiles: generate docu

documentation/docs/scenarios/ui5-sap-cp/Readme.md
=> Correct typos "SAP UI5"

documentation/mkdocs.yml
=> add new step docu to index

documentation/docs/scenarios/changeManagement.md
=> Add note admonition

vars/artifactSetVersion.groovy, vars/gaugeExecuteTests.groovy, vars/seleniumExecuteTests.groovy, vars/whitesourceExecuteScan.groovy
=> Doc - Add missing possible values

src/com/sap/piper/WhitesourceConfigurationHelper.groovy, test/groovy/WhitesourceExecuteScanTest.groovy, test/groovy/com/sap/piper/WhitesourceConfigurationHelperTest.groovy
=> whitesourceExecuteScan: Fix suffix collision for MTA scenario

documentation/docs/steps/slackSendNotification.md
=> improve Slack setup documentation

documentation/bin/createDocu.groovy, documentation/docs/steps/detectExecuteScan.md, resources/default_pipeline_environment.yml, test/groovy/DetectExecuteScanTest.groovy, vars/detectExecuteScan.groovy
add Synopsis Detect capabilities (formerly called Blackduck Hub Detect).
Details about the tool can be found here: https://synopsys.atlassian.net/wiki/spaces/INTDOCS/pages/62423113/Synopsys+Detect
=> add step for Synopsis Detect Scans

consumer-test/consumerTestController.groovy
Fix two bugs: 
1. Tests were not run on master branch.
1. Need commit hash before notifying github
=> fix groovy consumer test bugs

src/com/sap/piper/ConfigurationHelper.groovy, test/groovy/NeoDeployTest.groovy, test/groovy/com/sap/piper/ConfigurationHelperTest.groovy
https://github.com/SAP/jenkins-library/issues/665
=> fix wrong message

documentation/bin/createDocu.groovy, src/com/sap/piper/MapUtils.groovy, test/groovy/com/sap/piper/MapUtilsTest.groovy, test/groovy/templates/PiperInitRunStageConfigurationTest.groovy, vars/piperInitRunStageConfiguration.groovy
extract method for finding a map entry by `/`-separated path to `MapUtils` class
=> move method to MapUtils

vars/commonPipelineEnvironment.groovy
=> Compatibility to Piper PR support

test/groovy/NeoDeployTest.groovy
=> Tests: inline JUnit rules

documentation/bin/createDocu.groovy, vars/pipelineRestartSteps.groovy
A rewording of the paragraph https://github.com/SAP/jenkins-library/blob/77e344d181bbcb58b84f14d7977d692618d378a8/documentation/bin/createDocu.groovy#L622-L626 would be helpful. This is a text being showed on a lot of pages.
=> Fix formatting

resources/default_pipeline_environment.yml, src/com/sap/piper/GenerateStageDocumentation.groovy, test/groovy/templates/PiperPipelineStageConfirmTest.groovy, test/groovy/templates/PiperPipelineTest.groovy, vars/piperPipeline.groovy, vars/piperPipelineStageConfirm.groovy
=> Templates - Add advanced confirm stage

src/com/sap/piper/cm/BackendType.groovy, src/com/sap/piper/cm/ChangeManagementException.groovy, src/com/sap/piper/cm/StepHelpers.groovy, src/com/sap/piper/tools/neo/DeployMode.groovy, src/com/sap/piper/tools/neo/NeoCommandHelper.groovy, src/com/sap/piper/tools/neo/WarAction.groovy, test/groovy/CommonStepsTest.groovy, test/groovy/DockerExecuteOnKubernetesTest.groovy, test/groovy/PrepareDefaultValuesTest.groovy, test/groovy/com/sap/piper/MapUtilsTest.groovy, test/groovy/com/sap/piper/MtaUtilsTest.groovy, test/groovy/com/sap/piper/k8s/SystemEnvTest.groovy, test/groovy/util/JenkinsLoggingRule.groovy, test/groovy/util/JenkinsShellCallRule.groovy, test/groovy/util/PipelineWhenException.groovy, test/groovy/util/StepHelper.groovy, vars/mailSendNotification.groovy, vars/sonarExecuteScan.groovy
=> remove semikolons

documentation/docs/steps/slackSendNotification.md, vars/slackSendNotification.groovy
Christopher, can I change this, I did double check with the docu developer and she also agrees that the punctuation here is wrong.
=> minor change in slackSendNotification documentation

resources/default_pipeline_environment.yml, src/com/sap/piper/tools/neo/NeoCommandHelper.groovy, test/groovy/NeoDeployTest.groovy, test/groovy/com/sap/piper/tools/neo/NeoCommandHelperTest.groovy, vars/neoDeploy.groovy
=> adding extensions to neoDeploy

vars/neoDeploy.groovy
=> Avoid having the same string literal for the neo log folder three times

test/groovy/DockerExecuteOnKubernetesTest.groovy, vars/dockerExecuteOnKubernetes.groovy
Make sure that complete workspace is available in Kubernetes Pod.
So far e.g. git repository information were missing.
=> dockerExecuteOnKubernetes - stash also .git folder

vars/whitesourceExecuteScan.groovy
=> Add missing compatibility for productVersion

vars/mtaBuild.groovy
=> added comment to explain escaped variable

documentation/docs/steps/dubExecute.md, documentation/mkdocs.yml, resources/default_pipeline_environment.yml, test/groovy/DubExecuteTest.groovy, vars/dubExecute.groovy
Step to execute D Programming Language package manager ```Dub``` is added. 
- [ X] Tests
- [ X] Documentation
=> Add dubExecute step

test/groovy/KarmaExecuteTestsTest.groovy, vars/karmaExecuteTests.groovy
=> karmaExecuteTests: fix multi module execution

src/com/sap/piper/k8s/SystemEnv.groovy, vars/dockerExecuteOnKubernetes.groovy
For some use cases like [Karma execution](https://github.com/piper-validation/openui5-sample-app/pull/1/files#diff-1d8483a942d5a168aba51da54a9a9473R59) it is good to know that we are running in a kubernetes environment.
=> dockerExecuteOnKubernetes: hand ON_K8S env var down into container

consumer-test/consumerTestController.groovy
Change code to do a proper variable assignment
=> Fix consumer test invocation

resources/default_pipeline_environment.yml, test/groovy/WhitesourceExecuteScanTest.groovy
=> Change WhiteSource UA download URL to new official channel

test/groovy/GithubPublishReleaseTest.groovy, vars/githubPublishRelease.groovy
correct error handling to properly take care of non-existing initial release.
=> githubPublishRelease - correct situation where no release exist yet

consumer-test/TestRunnerThread.groovy, consumer-test/consumerTestController.groovy, consumer-test/jenkins.yml, consumer-test/testCases/s4sdk/consumer-test-neo.yml, consumer-test/testCases/s4sdk/consumer-test.yml, consumer-test/testCases/scs/ui5-neo.yml
Add test for UI5 sample app located here: https://github.com/piper-validation/openui5-sample-app/tree/piper-test-ui5-neo
Repo URL, branch and credential environment variable name are retrieved from test case yaml file.
=> add ui5 consumer test

consumer-test/jenkins.yml, consumer-test/testCases/scs/cap.yml
Adds [CAP Scenario](https://sap.github.io/jenkins-library/scenarios/CAP_Scenario/) to the Consumer Tests. Sample App Repo being built: https://github.com/piper-validation/mta-sample-app/tree/piper-test-cap
=> Add cds test case

documentation/bin/createDocu.groovy
=> Fix docu script to avoid withMandatoryPropertyUponCondition being picked

test/groovy/PiperPublishWarningsTest.groovy
=> Remove inappropriate package statement and inappr. shebang

src/com/sap/piper/ConfigurationHelper.groovy
Related to https://github.com/SAP/jenkins-library/issues/786#issuecomment-520461605
=> Fix cps mismatch issue

test/groovy/DockerExecuteOnKubernetesTest.groovy, vars/dockerExecuteOnKubernetes.groovy
For certain cases it is valuable to only bring back some of the files from an execution inside a container back to the workspace.
This is now added.
Closes #753
=> dockerExecuteOnKubernetes - add stashBack configuration

test/groovy/GithubPublishReleaseTest.groovy, vars/githubPublishRelease.groovy
add templating capabilities for the header in the release information
=> githubPublishRelease - add templating capabilities

vars/neoDeploy.groovy
=> Remove useless utils from signature inside neoDeploy

documentation/docs/scenarios/CAP_Scenario.md
SAP Cloud SDK implements a more comprehensive CAP pipeline and should be linked from here.
=> Link the SAP Cloud SDK

.travis.yml
=> Use openjdk8 in travis build

src/com/sap/piper/WhitesourceConfigurationHelper.groovy, vars/whitesourceExecuteScan.groovy
=> whitesourceExecuteScan: Add archiving of new UA log files

vars/whitesourceExecuteScan.groovy
=> whitesourceExecuteScan: Transfer logs into workspace to allow archiving

pkg/config/defaults_test.go
=> Remove redundancies in test (expected value repeated)

pkg/config/config_test.go
=> deep compare for maps

src/com/sap/piper/Utils.groovy, vars/artifactSetVersion.groovy, vars/batsExecuteTests.groovy, vars/buildExecute.groovy, vars/gaugeExecuteTests.groovy, vars/karmaExecuteTests.groovy, vars/mailSendNotification.groovy, vars/newmanExecute.groovy, vars/seleniumExecuteTests.groovy, vars/slackSendNotification.groovy, vars/sonarExecuteScan.groovy, vars/uiVeri5ExecuteTests.groovy, vars/whitesourceExecuteScan.groovy
=> Exchange non serializable template engine with GStringTemplateEngine

.codeclimate.yml
=> Disable return statement maintainability check

documentation/docs/steps/dockerExecuteOnKubernetes.md, resources/default_pipeline_environment.yml, test/groovy/CloudFoundryDeployTest.groovy, test/groovy/MulticloudDeployTest.groovy, vars/dockerExecuteOnKubernetes.groovy
=> User piper docker images

documentation/docs/steps/xsDeploy.md
=> correct typos in xsDeploy documentation

cmd/piper.go
Add missing command to piper binary
=> Add karma command

cmd/getConfig.go, cmd/githubPublishRelease_generated.go, cmd/karmaExecuteTests_generated.go, cmd/piper.go, cmd/piper_test.go, cmd/version_generated.go, pkg/generator/step-metadata.go, pkg/generator/testdata/TestProcessMetaFiles/step_code_generated.golden
First part in #956 missed to export the elements of the struct ...
... and the function to open configuration files required for steps.
=> Export general configuration - part 2

documentation/bin/createDocu.groovy
=> Fix docu generation for nexus stage step

vars/cfManifestSubstituteVariables.groovy
=> Fix documentation of cfManifestSubstituteVariables step

Dockerfile
**changes:**
- correct `ldflags` options
=> fix version command

.pipeline/config.yml, .travis.yml, Dockerfile, pkg/generator/helper/helper.go
Add publishing of latest binary version to GitHub release
=> Add publishing of master binary to latest release

test/groovy/SonarExecuteScanTest.groovy, vars/sonarExecuteScan.groovy
**changes:**
- unstash `git` stash before executing Sonar scan
- provide `env.CHANGE_BRANCH ` as `sonar.pullrequest.branch` instead of local branch name
fixes #946
=> fix: sonar PR voting

pkg/config/stepmeta.go, pkg/config/stepmeta_test.go
=> Add Docker options to the step meta data

documentation/docs/scenarios/CAP_Scenario.md
Fixes broken links in documentation
=> Fix broken links in scenario documentation

resources/default_pipeline_environment.yml, vars/mtaBuild.groovy
**changes:**
- `mtaBuild` step can use `devici/mbtci` and `cloudMBT` tool
https://hub.docker.com/r/devxci/mbtci
fixes #953
=> feat: enable mtaBuild to use cloudMBT

.travis.yml
=> Docu generation for GoLang Steps

vars/sonarExecuteScan.groovy
as SonarQube LTS has now moved to v7.9
=> docs(sonar): correct sonar docs

resources/default_pipeline_environment.yml
see https://github.com/SAP/cloud-mta-build-tool/issues/611
**changes:**
- use updated Docker image
=> fix(mta): update docker image to fix npm.sap.com ssl issue

vars/artifactSetVersion.groovy
=> Fix TBD in docu

src/com/sap/piper/integration/TransportManagementService.groovy, vars/tmsUpload.groovy
=> Proxies for TMS calls

resources/metadata/xsDeploy.yaml
=> Adjust image pull policy property in metadata for xs deploy

vars/whitesourceExecuteScan.groovy
=> Fix NPE in case no version specified in descriptor

src/com/sap/piper/mta/MtaMultiplexer.groovy, test/groovy/com/sap/piper/mta/MtaMultiplexerTest.groovy
=> whitesourceExecuteScan: Avoid node_modules are treated like project modules

cmd/githubCreatePullRequest.go, cmd/githubCreatePullRequest_generated.go, cmd/githubCreatePullRequest_generated_test.go, cmd/githubCreatePullRequest_test.go, cmd/piper.go, resources/metadata/githubcreatepr.yaml
This step will be helpful for GitOps like workflows.
=>  Add step githubCreatePullRequest

test/groovy/CloudFoundryCreateServiceKeyTest.groovy, vars/cloudFoundryCreateServiceKey.groovy
=> add parameter compatibilitiy to cloudFoundryCreateServiceKey

vars/whitesourceExecuteScan.groovy
=> whitesourceExecuteScan: Resilience for report generation

vars/dockerExecuteOnKubernetes.groovy
Otherwise we continue and will fail later.
That violates the fail fast principle and causes higher costs in terms of support efforts compared to a situation where we fail immediately.
=> Don't swallow Exception happening inside dockerExecOnK8S.stashWorkspace

pkg/http/http.go, pkg/http/http_test.go
=> Add upload of files to HTTP capabilities

src/com/sap/piper/DefaultValueCache.groovy, test/groovy/CommonStepsTest.groovy, test/groovy/XsDeployTest.groovy, vars/commonPipelineEnvironment.groovy, vars/xsDeploy.groovy
xsDeploy now with go. The groovy step is now only a stub which forwards to the go binary.
=> xsDeploy.groovy forwarding to go

test/groovy/XsDeployTest.groovy, vars/xsDeploy.groovy
=> mta file via CPE and better support for configuration handling

test/groovy/PiperPublishWarningsTest.groovy
**changes:**
- reset `metaClass` after tests
related to #1098
=> chore(tests): cleanup metaClass

pkg/http/http.go, pkg/http/http_test.go
=> improved Upload to handle http.Method

.gitignore, src/com/sap/piper/Utils.groovy, src/com/sap/piper/versioning/MavenArtifactVersioning.groovy, test/groovy/ArtifactSetVersionTest.groovy, test/groovy/CommonStepsTest.groovy, test/groovy/MavenExecuteTest.groovy, test/groovy/com/sap/piper/versioning/MavenArtifactVersioningTest.groovy, vars/mavenExecute.groovy
* add evaluateFromMavenPom to piper Utils
* adapt mavenExecute to accept `returnStdout` as parameter. If configured mavenExecute will return the stdout for further processing
* adapt tests of mavenExecute and mavenArtifactVersioning as well as adding another exception to CommonStepsTest because mavenExecute will return a String if configured
=> Use maven eveluate for mavenArtifactVersioning

cmd/checkmarxExecuteScan.go, pkg/piperutils/stepResults.go, pkg/piperutils/stepResults_test.go, src/com/sap/piper/JenkinsUtils.groovy, test/groovy/CheckmarxExecuteScanTest.groovy, test/groovy/com/sap/piper/JenkinsUtilsTest.groovy, vars/checkmarxExecuteScan.groovy
=> Avoid potential collisions among steps

.github/workflows/verify-go.yml, .github/workflows/verify-groovy.yml
**changes:**
- beside `on push` also trigger `on pull_request`
=> chore(pipeline): enable GH actions for PRs from forks

cmd/piper.go, cmd/piper_test.go
fixes #1032 
superseeds #1038 
- ~[ ] Documentation~ n/a
=> Support yml and yaml extension of config files

DEVELOPMENT.md, cmd/checkmarxExecuteScan_test.go
=> Fix chars in checkmarx test, improve development.md

pkg/docker/docker.go
=> Docker functionality fix interface

DEVELOPMENT.md, pkg/checkmarx/checkmarx.go, pkg/checkmarx/checkmarx_test.go
=> Small cleanup

cmd/protecodeExecuteScan.go, cmd/protecodeExecuteScan_generated.go, resources/metadata/protecode.yaml
=> adjust protecode influx parameter

vars/piperStageWrapper.groovy
Fixes configuring sidecars for the given stage when Jenkins runs on Kubernetes.
=> Pass stageName to dockerExecuteOnKubernetes

cmd/protecodeExecuteScan_generated.go, resources/metadata/protecode.yaml
=> Adjust documentation for Protecode

test/groovy/CloudFoundryDeployTest.groovy, test/groovy/NeoDeployTest.groovy, vars/cloudFoundryDeploy.groovy, vars/neoDeploy.groovy
fixes #857
With this change the *Shell Script* that actually failed is also marked a such.
=> refactor: ease debugging in blue ocean

cmd/githubPublishRelease.go, cmd/githubPublishRelease_test.go
=> Fixed error handling gitHubPublishRelease

documentation/docs/index.md
=> Fix broken link

pkg/generator/helper/helper.go
Switch to correct interface in step example
=> Correct step generator

src/com/sap/piper/WhitesourceConfigurationHelper.groovy, src/com/sap/piper/integration/WhitesourceOrgAdminRepository.groovy, vars/whitesourceExecuteScan.groovy
=> Avoid using Iterators to get around NotSerializableException

documentation/docs/configuration.md, documentation/docs/pipelines/cloud-sdk/build-tools.md, documentation/docs/pipelines/cloud-sdk/shared-config-between-projects.md, documentation/docs/scenarios/CAP_Scenario.md
=> Document new sdk config location

test/groovy/SeleniumExecuteTestsTest.groovy, vars/seleniumExecuteTests.groovy
**changes:**
- fix NPE when no suitable entry in `containerPortMappings` is maintained
=> fix: handle NPE in seleniumExecuteTests

documentation/docs/steps/handlePipelineStepErrors.md
=> Try improving the provided example

.github/workflows/verify-go.yml, integration/integration_test.go
**changes:**
- fix usage of *local piper* in integration tests
- cleanup *integration* workflow
=> chore: streamline GH actions

src/com/sap/piper/DebugReport.groovy, src/com/sap/piper/k8s/ContainerMap.groovy, vars/dockerExecuteOnKubernetes.groovy
=> Avoid NotSerializableException #3

vars/dockerExecute.groovy
=> NotSerializableException next part

.github/workflows/release-go-master.yml, .github/workflows/release-go.yml, .travis.yml
Eat your own dogfood
This makes the release process more transparent and verifies our own GitHub Action.
=> Release go-binary via piper action

pkg/command/command.go
=> docs(command): Clarify runExecutable Env usage

vars/piperPipelineStageRelease.groovy
=> Add missing config for tmpUpload

resources/com.sap.piper/pipeline/stashSettings.yml
=> Fix issue with deployment related stashing in `piperPipeline`

test/groovy/DockerExecuteOnKubernetesTest.groovy, vars/dockerExecute.groovy, vars/dockerExecuteOnKubernetes.groovy
Bug. Before sidecarEnvVars sidecarWorkspace were ignored as parameters
=> Fix sidecar env vars

.pipeline/config.yml
Same configuration as the old release process used
=> Configure GitHub Release

resources/default_pipeline_environment.yml
=> Always pull sidecar images by default

cmd/abapEnvironmentPullGitRepo.go
=> Increase timeout limit for abapEnvironmentPullGitRepo()

documentation/docs/steps/nexusUpload.md, documentation/mkdocs.yml
=> Generate documentation for nexusUpload Groovy part

vars/cloudFoundryCreateServiceKey.groovy
Removed the report parameter from piperExecuteBin which causes the step to fail
=> Removed report from piperExecuteBin

test/groovy/com/sap/piper/integration/TransportManagementServiceTest.groovy
=> TMS: exchange dummy(.)com in junit tests with a more secure 

.github/workflows/integration-tests.yaml
Sorry. Follow-up of https://github.com/SAP/jenkins-library/pull/1375
=> Allow MEMBERs to trigger integration tests

vars/setupCommonPipelineEnvironment.groovy
=> add stash for pipeline custom defaults

consumer-test/TestRunnerThread.groovy, consumer-test/jenkins.yml
=> Use new piper identifier in tests

test/groovy/UiVeri5ExecuteTestsTest.groovy, vars/newmanExecute.groovy, vars/uiVeri5ExecuteTests.groovy
=> UIVeri5 & Newman: provide better error messages

src/com/sap/piper/DebugReport.groovy, test/groovy/DockerExecuteOnKubernetesTest.groovy, test/groovy/PiperStageWrapperTest.groovy, test/groovy/com/sap/piper/DebugReportTest.groovy, vars/dockerExecuteOnKubernetes.groovy, vars/piperStageWrapper.groovy
In some kubernetes environment nothing should run on the master node, but new pods should be spawned. 
This change adds on option to enable this behavior.
=> Add option to always run stages in a pod

test/groovy/BatsExecuteTestsTest.groovy, test/groovy/ContainerExecuteStructureTestsTest.groovy, test/groovy/GaugeExecuteTestsTest.groovy, test/groovy/UiVeri5ExecuteTestsTest.groovy, vars/batsExecuteTests.groovy, vars/containerExecuteStructureTests.groovy, vars/gaugeExecuteTests.groovy, vars/karmaExecuteTests.groovy, vars/newmanExecute.groovy, vars/uiVeri5ExecuteTests.groovy
=> Improve error messages for test failures

cmd/protecodeExecuteScan.go, cmd/protecodeExecuteScan_generated.go, resources/metadata/protecode.yaml
align parameter name for scan user with other steps
=> protecodeExecuteScan - align user parameter

.github/workflows/integration-tests.yaml, consumer-test/consumerTestController.groovy
Before the branch name was not passed correctly to the script and thus the scripts were skipped on master.
=> Fix integration tests on master

documentation/docs/steps/mavenBuild.md
=> Document mavenBuild

documentation/docs/steps/artifactPrepareVersion.md, documentation/docs/steps/artifactSetVersion.md, documentation/docs/steps/batsExecuteTests.md, documentation/docs/steps/buildExecute.md, documentation/docs/steps/detectExecuteScan.md, documentation/docs/steps/gaugeExecuteTests.md, documentation/docs/steps/jenkinsMaterializeLog.md, documentation/docs/steps/kanikoExecute.md, documentation/docs/steps/mailSendNotification.md, documentation/docs/steps/pipelineStashFiles.md, documentation/docs/steps/pipelineStashFilesAfterBuild.md, documentation/docs/steps/pipelineStashFilesBeforeBuild.md, documentation/docs/steps/sonarExecuteScan.md, documentation/docs/steps/testsPublishResults.md
Fix typo `Prerequsites` for `Prerequisites`
=> fix: typo `Prerequsites`

src/com/sap/piper/PiperGoUtils.groovy
Small change to allow seeing which version of piper is used in IT scenarios.
=> Set piper exe version when under test

vars/piperExecuteBin.groovy
=> Golang errors: improve error message in groovy part

pkg/log/fatalHook.go, pkg/versioning/docker.go, pkg/versioning/docker_test.go, vars/sonarExecuteScan.groovy
=> Docker versioning: fall back to custom

cmd/piper.go
=> Handle illegal verbose value

pkg/generator/helper/docuHelper.go, pkg/generator/helper/docuHelper_test.go
related to #1485
**changes:**
- print *possible values* for boolean parameters
=> docs: add possible value for bool parameters

test/groovy/PiperExecuteBinTest.groovy, vars/artifactPrepareVersion.groovy, vars/checkmarxExecuteScan.groovy, vars/piperExecuteBin.groovy
=> Allow proper usage of resilience feature in golang steps

pkg/protecode/protecode.go
**changes:**
- in case of an error don't access the response body
=> fix(protecode): handle api request issues

documentation/docs/steps/protecodeExecuteScan.md
=> docs: fix protecode example

pkg/log/log.go
=> Handle case when stepname is not set for logging

pkg/log/sentryHook.go
The exception object in the logrus fire method implementation will now be created and filled regardless of the found error type in entry.Data
=> SentryHook: Fixed issue of unlabeled events

resources/default_pipeline_environment.yml
There was already a config key in the defaults for jenkinsKubernetes.
=> Merge duplicated jenkinsKubernetes keys in defaults

pkg/generator/helper/helper.go, pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden
=> Fix generator for custom steps

vars/abapEnvironmentPullGitRepo.groovy
Should fix https://github.com/SAP/jenkins-library/issues/1551
See https://github.com/SAP/jenkins-library/blob/master/resources/metadata/abapEnvironmentPullGitRepo.yaml#L15
=> Fix name of credentials ID param

cmd/mtaBuild.go, cmd/mtaBuild_generated.go, cmd/mtaBuild_test.go, resources/metadata/mtaBuild.yaml
=> Allow to configure sap npm registry in mta builder

cmd/getConfig.go, pkg/config/stepmeta.go, pkg/config/stepmeta_test.go, resources/metadata/mtaBuild.yaml
=> mtaBuild - change default for docker image

.github/workflows/release-go.yml
=> Fix piper version to v1.34.0 for release

.github/workflows/release-go.yml, .github/workflows/update-go-dependencies.yaml, .github/workflows/upload-go-master.yml
Follow-up of https://github.com/SAP/jenkins-library/pull/1576
=> Use master version of piper binary in all usages of the action

cmd/detectExecuteScan.go
=> detectExecuteScan - switch off phone home

documentation/docs/pipelines/cloud-sdk/introduction.md
=> Fix typo in docs

.github/workflows/release-go.yml
=> Publish jar for releases

src/com/sap/piper/BuildTool.groovy, src/com/sap/piper/DownloadCacheUtils.groovy, test/groovy/DownloadCacheUtilsTest.groovy, vars/artifactPrepareVersion.groovy, vars/fortifyExecuteScan.groovy, vars/mavenBuild.groovy, vars/mavenExecute.groovy, vars/mavenExecuteStaticCodeChecks.groovy, vars/mtaBuild.groovy, vars/nexusUpload.groovy, vars/npmExecuteScripts.groovy
- NPMRegistry was always an empty string
- MTA did not use npm registry
=> Fix injection of download cache parameters

cmd/artifactPrepareVersion.go, cmd/artifactPrepareVersion_generated.go, cmd/artifactPrepareVersion_test.go, pkg/generator/helper/resources.go, pkg/generator/helper/testdata/TestProcessMetaFiles/custom_step_code_generated.golden, pkg/generator/helper/testdata/TestProcessMetaFiles/step_code_generated.golden, resources/metadata/versioning.yaml, test/groovy/CommonPipelineEnvironmentTest.groovy, vars/commonPipelineEnvironment.groovy
=> artifactPrepareVersion: remember original artifact version

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_test.go
=> Add build project name

resources/metadata/mtaBuild.yaml
=> Use fixed versions for docker images for mtaBuild

documentation/mkdocs.yml
=> Restore alphabetical order of docs

pkg/config/config.go
=> Update deprecation message

cmd/mavenBuild_test.go, cmd/nexusUpload.go, cmd/nexusUpload_test.go, cmd/npmExecuteScripts_test.go, pkg/mock/fileUtils.go, pkg/mock/fileUtils_test.go, pkg/piperutils/FileUtils.go, pkg/piperutils/fileUtils_test.go
* Add more commonly used functionality to Files, such as DirExists(), FileRemove(), Glob() and so on.
* Flesh out the existing mock.FilesMock implementation.
* Avoid a lot of code-duplication by using a type of struct embedding that results in combining interface implementations.
=> Enhance piperutils.Files and mock.FilesMock

resources/com.sap.piper/pipeline/stageDefaults.yml, test/groovy/templates/PiperPipelineStageSecurityTest.groovy, vars/piperPipelineStageSecurity.groovy
Add new steps
* checkmarxExecuteScan
* fortifyExecuteScan
closes #1650
=> extend security stage

cmd/jsonApplyPatch.go, cmd/jsonApplyPatch_test.go
=> Let json patcher fail if file not found

vars/influxWriteData.groovy
This change allows the [Influx Jenkins plugin](https://github.com/jenkinsci/influxdb-plugin/blob/c191e69eb34b0a7bf81b4e45ae0402d59272d821/src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java#L117-L124) to report Sonar findings as `sonarqube_data` to the Influx database.
Due to a change in the Plugin, this was not possible recently:
```log
14:02:58  [InfluxDB Plugin] SonarQube data found. Writing to InfluxDB...
14:02:58  [InfluxDB Plugin] INFO: No SonarQube host URL found in environment variable SONAR_HOST_URL. Using build log instead.
14:02:58  [InfluxDB Plugin] WARNING: No SonarQube auth token found in environment variable SONAR_AUTH_TOKEN. Depending on access rights, this might result in a HTTP/401.
14:02:58  [InfluxDB Plugin] Failed to collect data. Ignoring …
```
=> fix(influx): pass Sonar token to influx

vars/piperPipelineStageSecurity.groovy
=> fix(security): remove duplicate stage wrapper

resources/com.sap.piper/pipeline/abapStashSettings.yml
=> Fix extensions for Post stage of ABAP Pipeline

cmd/sonarExecuteScan_generated.go, cmd/sonarExecuteScan_test.go, resources/metadata/sonar.yaml
=> Upgrade sonar-scanner-cli to 4.4.0.2170

cmd/artifactPrepareVersion_generated.go, cmd/sonarExecuteScan_generated.go, pkg/config/stepmeta.go, resources/metadata/sonar.yaml, resources/metadata/versioning.yaml
=> Extend resource references to cater for secrets

cmd/sonarExecuteScan.go, pkg/log/fatalHook.go, pkg/log/sentryHook.go
=> sonarExecuteScan: add error categorization

pkg/yaml/yamlUtil.go
reality teaches us that we need to handle that type
=> handle map[interface]interface{} in yaml utils substitute

resources/metadata/mtaBuild.yaml
=> Upgrade cloud mbt tool docker image version

pkg/cloudfoundry/Authentication.go, pkg/cloudfoundry/CloudFoundry_test.go
~~This PR is based on PR #1737. For this PR it is sufficient to review all commits which are not already contained in the other PR.~~
We are using a mock now and we assert the commands which are issue to the `cf` command line tool.
=> More accurate tests for cf login check and cf login

documentation/docs/extensibility.md
=> Update docs on js linting in Cloud SDK Pipeline

vars/multicloudDeploy.groovy
=> Expose enableZeroDowntimeDeployment as step parameter

vars/multicloudDeploy.groovy
Stage config should of precedence over step config
=> Multicloud change config order

test/groovy/PiperExecuteBinTest.groovy, vars/piperExecuteBin.groovy
=> Fix stashing of piper binary

documentation/docs/pipelines/abapEnvironment/configuration.md, vars/abapEnvironmentPipelineStageATC.groovy
=> Adapt documentation for abap pipeline

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
=> Create stage run defaults for the Cloud SDK Pipeline

pkg/config/config_test.go, pkg/config/stepmeta.go, pkg/config/stepmeta_test.go, test/groovy/CommonPipelineEnvironmentTest.groovy, vars/commonPipelineEnvironment.groovy
=> Support lists in commonPipelineEnvironment

pkg/config/stepmeta.go, test/groovy/CommonPipelineEnvironmentTest.groovy, vars/commonPipelineEnvironment.groovy
=> Fix commonPipelineEnvironment issue

pkg/config/config.go, pkg/config/config_test.go
=> Apply alias to secrets

pkg/generator/helper/docuHelper.go, pkg/generator/helper/docuHelper_test.go, src/com/sap/piper/integration/CloudFoundry.groovy
=> Documentation: fix parameter links & some spelling

DEVELOPMENT.md, cmd/piper.go, main.go
=> move generate command to main.go

vars/npmExecuteEndToEndTests.groovy
=> Fix npmExecuteEndToEndTests

documentation/docs/pipelines/abapEnvironment/configuration.md
=> Fix error in documentation

pkg/generator/helper/docuHelper.go, pkg/generator/helper/docuHelper_test.go
=> DocGenerator: fix links to secrets

cmd/gctsCloneRepository_generated.go, cmd/gctsCreateRepository_generated.go, cmd/gctsDeploy_generated.go, cmd/gctsExecuteABAPUnitTests_generated.go, documentation/docs/steps/gctsCloneRepository.md, documentation/docs/steps/gctsCreateRepository.md, documentation/docs/steps/gctsDeploy.md, documentation/docs/steps/gctsExecuteABAPUnitTests.md, resources/metadata/gctsCloneRepository.yaml, resources/metadata/gctsCreateRepository.yaml, resources/metadata/gctsDeployCommit.yaml, resources/metadata/gctsExecuteABAPUnitTests.yaml
Improved and fixed gCTS step documentation.
=> gCTS docu fixes

cmd/abapEnvironmentRunATCCheck.go, cmd/abapEnvironmentRunATCCheck_test.go
=> Create fix for ABAP ATC step

documentation/docs/steps/detectExecuteScan.md
The step is golang based thus no dependency to a Jenkins plugin ...
=> detectExecuteScan: fix docs

src/com/sap/piper/Utils.groovy
When running inside a jenkins file runner scenario these parameters might
not be available.
=> fix file runner use case

cmd/detectExecuteScan.go, cmd/detectExecuteScan_generated.go, cmd/detectExecuteScan_test.go, cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_generated.go, resources/metadata/detect.yaml, resources/metadata/fortify.yaml
align with Fortify to also use the same versioning model by default.
=> detectExecuteScan: update versioning

cmd/mavenExecuteStaticCodeChecks.go, cmd/mavenExecuteStaticCodeChecks_test.go
=> Update maven spotbugs plugin to support Java 14

cmd/kanikoExecute_test.go, cmd/mtaBuild.go, cmd/mtaBuild_test.go, cmd/xsDeploy_test.go, pkg/command/command.go, pkg/maven/settings_test.go, pkg/mock/fileUtils.go, pkg/mock/runner.go, pkg/piperutils/FileUtils.go
=> Support m2path for mtaBuild

cmd/piper.go, cmd/piper_test.go, pkg/config/config.go, pkg/log/sentryHook.go
=> Fix reading of hook configuration

cmd/kubernetesDeploy_generated.go, resources/metadata/kubernetesdeploy.yaml
used for backward compatibility
=> kubernetesDeploy: add step configuration alias

documentation/docs/pipelines/cloud-sdk/build-tools.md
=> Reflect recent changes for unit tests in cloud sdk projects in docs

documentation/docs/cli/index.md
=> Hint about piper binary on non-linux os

cmd/mtaBuild_generated.go, resources/metadata/mtaBuild.yaml
=> Add mta alias for maven parameter

vars/piperExecuteBin.groovy
This change enables the publication of step results also if the step execution itself failed.
=> fix(step results): publish step results also on step error

cmd/piper.go
=> type error: avoid message `Error: <nil>`

pkg/abaputils/abaputils.go, pkg/abaputils/abaputils_test.go
=> Addon descriptor

cmd/kubernetesDeploy.go, cmd/kubernetesDeploy_generated.go, cmd/kubernetesDeploy_test.go, resources/metadata/kubernetesdeploy.yaml
=> kubernetesDeploy - improve helm parameter handling

cmd/artifactPrepareVersion.go, cmd/getConfig.go
=> artifactPrepareVersion: improve error categorization

cmd/abapEnvironmentCloneGitRepo.go, documentation/docs/steps/abapEnvironmentCloneGitRepo.md, documentation/mkdocs.yml, test/groovy/CommonStepsTest.groovy, vars/abapEnvironmentCloneGitRepo.groovy
=> Add groovy file and documentation for cloneGitRepo step

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
=> Fix stageDefaults for fortify and mavenStaticCodeChecks

cmd/protecodeExecuteScan_test.go
=> Make protecodeExecuteScan tests run in temp dir

vars/tmsUpload.groovy
=> small docu change for mtar path

documentation/docs/extensibility.md, documentation/docs/pipelines/cloud-sdk/build-tools.md, documentation/docs/pipelines/cloud-sdk/cloud-qualities.md
This change updates the documentation provided for the linting
capabilities of the Cloud SDK Pipeline.
=> Update Cloud SDK Pipeline docs on linting

documentation/docs/pipelines/cloud-sdk/build-tools.md, documentation/docs/pipelines/cloud-sdk/configuration.md
=> Update Cloud SDK docs on linting and static code checks

cmd/checkmarxExecuteScan.go, cmd/checkmarxExecuteScan_test.go
=> checkmarxExecuteScan: Fix access to projects

documentation/mkdocs.yml
=> Add mavenExecuteIntegration to documented steps

documentation/docs/pipelines/cloud-sdk/configuration.md
=> Remove duplicated docs of steps that are documented in piper

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
This change renames the Cloud SDK Pipeline stage `frontendUnitTests` to `additionalUnitTests`.
=> Rename frontendUnitTests to additionalUnitTests stage

cmd/checkmarxExecuteScan.go
=> checkmarxExecuteScan: fix PR project identification

resources/metadata/checkmarx.yaml, resources/metadata/cloudFoundryCreateService.yaml, resources/metadata/cloudFoundryCreateServiceKey.yaml, resources/metadata/cloudFoundryDeleteService.yaml, resources/metadata/cloudFoundryDeploy.yaml, resources/metadata/fortify.yaml, resources/metadata/kaniko.yaml, resources/metadata/kubernetesdeploy.yaml, resources/metadata/malwareExecuteScan.yaml, resources/metadata/nexusUpload.yaml, resources/metadata/protecode.yaml, resources/metadata/sonar.yaml, resources/metadata/versioning.yaml, resources/metadata/whitesource.yaml, resources/metadata/xsDeploy.yaml
Add / update Jenkins credential descriptions
Documentation only.
=> Documentation: Improve Jenkins credential docs

cmd/mtaBuild_generated.go, resources/metadata/mtaBuild.yaml
Based on https://github.com/SAP/jenkins-library/issues/2060
=> Improve docs on mtaBuild installArtifacts

DEVELOPMENT.md
=> doc: fix an invalid relative link

pkg/documentation/generator/parameters.go
Adds link to Jenkins *using credentials* HowTo.
fixes #2074
=> docs: add note about Jenkins credentials

cmd/checkmarxExecuteScan.go, cmd/checkmarxExecuteScan_test.go, pkg/checkmarx/checkmarx.go, pkg/checkmarx/checkmarx_test.go
improve  / update error handling: bubble up errors.
This will prevent error message like 
`ERROR: [checkmarxExecuteScan] Step execution failed (category: undefined). Error: <nil>` 
in Jenkins pipelines.
In addition it provides the foundation for better error categorization.
=> checkmarxExecuteScan: update error handling

documentation/docs/pipelines/cloud-sdk/configuration.md, documentation/docs/steps/debugReportArchive.md, documentation/mkdocs.yml, resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml
This change updates the Cloud SDK documentation with the changes of migrating to
the `piperPipelineStageInit` and update the legacy configuration settings accordingly. 
In addition, it fixes the documentation of the step `debugReportArchive` and includes
it in the list of library steps.
=> Update Cloud SDK documentation

documentation/docs/pipelines/cloud-sdk/configuration.md, resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml, resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml, resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml, resources/com.sap.piper/pipeline/cloudSdkLegacyConfigSettings.yml, resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml, resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
Updates containersMap, stash settings, stage defaults and legacy config settings.
=> Preparation to switch to piperPipelineStageSecurity for Cloud SDK pipeline 

documentation/docs/pipelines/cloud-sdk/build-tools.md, documentation/docs/pipelines/cloud-sdk/cloud-qualities.md, documentation/docs/pipelines/cloud-sdk/configuration.md
=> Remove absolute links from Cloud SDK docs section

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
The parameter name for the new step is "productName", not "product".
=> Fix conditions for whitesourceExecuteScan

vars/dockerExecute.groovy
Having that like this increases maintainability.
=> [refactoring] Avoid having simiar dockerExecuteOnKubernetes call twice.

vars/piperPipelineStagePost.groovy
=> Archive debug report in piper post action stage

cmd/detectExecuteScan.go, cmd/detectExecuteScan_generated.go, cmd/detectExecuteScan_test.go, resources/metadata/detect.yaml, vars/detectExecuteScan.groovy
support backward compatibility
=> detect: add parameter aliases

cmd/checkmarxExecuteScan.go
fixes a regression introduced with #2084 
fixes #2103
=> fix : allow creation of Checkmarx projects

resources/com.sap.piper/pipeline/cloudSdkContainersMap.yml, resources/com.sap.piper/pipeline/cloudSdkJavaStashSettings.yml, resources/com.sap.piper/pipeline/cloudSdkJavascriptStashSettings.yml, resources/com.sap.piper/pipeline/cloudSdkMtaStashSettings.yml, resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml
This change updates and cleans up the Cloud SDK specific stash settings
and stage defaults.
=> Update Cloud SDK stash settings and stage defaults

cmd/abapEnvironmentAssemblePackages.go
Handover from one struct to another was missing
=> Fix call issue to abap build framework

cmd/sonarExecuteScan.go
Add Error Categories for 
- unable to download plugin
- unable to connect to instance
- no class files provided
=> chore(sonar): assign error categories to know error cases

cmd/kubernetesDeploy.go, cmd/protecodeExecuteScan.go, pkg/docker/docker.go, pkg/maven/maven.go
=> Improve error categorization

src/com/sap/piper/Utils.groovy, vars/piperPipelineStageInit.groovy
=> Infer project name

pkg/checkmarx/checkmarx.go
=> Avoid nil reference access

cmd/abapEnvironmentCheckoutBranch.go, cmd/abapEnvironmentCloneGitRepo.go, cmd/abapEnvironmentPullGitRepo.go, cmd/abapEnvironmentRunATCCheck.go, pkg/abaputils/abaputils.go
=> Fix GetHTTPResponse func

documentation/docs/index.md
=> Add ABAP Environment Pipeline to piper docs index

vars/cloudFoundryDeploy.groovy
=> Docu description of buildTool

documentation/docs/pipelines/abapEnvironment/introduction.md
=> ABAP Pipeline docu fixes

resources/default_pipeline_environment.yml
=> Also stash war files as build result

cmd/mavenExecuteStaticCodeChecks.go, cmd/mavenExecuteStaticCodeChecks_test.go
=> Update spotbugs-maven-plugin to 4.1.4

vars/cloudFoundryDeploy.groovy
Fixes https://github.com/SAP/jenkins-library/issues/2235
=> Fix cloudFoundryDeploy documentation

test/groovy/util/JenkinsPropertiesRule.groovy
=> Support for properties provided as text

cmd/fortifyExecuteScan.go
=> fortifyExecuteScan: increase timeout

cmd/fortifyExecuteScan.go, cmd/fortifyExecuteScan_test.go, pkg/fortify/fortify.go
=> fortifyExecuteScan: Fix report download

cmd/fortifyExecuteScan_generated.go, resources/metadata/fortify.yaml
=> Update Fortify Documentation

resources/com.sap.piper/pipeline/cloudSdkStageDefaults.yml, test/groovy/templates/PiperInitRunStageConfigurationTest.groovy, vars/piperInitRunStageConfiguration.groovy
Only rely on "runInAllBranches" to be configured either in stage defaults, or in project config.
=> Remove "onlyInProductiveBranch" check

pkg/maven/maven.go, pkg/maven/maven_test.go
=> Pass project settings to flatten command

pkg/checkmarx/checkmarx.go
=> checkmarxExecuteScan: Relax timeout

cmd/mavenExecuteStaticCodeChecks.go, cmd/mavenExecuteStaticCodeChecks_generated.go, cmd/mavenExecuteStaticCodeChecks_test.go, resources/metadata/mavenStaticCodeChecks.yaml
=> Add option to install artifacts before running static code checks

cmd/piper.go, cmd/piper_test.go, resources/metadata/npmExecuteLint.yaml
=> fix(config) conversion of small ints into string

resources/metadata/npmExecuteScripts.yaml
=> Add default stashes for npmExecuteScripts
